### ISSUE TITLE
`redirect_cleartext_from: 80` has no effect

### ISSUE THREAD

**Issue by samuela** [datawire/ambassador#1000]
**Describe the bug**
I have Ambassador set up with TLS termination but the `redirect_cleartext_from: 80` seems to have no effect. 

Here's the Service description include the TLS termination Module:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  annotations:
    getambassador.io/config: |
      # From https://www.getambassador.io/user-guide/tls-termination/.
      apiVersion: ambassador/v0
      kind: Module
      name: TLS
      config:
        # The 'server' block configures TLS termination. 'enabled' is the only
        # required element.
        server:
          # If 'enabled' is not True, TLS termination will not happen.
          enabled: True
          # If you set 'redirect_cleartext_from' to a port number, HTTP traffic
          # to that port will be redirected to HTTPS traffic. Typically you would
          # use port 80, of course.
          redirect_cleartext_from: 80

          # These are optional. They should not be present unless you are using
          # a custom Docker build to install certificates onto the container
          # filesystem, in which case YOU WILL STILL NEED TO SET enabled: True
          # above.
          #
          # cert_chain_file: /etc/certs/tls.crt   # remember to set enabled!
          # private_key_file: /etc/certs/tls.key  # remember to set enabled!
          # Enable TLS ALPN protocol, typically HTTP2 to negotiate it with
          # HTTP2 clients over TLS.
          # This must be set to be able to use grpc over TLS.
          alpn_protocols: h2
        # The 'client' block configures TLS client-certificate authentication.
        # 'enabled' is the only required element.
        client:
          # If 'enabled' is not True, TLS client-certificate authentication will
          # not happen.
          enabled: False

          # If 'cert_required' is True, TLS client certificates will be required
          # for every connection.
          # cert_required: False
          # This is optional. It should not be present unless you are using
          # a custom Docker build to install certificates onto the container
          # filesystem, in which case YOU WILL STILL NEED TO SET enabled: True
          # above.
          #
          # cacert_chain_file: /etc/cacert/tls.crt  # remember to set enabled!
spec:
  type: LoadBalancer
  # This must be a static IP in the same GCP region as the cluster.
  loadBalancerIP: 35.236.77.11
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  selector:
    service: ambassador
```

**Expected behavior**
I expected http://foo.kumo.run to be redirected to https://foo.kumo.run and work as expected. Instead, I see that https://foo.kumo.run can be accessed as normal, but http://foo.kumo.run refuses connections:
```
~ -> curl https://foo.kumo.run
Hello, world!
Version: 1.0.0
Hostname: foo-deployment-667cf67d6-54mlx
~ -> curl http://foo.kumo.run 
curl: (7) Failed to connect to foo.kumo.run port 80: Connection refused
```

**Versions (please complete the following information):**
 - Ambassador: 0.40.2
 - Kubernetes environment: GKE

**Additional context**
See https://github.com/datawire/ambassador/issues/995.

**Comment by nbkrause** [comment]
Turns out the tls `Module` **is** case sensitive. Should be
```
annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
          alpn_protocols: h2
        client:
          enabled: False
```
