### ISSUE TITLE
Ambassador - APIs mapping issue (upstream request timeout)

### ISSUE THREAD

**Issue by rkrgarlapati** [datawire/ambassador#1041]
Have installed kubectl cluster on Ubuntu 16x.

I am trying to setup ambassador api gateway for my microservices using springboot webservices, followed this doc : https://www.getambassador.io/user-guide/getting-started/

When i tried to call my service API, there is no response from Ambassador.

`curl http://10.102.202.159/userparty/party/`

Throws the error : upstream request timeout
I guess mapping is not happening properly.

```
rshoba@kubernetesMaster:/home/rkrshoba$ kubectl get deployments
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
ambassador      3/3     3            3           25h
guids           1/1     1            1           2d16h
userparty       1/1     1            1           5s

rshoba@kubernetesMaster:/home/rkrshoba$ kubectl get pods
NAME                             READY   STATUS             RESTARTS   AGE
ambassador-5dc8d7b97b-5gch7      1/1     Running            0          25h
ambassador-5dc8d7b97b-jlwlm      1/1     Running            0          25h
ambassador-5dc8d7b97b-jmql7      1/1     Running            0          25h
guids-68898f7dc9-rn4hr           1/1     Running            0          2d16h
userparty-64789c558b-rzh55       1/1     Running            0          9s

rshoba@kubernetesMaster:/home/rkrshoba$ kubectl get services
NAME               TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
ambassador         LoadBalancer   10.102.202.159   <pending>     80:31986/TCP     25h
ambassador-admin   NodePort       10.103.52.235    <none>        8877:30387/TCP   25h
httpbin            ClusterIP      10.99.83.116     <none>        80/TCP           25h
userparty          ClusterIP      10.108.168.179   <none>        80/TCP           26s
kubernetes         ClusterIP      10.96.0.1        <none>        443/TCP          2d16h
```

Server started smoothly. I don't see any errors in logs :  `kubectl logs --selector app=userparty
`
I guess, ambassador and my service mapping is not happening properly. Kindly help me to debug this issue. 

This is the ONLY  yaml file i have. This will download image from azure repository and deploys on Kubernetes cluster.

(kubectl apply -f myconnect.yaml)

```
apiVersion: v1
kind: Service
metadata:
  name: userparty
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  userparty
      prefix: /userparty/
      service: userparty:8089
      host_rewrite: userparty
spec:
  type: ClusterIP
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userparty
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: userparty
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: userparty
        image: myconnectregistry.azurecr.io/myconnect/myconnectexample:latest
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always
        ports:
        - name: userparty
          containerPort: 8089
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
```

**Comment by shalkam** [comment]
Aside from ambassador service to get it up and running. there should be a separate service config file for the userparty app.
This part of userparty service config is messed up
```
spec:
  type: ClusterIP
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
```
So, supposing that you already have the userparty deployment up and running, you simply need to add a service for it like this:
```
kind: Service
apiVersion: v1
metadata:
  name: userparty
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  userparty
      prefix: /userparty/
      service: userparty
      host_rewrite: userparty
spec:
  selector:
    app: userparty
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```
Hopefully that will work on your end.

Regards,
Mostafa
