### ISSUE TITLE
change timezone Ambassador logs

### ISSUE THREAD

**Issue by zencircle** [datawire/ambassador#1046]
**Describe the bug**
Typical docker settings to change the timezone does not work for Ambassador. Option to change timezone from default UTC to EST

**To Reproduce**
Create ambassador deployment with timzone info:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        service: ambassador
    spec:
      serviceAccountName: ambassador
      containers:
      - name: ambassador
        image: quay.io/datawire/ambassador:0.40.2
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace          
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
#       - name: statsd
#        image: quay.io/datawire/statsd:0.39.0
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
           path: /usr/share/zoneinfo/America/New_York
      restartPolicy: Always
```
**Expected behavior**
Log should change to EST format 

**Versions (please complete the following information):**
 - Ambassador: [0.40.2]
 - Kubernetes environment [DCOS Kubernetes]
 - Version [e.g. 1.10.8]

**Additional context**
As any alternative approach update `default` the envoy template.    
https://www.getambassador.io/reference/override   
to  `add zone offset value` mentioned in envoy documentation    
https://www.envoyproxy.io/docs/envoy/latest/operations/cli.html?highlight=timezone
