### ISSUE TITLE
TLS Module w/o Secret Does not Configure Ambassador to Listen on 443

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#1104]
Regression starting in `0.50.0-rc2`.

Configuring a TLS module without a certificate should configure Ambassador to listen on port 443. The primary use of this is if you are terminating TLS at an L4 LoadBalancer, you need `redirect_cleartext_from: 80` for http -> https redirection. This can only be configured in a TLS `module`. 

Adding this TLS `Module`:
```
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: true
          redirect_cleartext_from: 80
```
Should cause Ambassador to listen on 443 and redirect traffic from 80. Starting in `0.50.0-rc2`, Kubewatch errors out on that TLS module `2019-01-11 16:59:56 kubewatch [36 TRestarter] 0.50.0 ERROR: service ambassador, namespace default.1: <RichStatus BAD error=TLSContext server found no certificate in secret ambassador-certs in namespace default hostname=ambassador-5958f9547f-k8g45 resolvedname=192.168.0.8 version=0.50.0>`.
