### ISSUE TITLE
Ambassador does not throw an error when client cert is configured without TLS termination

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#1147]
Steps to reproduce:

Configure ambassador with a Mapping that looks like -
```yaml
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name: tls
      config:
        client:
          enabled: True
          secret: client-cert-secret
          cert_required: True
```

Ambassador does not throw an error that TLS termination is not configured.
