### ISSUE TITLE
TLS module alongwith SNI crashes Ambassador (crash on invalid configuration)

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#1156]
Envoy goes for a toss when it's fed an invalid configuration, i.e. it goes in an infinite loop with 100% CPU usage.

A configuration like the following where SNI and TLS module are both configured -

```yaml
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: same-context-2
      hosts:
      - tls-context-host-2
      secret: same-secret-2
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          secret: user-secret
```

When the resulting configuration is fed to envoy, the following message is logged infinitely -
```
[2019-01-28 14:00:34.606][000034][warning][config] [bazel-out/k8-dbg/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener ambassador-listener-443: error adding listener '0.0.0.0:443': partial wildcards are not supported in "server_names"
```

and no response is received to any request.
