### ISSUE TITLE
TLS, ambassador, cert-manager, and HTTP challenge

### ISSUE THREAD

**Issue by Mimetis** [datawire/ambassador#1158]
Hello all. I'm trying to setup a config with **ambassador** in **Azure**.   
For now, **ambassador** is just used as an ingress controller, and that's work fine.   
Troubles arrive when I try to setup a TLS config using **cert-manager**.   
I can't used **DNS** acme-challenge since my TLS domain is the one created for my K8S by Azure (something like `myrepo.westeurope.cloudapp.azure.com` )    

That's why I'm stuck using **HTTP** challenge resolution.

The problem comes from how **cert-manager** is working.  
One configured, to be able to challenge the domain, **cert-manager** will dynamically generate a `deployment` / `service` / `ingress` to be able to expose the famous `.well-known/acme-challenge/OXiBFblablablalbla` url.

Since we don't have any ingress controller installed, the service is not reachable.

Of course I tried to implement my own service, to handle correctly the request, but it doesn't work at all.
(*Well today, the urls and name are hardcoded, it's another problem to solve, but for now, it's just fine testing like that*)

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  acme-challenge-mapping
      prefix: /.well-known/acme-challenge/OXiBF7fN601nISblablbalbla 
      service: nginx 
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    certmanager.k8s.io/acme-http-domain: "3932818779"
    certmanager.k8s.io/acme-http-token: "782372305"
 
```
The logs from the cert pod contains this relevant log:

``` cmd
logger.go:93] Calling HTTP01ChallengeResponse
prepare.go:279] Cleaning up old/expired challenges for Certificate default/ambassador-certs
logger.go:68] Calling GetChallenge
http.go:145] presented key () did not match expected (OXiBF7fN60blablablabla.vt8Zlzf-eC5Dj9dnanananana)
```

**To Reproduce**

Installing cert-manager using `helm`
``` cmd
helm install stable/cert-manager  --set ingressShim.defaultIssuerName=letsencrypt-staging --set ingressShim.defaultIssuerKind=ClusterIssuer
```
Installing the `https` ambassador (with RBAC) stuff

Installing a straightforward sample
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - name: azure-vote-back
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
      - name: azure-vote-front
        image: microsoft/azure-vote-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  azure-vote-front-mapping
      prefix: /
      service: azure-vote-front  
spec:
  ports:
  - port: 80
  selector:
    app: azure-vote-front
```

**Versions (please complete the following information):**
Last versions of everything :)

**Comment by Mimetis** [comment]
Continuing my investigations.
One of the problem comes from the `rewriting` default behavior
Adding the `rewrite = ""` options makes the validation working:

``` yaml
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      rewrite: ""
      name:  acme-challenge-mapping
      prefix: /.well-known/acme-challenge
      service: nginx
```

Now I want to avoid using a generated selector:
``` yaml
  selector:
    certmanager.k8s.io/acme-http-domain: "3932818779"
    certmanager.k8s.io/acme-http-token: "782372305"
```
any idea ?

And now my certificate (in the same namespace as `ambassador`) with the correct name (`ambassador-certs`) is not loaded by `ambassador` even if I delete my `ambassador` pod. any idea ?

Tthx a lot

**Comment by Mimetis** [comment]
Hey guyz, no one to help here .
I've just write a full sample, available here : [Handle ambassador TLS with cert-manager](https://github.com/Mimetis/ambassadorandtls)

I still have some issues:
- Need to notice the selectors
- Need to start ambassador once (to have the load balancer) then restart it to handle ssl certificate
- I didn't test it, but I think I will have some troubles when I will have to renew the certificate...

Any idea ?

**Comment by richarddli** [comment]
0.50-rc6 detects when certs change and will auto-reload them. See the release notes.

**Comment by Mimetis** [comment]
Thx @richarddli for the precision. Good to know we won't have to restarts ambassador when a new cert appears.
A part from that, do you have any idea on how to handle the pod binding to the service we need to create ?

My assumption is that the domain encoded value (`certmanager.k8s.io/acme-http-domain: "3932818779"` in my sample) will never change over time (am I correct ?)
But not sure if it will be the same for the token encoded value (`certmanager.k8s.io/acme-http-token: "782372305"`) ?

If I'm sure it won't change over time, that's enough for my scenario, but we need to be sure of this point.

Any idea ?

**Comment by LiVe** [comment]
hey,

i went through similar thing as you did a while back and came up with pretty much the same solutions. only difference, i'm only using a selector with
certmanager.k8s.io/acme-http-domain: <val>
which works fine for me. skipped the token.

the acme-http-domain value is a adler32 hash of the domain. so it wont change. there are topics in the cert-manager repo regarding this suggesting custom selector options and / or changing the adler32 hash to something helm can use (then it would be just a template function for us). but im not  sure if anything changed since my adventure down that road :)

**Comment by richarddli** [comment]
Now documented here: https://www.getambassador.io/user-guide/cert-manager

**Comment by Mimetis** [comment]
Thx @richarddli for the updated documentation.

Just for your information, I have created a small repo with a readme doc, about installing cert-manager in an AKS cluster.

I know my English is not really as good as it should be, but you may found useful information on this topic:
[https://github.com/Mimetis/ambassadorandtls](https://github.com/Mimetis/ambassadorandtls)

**Comment by derekperkins** [comment]
@Mimetis has your cert renewed yet? Did the `acme-http-token` change or did you have to take any manual steps?

**Comment by Mimetis** [comment]
Unfortunatelly, the project is not yet released in production, and I don't work anymore on it :)
I guess, it "should" be updated since cert-manager is handle it, by default (in my memories)

**Comment by tegamckinney** [comment]
@richarddli With the auto-reload feature, how does it work with the http01 challenged.  I noticed that the token changed (but not the domain).  Is ambasador somehow updating the challenge service so that the cert can be regenerated and then it loads it?

**Comment by Mercbot7** [comment]
I think this may work.
You may want to try something like this:

```yaml
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  # Adjust the name here accordingly
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: user@example.com
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: ambassador
          ingressTemplate:
            metadata:
              annotations:
                getambassador.io/config: |
                    ---
                    apiVersion: ambassador/v2
                    kind: Mapping
                    name: acme-challenge-service-mapping-stage
                    rewrite: ""
                    prefix: /.well-known/acme-challenge/
```

**Comment by cr1cr1** [comment]
Tried @Mercbot7 suggestion. And it.. kind of works. I mean I do get a sometimes reachable endpoint, http://mydomain.com/.well-known/acme-challenge/g_Se6IDLLZbjAIZML2o3UXtfRBaU9VpMm_zjeIfR7Y9

Using:

```yaml
  annotations:
    getambassador.io/config: |
      apiVersion: getambassador.io/v3alpha1
      kind: Mapping
      metadata:
        name: acme-challenge-mapping
      spec:
        hostname: "*"
        prefix: /.well-known/acme-challenge/
        rewrite: ""
        service: "*:8089"
```

- `service` field is mandatory in `apiVersion: getambassador.io/v3alpha1`
- Using `*:8089` will result in envoy DNS resolver obtaining all services from the current namespace, after appending the port, in my case `8089`. 
- This means that most of services in the current namespace will fail, since not listening on port 8089 (except the cert-manager autogenerated one), resulting everytime but one in `upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111`
- Lentsencrypt will try to reach the generated endpoint, but will fail every time, somehow never reaching the 1 working instance
- This means that certificates will not be signed
- Perhaps adding some kind a parameter (that I have yet to find) to the `Mapping` object as to test first if upstream is available and not route traffic if not? This would in theory leave only the working one.

I do not really get the "cert-manager uses an Ingress to issue the challenge to /.well-known/acme-challenge/ that is incompatible with Ambassador." part from the docs: https://www.getambassador.io/docs/emissary/latest/howtos/cert-manager/#http-01-challenge

Why is a standard regular ingress incompatible?

The suggested solution is not the nicest, especially since I have tens of subdomains, meaning I would need to create a new `Service` and a `Mapping` in every namespace that has an ingress defined.

Also, the default `ingressClass` for an `Issuer/ClusterIssuer` must be something else than `ambassador`, and eventually non existent, or an ingress-controller that does not occupy port `80`, so the Mapping can do its job for `/.well-known/acme-challenge/`, and having a useless ingress object created by `cert-manager`
