### ISSUE TITLE
host_rewrite causes canary deployment to fail

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#1159]
I have some test canary configuration like -

```YAML
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  qotm_mapping_1
      prefix: /qotm/
      service: qotm
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  qotm_mapping_2
      prefix: /qotm/
      service: httpbin.org:80
      host_rewrite: httpbin.org
      weight: 50
```

One of the mappings is ignored completely and diag reports the error -
```
qotm.default.1: cannot accept new mapping qotm_mapping_2 with mismatched host_rewrite: httpbin.org != -unset-
```

As soon as I remove `host_rewrite` from the config, the canary starts working fine.

I can reproduce this every time right now, but I have a faint memory that this was intermittent while testing (might help while debugging)
