### ISSUE TITLE
Custom Auth Headers not being sent using ambassador auth

### ISSUE THREAD

**Issue by jisaacstone** [datawire/ambassador#1173]
**Describe the bug**
This bug is in 2 parts:
First: custom headers set in my ambassador auth endpoint are not being forwarded to downstream requests
Second: the custom header is _not_ being stripped out of external requests.

The first problem causes authentication not to work, the second problem is a security problem. Probably these problems are related.

**To Reproduce**
Was chatting with `nkrause` on the slack and he said to create an issue. I'll just describe the setup we have best I can. I can yell at devops if we need more details

We got a cluster for dev with several namespaces, I've taken one namespace to spin up a cluster trying to get ambassador auth to work. For the `auth-server` service I have these ambassador annotations:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  auth_mapping
      prefix: /o/
      rewrite: /o/
      service: auth-server:8080
      timeout_ms: 15000
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  auth_admin_mapping
      prefix: /oauth-admin/
      rewrite: /oauth-admin/
      service: auth-server:8080
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: auth-server:8080
      path_prefix: "/o/autheader"
      allowed_request_headers:
        - "x-z-experiments"
      allowed_authorization_headers:
        - "cookie"
        - "x-z-userid"
      allow_request_body: false
```

**Expected behavior**
I expect when I call any backend endpoint that ambassador will forward the request to my auth service, and if the auth service responds with a 200 and x-z-userid set then the request will be forwarded to the downstream service with x-z-userid set. I also expect if the original request includes an x-z-userid header it will be stripped out by ambassador.

**Versions (please complete the following information):**
 - Ambassador: 0.38.0
 - Kubernetes environment: some Azure thing
 - Version: don't know

**Additional context**
Here's my debug logs:

```
[2019-01-31 21:37:58.412][61][debug][http] source/common/http/conn_manager_impl.cc:798] [C4156][S8695434922728941466] request end stream

[2019-01-31 21:37:58.412][61][debug][http] source/common/http/conn_manager_impl.cc:454] [C4156][S8695434922728941466] request headers complete (end_stream=true):
':authority', 'stone.dev.azure.example.com'
':path', '/api/accounts/v3/accounts/current'
':method', 'GET'
'user-agent', 'curl/7.43.0'
'accept', '*/*'
'authorization', 'Bearer m6FtlXv49k7Rvi8ucPFJuN4F97vmqb'
'x-foo', 'BAR'

[2019-01-31 21:37:58.412][61][debug][router] source/common/router/router.cc:253] [C0][S8546781774831249735] cluster 'cluster_ext_auth' match for URL '/o/autheader/api/accounts/v3/accounts/current'
[2019-01-31 21:37:58.412][61][debug][router] source/common/router/router.cc:304] [C0][S8546781774831249735] router decoding headers:
':authority', 'stone.dev.azure.example.com'
':path', '/o/autheader/api/accounts/v3/accounts/current'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.43.0'
'accept', '*/*'
'authorization', 'Bearer XXXXXXXXXXXX'
'x-foo', 'BAR'
'x-forwarded-proto', 'https'
'x-request-id', '8fd33790-9486-901d-9548-e2adffedd1bd'
'x-b3-traceid', '0c55ac9b43467d3d'
'x-b3-spanid', '0c55ac9b43467d3d'
'x-b3-sampled', '1'
'content-length', '0'
'x-ambassador-calltype', 'extauth-request'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.7.0.112'
'x-envoy-expected-rq-timeout-ms', '5000'

[2019-01-31 21:37:58.412][61][debug][pool] source/common/http/http1/conn_pool.cc:79] creating a new connection
[2019-01-31 21:37:58.412][61][debug][client] source/common/http/codec_client.cc:25] [C4158] connecting
[2019-01-31 21:37:58.412][61][debug][connection] source/common/network/connection_impl.cc:569] [C4158] connecting to 10.0.181.71:8080
[2019-01-31 21:37:58.412][61][debug][connection] source/common/network/connection_impl.cc:578] [C4158] connection in progress
[2019-01-31 21:37:58.412][61][debug][pool] source/common/http/http1/conn_pool.cc:105] queueing request due to no available connections
[2019-01-31 21:37:58.413][61][debug][connection] source/common/network/connection_impl.cc:466] [C4158] connected
[2019-01-31 21:37:58.413][61][debug][client] source/common/http/codec_client.cc:63] [C4158] connected
[2019-01-31 21:37:58.413][61][debug][pool] source/common/http/http1/conn_pool.cc:249] [C4158] attaching to next request
[2019-01-31 21:37:58.413][61][debug][router] source/common/router/router.cc:972] [C0][S8546781774831249735] pool ready
[2019-01-31 21:37:58.427][61][debug][router] source/common/router/router.cc:584] [C0][S8546781774831249735] upstream headers complete: end_stream=false
[2019-01-31 21:37:58.428][61][debug][http] source/common/http/async_client_impl.cc:92] async http request response headers (end_stream=false):
':authority', 'stone.dev.azure.example.com'
':status', '200'
'content-type', 'text/html; charset=utf-8'
'user-agent', 'curl/7.43.0'
'accept', '*/*'
'x-foo', 'BAR'
'x-forwarded-proto', 'https'
'x-request-id', '8fd33790-9486-901d-9548-e2adffedd1bd'
'x-b3-traceid', '0c55ac9b43467d3d'
'x-b3-spanid', '0c55ac9b43467d3d'
'x-b3-sampled', '1'
'x-ambassador-calltype', 'extauth-request'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.7.0.112'
'x-envoy-expected-rq-timeout-ms', '5000'
'x-z-userid', '3'
'x-frame-options', 'SAMEORIGIN'
'vary', 'Accept-Language, Cookie'
'content-language', 'en'
'content-length', '0'
'x-envoy-upstream-service-time', '15'

[2019-01-31 21:37:58.428][61][debug][client] source/common/http/codec_client.cc:94] [C4158] response complete
[2019-01-31 21:37:58.428][61][debug][filter] source/extensions/filters/http/extauthz/extauthz.cc:203] [C4156][S8695434922728941466] ExtAuth accepting request
[2019-01-31 21:37:5.428][61][debug][router] source/common/router/router.cc:253] [C4156][S8695434922728941466] cluster 'cluster_backend_8080' match for URL '/api/accounts/v3/accounts/current'
[2019-01-31 21:37:58.428][61][debug][router] source/common/router/router.cc:304] [C4156][S8695434922728941466] router decoding headers:
':authority', 'stone.dev.azure.example.com'
':path', '/api/accounts/v3/accounts/current'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.43.0'
'accept', '*/*'
'authorization', 'Bearer XXXXXXXXXXXXXXXX'
'x-foo', 'BAR'
'x-forwarded-proto', 'https'
'x-request-id', '8fd33790-9486-901d-9548-e2adffedd1bd'
'x-b3-traceid', '0c55ac9b43467d3d'
'x-b3-spanid', '0c55ac9b43467d3d'
'x-b3-sampled', '1'
'x-envoy-expected-rq-timeout-ms', '15000'
'x-envoy-original-path', '/api/accounts/v3/accounts/current'
```
