### ISSUE TITLE
LightStep gRPC TracingService broken in 0.50.0

### ISSUE THREAD

**Issue by krishicks** [datawire/ambassador#1189]
**Describe the bug**
Configuring a TracingService with LightStep using the gRPC endpoint does not work; it causes the Ambassador container to crash loop.

**To Reproduce**
Configure a TracingService pointing at LightStep's gRPC endpoint, collector-grpc.lightstep.com:

```yaml
      ---
      apiVersion: ambassador/v0
      kind: TracingService
      name: lightstep
      service: collector-grpc.lightstep.com:443
      driver: lightstep
      config:
        access_token_file: /config/lightstep_access_token
```

Do a fresh deploy of Ambassador. See that the pod is in CrashLoopBackOff with a message like:

```
[2019-02-04 22:50:41.328][000063][critical][main] [source/server/server.cc:81] error initializing configuration '/ambassador/bootstrap-ads.json': cluster_tracing_collector_grpc_lightstep_com_443 collector cluster must support http2 for gRPC calls
```

**Expected behavior**
The deploy to be successful, and LightStep tracing to work.

**Versions (please complete the following information):**
 - Ambassador: 0.50.0-rc8
 - Kubernetes environment GKE
 - Version 1.11

**Additional context**

There was a prior commit that fixed this for 0.40, 0687180d. Oddly, the file that was there is not reachable from HEAD of master but _also_ has no git log of being deleted, which confuses me.

The problem is that the configured tracing cluster is missing `http2_protocol_options: {}`; see the Envoy example [here](https://github.com/envoyproxy/envoy/blob/master/configs/envoy_front_proxy_v2.template.yaml#L122).

I was able to at least get 0.50.0 deployed by deleting the TracingService configuration and adding it later. It shows up in the Ambassador admin page as being configured without error, but it does not actually work; no spans are sent.

See related issue https://github.com/datawire/ambassador/issues/796.
