### ISSUE TITLE
simple grpc config return 404

### ISSUE THREAD

**Issue by protheusfr** [datawire/ambassador#1199]
**Describe the bug**
On a fresh install of Ambassador (0.50.1) I've try to expose a grpc service to outside in order to reach them via gRPC-Web (https://github.com/grpc/grpc-web).

Then from what I've understand in doc : 

```
client (JS) ---gRPC-Web--->Ambassador LB---->Service----->Pod
HTTP 1.1       HTTP 1.1                     HTTP 2.0
```

**To Reproduce**

Service config : 
```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: qa
  name: dataservices-mobile
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: dataservice_qa_grpc
      grpc: true
      prefix: /lm.object.DataService.Authenticate
      rewrite: /lm.object.DataService.Authenticate
      service: dataservices-mobile.qa:9090
spec:
  selector:
    app: dataservice-mobile
  ports:
    - port: 2553
      name: akka
    - port: 9090
      name: grpc
```

Please note Ambassador is located in an `ambassador` namespace.

**Expected behavior**
On grpc call on `lm.object.DataService.Authenticate` get a response.
But I recieve a 404 response, the Ambassador logs show the following : 
```
ACCESS [2019-02-08T13:34:52.904Z] "OPTIONS /lm.object.DataService/Authenticate HTTP/1.1" 404 NR 0 0 0 - "93.16.138.77" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36" "79be193f-5971-4d11-9bd8-6ce48ad9d767" "X.X.X.X" "-"
```

**Versions (please complete the following information):**
 - Ambassador: 0.50.1
 - Kubernetes environment : bare metal 
 - Version : v1.13.3
