### ISSUE TITLE
Canary routing by weight or header

### ISSUE THREAD

**Issue by edfungus** [datawire/ambassador#1227]
**Please describe your use case / problem.**
We use weighted routing to give canary 2% of production traffic; however, it would be nice to be able to target the canary instances explicitly too. 

**Describe the solution you'd like**
A solution could be similar to `canary-by-header-value` in ingress-nginx (https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#canary) where I can use headers to force a request to be handled by the canary instances.  

For example,
```yaml
---
apiVersion: ambassador/v1
kind:  Mapping
name:  helloworld_dev
prefix: /
service: helloworld-service
weight: 50      
headers:
  x-target-canary: true
```
would respect both the `weight` and the `headers`. Right now it seems like the `headers` take priority and the `weight` is ignored.

**Describe alternatives you've considered**
I can route to the canary instances through a different ingress but ideally everything can happen via Ambassador 

**Additional context**
If there is a better work around or I missed something, let me know! Thanks!
