### ISSUE TITLE
Enable access to AuthService endpoints via Mapping

### ISSUE THREAD

**Issue by GabrielCiordas** [datawire/ambassador#1251]
**Please describe your use case / problem.**
Ambassador is the gateway to the resources in the Kubernetes cluster.
I have set up an authentication service in k8s that should:
1. Act as an authentication service upstream for all requests that do not have "bypass_auth" enabled
2. Expose some public endpoints for authentication to return a JWT

For this scenario the documentation indicates that it is possible to add multiple config snippets to any k8s service, so logically I created a Mapping and an AuthService snippet, both in the same ambassador config.
This way I want to have access to all my services public endpoints AND have all my requests validated by the internal service validator.
The above described configuration returns 404 to my service endpoints if I have both Mapping and AuthService enabled in Ambassador config.

**Describe the solution you'd like**
It should be possible to have an Ambassador config as follows:
```yaml
annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: my-auth-service
      prefix: /auth/
      service: my-service-url
      rewrite: /auth/
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: my-authentication
      auth_service: my-service-url
      path_prefix: /auth/token/validate
```

**Describe alternatives you've considered**
I am unable to consider alternatives due to project constraints.

**Additional context**
Can be made available per request.
