### ISSUE TITLE
TLS custom secret with period in name does not work

### ISSUE THREAD

**Issue by richardbolt** [datawire/ambassador#1255]
**Describe the bug**
When your custom TLS secret name has a period (.) in the name Ambassador will fail to start Envoy and will error thinking the first part before the period is the secret name. Quoting the secret name in the annotation does not make a difference.

```
RichStatus BAD error=TLSContext server found no certificate in secret with in namespace period, ignoring...
```

Bad Module/tls configuration:

```yaml
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
          secret: with.period
```

Good configuration:

```yaml
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
          secret: withoutperiod
```

**To Reproduce**
Create a secret with a name of "with.period" and appropriate tls.key and tls.cert values
Apply the "Bad" example Module/tls annotation
Observe the error in Ambassador logs and the diagnostics UI

**Expected behavior**
The "with.period" secret should be read as specified in the Module/tls annotation and Ambassador should successfully start Envoy

**Versions (please complete the following information):**
 - Ambassador: 0.50.3
 - Kubernetes environment: AKS
 - Version: 1.12.5

**Additional context**
Secrets with periods in the name were working successfully in Ambassador 0.40.2
