### ISSUE TITLE
Documentation ambiguities

### ISSUE THREAD

**Issue by derrickburns** [datawire/ambassador#1256]
**Describe the bug**
The documentation on integrating Ambassador and Istio is riddled with ambiguities. I need to use mTLS for HIPAA compliance.  I don't want to spend a week trying to figure this out. Please help. :)

**Example 0**
```
Istio's basic ingress controller is very limited, and has no support for authentication or many of the other features of Ambassador
```
While the sentence is factually true, it is misleading.  Istio offers a Gateway now. So, comparing Ambassador to the Istio Ingress Controller is inappropriate. 

**Example 1**
```
(Note that if you are planning to use mutual TLS for communication between Ambassador and Istio/services in the future, then the order in which you deploy the ambassador-admin service and the ambassador LoadBalancer service below may need to be swapped)
```
Well, what does this mean in practice.  What is the order?  What should the order be?  How does one affect the order, particularly if one is implementing GitOps?

**Example 2**
```
Optionally, delete the Ingress controller from the bookinfo.yaml manifest by typing kubectl delete ingress gateway.
```
What ingress gateway?  Is this created by istio?  Why is this optional? What happens if you don't delete it?  Why should one delete it?

**Example 3**
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
        client:
          enabled: False
        upstream:
          cert_chain_file: /etc/istiocerts/cert-chain.pem
          private_key_file: /etc/istiocerts/key.pem
```
This includes a `Mapping` and a `Module`.  Why?  Why not just include a` Module`?  The point is the certs, right?  How else can one provide the `Module` outside of a service?  Why are these combined here?

**Example 4**
```
This will define an upstream that uses the Istio certificates. We can now reuse the upstream in all Ambassador mappings to enable communication with Istio pods.
```
What is an `upstream`?  How can it be reused?  Why do I care?

**Example 5**
```
First we need to change our Ambassador Deployment to use the Prometheus StatsD Exporter as its sidecar. Do this by applying the ambassador-rbac-prometheus.yaml:
```
What does StatsD have to do with Prometheus?  Why is a StatsD exporter needed?
