### ISSUE TITLE
Docs are wrong

### ISSUE THREAD

**Issue by derrickburns** [datawire/ambassador#1258]
https://www.getambassador.io/reference/ambassador-with-aws/

the names of the keys are wrong
```
service:
  enableHttp: true 
  enableHttps: true 

  targetPorts:
    http: 80
    https: 80

  httpPort: 80
  httpsPort: 443
```
