### ISSUE TITLE
Client certificate authentication not working

### ISSUE THREAD

**Issue by shettyh** [datawire/ambassador#1262]
**Describe the bug**
I am trying to setup the Mutual Authentication with Ambassador. Something like
```
Client ----- 2 WAY SSL ---> Ambassador ----- Not secure link ---> My Service
```

My config is as below 
```
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: true
          alpn_protocols: h2
        client:
          enabled: true
          cert_required: true
```

I am setting both `ambassador-certs` and `ambassador-cacerts` secrets.

Even though i have enabled the client authentication , it still works like One Way TLS. Client certs are not verified.

**To Reproduce**
1. Create One gRPC service with no certificate
2. Add Ambassador configs as shown above
3. Add Service mapping
4. Try to access. Services are accessed without client certificates !

**Expected behavior**
Client certificated should be verified

**Versions (please complete the following information):**
 - Ambassador: 50.3
 - Kubernetes environment: Bare meta
 - Version: 1.11

**Additional context**
Tried with both gRPC and HTTPs
