### ISSUE TITLE
Helm Chart : cannot upgrade from chart on datawire repository to stable/hub version

### ISSUE THREAD

**Issue by draeron** [datawire/ambassador#1268]
I've been trying to upgrade a chart install from `0.50.1` to `0.50.3` and it seems the match labels were changed from the two version of the chart, that field is immutable so helm will refuse the upgrade.

I've been trying to figure out the changeset to the chart which caused this but i can't find the history seems like it was copied over to the official stable repository.

```Error: UPGRADE FAILED: Deployment.apps "ambassador-dev" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"ambassador-dev", "app.kubernetes.io/instance":"ambassador-dev"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable```

Versions:
k8s: `1.10.11`
helm: `2.11.0`
chart: `0.50.1` (from datawire repo) to `1.1.15` (stable/ambassador)
ambassador: `0.50.1` to `0.50.3`

**Comment by draeron** [comment]
In template/deployment.yaml: 

Was :
```yaml
selector:
  matchLabels:
     app: {{ include "ambassador.name" . }}
     release: {{ .Release.Name }}
```

is now : 
```yaml
selector:
  matchLabels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
```
