### ISSUE TITLE
Memory usage in Ambassador (was: Split processes in multiple containers)

### ISSUE THREAD

**Issue by draeron** [datawire/ambassador#1297]
We have memory issues where the ambassador container grows out of it's memory since upgrade the latest 0.50.x. It's very hard to know what is the actual process which seems to be leaking memory since the ambassador container contains envoy, some python scripts, kubewatch and ambex.

I would humbly suggest to split those processes into multiple containers so that basic kube metrics such as cpu and memory usage can be found for each part of the pods. Also it would also help to segregate the logs from these process.

Inter process communication can be easily made through common volume mount such as `emptyDir` or through a loopback network.

**Comment by richarddli** [comment]
Can you post some more details about your configuration, e.g., # services, etc and more details by what "leaking memory" means? That would be very helpful.

**Comment by draeron** [comment]
Version: 0.50.3
Chart: 1.1.5
K8S Version: 1.10.11

This is an example of the memory usage over a couple of hours. The gateway runs on a sandbox cluster, no events happened in the cluster at that time which would explain why the memory would go up so fast all of the sudden.

![image](https://user-images.githubusercontent.com/2256246/54049168-d0cec100-41a9-11e9-90f1-77705742e6cd.png)
![image](https://user-images.githubusercontent.com/2256246/54049293-1a1f1080-41aa-11e9-8a1d-23153e26bcb7.png).

Since this is a test setup, we only got one service with a annotations mapping and one authentication service.

Configuration: 

```yaml
ambassador_id: test
apiVersion: ambassador/v1
config:
  service_port: 8443
kind: Module
name: ambassador
```

```yaml
ambassador_id: test
apiVersion: ambassador/v1
config:
  server:
    enabled: true
    redirect_cleartext_from: 8080
    secret: ambassador-svod-test-cert
kind: Module
name: tls
```

```yaml
ambassador_id: test
apiVersion: ambassador/v1
driver: zipkin
kind: TracingService
name: zipkin
service: zipkin.istio-system:9411
tag_headers:
- :authority
- :path
- x-client-id
- authorization
```
