### ISSUE TITLE
prefix_regex fails to interpret capture group with a pipe operator correctly

### ISSUE THREAD

**Issue by max-l-weaver** [datawire/ambassador#1315]
**Describe the bug**
We are using a `prefix_regex` in order to route two endpoints to the same service in Openshift. This is not working as expected and instead returns a 404 from envoy.

**To Reproduce**
1. `oc edit svc <service-name>`
2. add the following annotations in order to match two separate prefixes:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      name: "http-foo"
      prefix: /v1/foo/(server1|server2)/.*
      prefix_regex: true
      service: "http://http-foo.namespace.svc"
      apiVersion: ambassador/v1
      kind: Mapping
```
Attempt to curl both `GET /v1/foo/server1/path/to/something` and `GET /v1/foo/server2/path/to/something/else`

**Expected behavior**
Both urls should resolve to the same kubernetes service - instead both urls receive a 404 response.

**Versions (please complete the following information):**
 - Ambassador: 0.50.1
 - Kubernetes environment: Openshift
 - Version 3.11

**Additional context**
I have tried formatting the regex multiple ways. For example I have tried:

`\/v1\/foo\/(server1|server2)\/.*`
and
`^\\/v1\\/foo\\/((server1)|(server2))\\/.*`

amongst others

**Comment by max-l-weaver** [comment]
Any ideas on this? If we can't get the prefix_regex to work we cannot migrate our services to use Ambassador.

**Comment by kflynn** [comment]
Envoy uses the modified ECMAScript regex grammar (see https://en.cppreference.com/w/cpp/regex/ecmascript), so I'm not sure that capture groups work.

However, it should be straightforward to use two `Mapping`s for this:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: http-foo-1
      prefix: /v1/foo/server1/
      service: http://http-foo.namespace.svc
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      prefix: /v1/foo/server2/
      service: http://http-foo.namespace.svc
```

I'm going to go ahead and close this one -- reopen if needed!
