### ISSUE TITLE
Configuring client cert validation in a tls Module requires secret to be specified

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#1331]
**Describe the bug**
The docs indicate that you do not need to specify the secret that is storing the TLS client in the tls `Module` client configuration. If you do not specify a secret, it will look for and use `ambassador-cacert` as the secret holding the client ca certificate. This behavior is broken and you need to include `secret: ambassador-cacert` in the configuration to enable client certificate validation.

This does not work anymore:
```
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: true
          secret: ambassador-certs
          redirect_cleartext_from: 80
        client:
          enabled: true
```
 
Ambassador logs this error:

```
2019-03-19 16:01:49 diagd 0.50.3 [P44TAmbassadorEventWatcher] INFO: resolve_secrets working on: {
    "_active": false,
    "_errored": false,
    "_referenced_by": [
        "ambassador.default.2"
    ],
    "_rkey": "ambassador.default.2",
    "hosts": [
        "*"
    ],
    "kind": "IRTLSContext",
    "location": "ambassador.default.2",
    "name": "server",
    "redirect_cleartext_from": 80,
    "secret_info": {
        "secret": "ambassador-cacert"
    }
}
2019-03-19 16:01:49 diagd 0.50.3 [P44TAmbassadorEventWatcher] ERROR: ambassador.default.2: <RichStatus BAD error=TLSContext server found no private key in secret ambassador-cacert in namespace default hostname=ambassador-786c56c64f-knr9m resolvedname=10.8.0.6 version=0.50.3>
```

You need to specify `secret: ambassador-cacert` for Ambassador to be properly configured:

```
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: true
          secret: ambassador-certs
          redirect_cleartext_from: 80
        client:
          enabled: true
          secret: ambassador-cacert
```
