### ISSUE TITLE
0.51.2 envoy_override is not applied

### ISSUE THREAD

**Issue by simenbw** [datawire/ambassador#1348]
**Describe the bug**
envoy_override does not add idle_timeout to a route config
In my service mapping:
```
      apiVersion: ambassador/v1
      kind: Mapping
      name: grpc_service_mapping
      grpc: True
      prefix: "/dei.grpc.(.+)/(.*)"
      prefix_regex: True
      rewrite: ""
      auto_host_rewrite: True
      service: {{ $appName }}
      timeout_ms: 86400000
      ambassador_id: dei-staging-ambassador
      envoy_override:
        idle_timeout: 86400s
```

Here is envoy route config generated:
```
    "match": {
        "case_sensitive": true,
        "regex": "/dei.grpc.(.+)/(.*)"
    },
    "route": {
        "auto_host_rewrite": true,
        "priority": null,
        "timeout": "86400.000s",
        "weighted_clusters": {
            "clusters": [
                {
                    "name": "cluster_grpc_staging_server_dei_9429_dei_grpc_server",
                    "weight": 100.0
                }
            ]
        }
    }
},
```

**Expected behavior**
idle_timeout should be appended to Envoy route

**Versions (please complete the following information):**
 - Ambassador: 0.51.2
 - Amazon EKS
 - Version ?
