### ISSUE TITLE
tls: true, does not seem to work 

### ISSUE THREAD

**Issue by bitsofinfo** [datawire/ambassador#1362]
Using 0.50.3

The backend service I need to proxy to presents TLS on its port.

The docs say that you can set `tls: true` for this to work

This configuration does not work.

```
apiVersion: v1
kind: Service
metadata:
  namespace: my-apps
  name: my-app-4-1-3-1--1-3
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  my_app_mapping
      host: "^my-app-stage.local(:{1}\\d+)*$"
      host_regex: true
      prefix: /
      timeout_ms: 60000
      tls: true
      service: my-app-4-1-3-1--1-3:30000
spec:
  selector:
    app: my-app
    version: 4-1-3-1--1-3
    env: stage
  type: NodePort
  ports:
  - protocol: TCP
    port: 30000
    targetPort: app-port
    nodePort: 30000
```

This configuration DOES work

```
apiVersion: v1
kind: Service
metadata:
  namespace: my-apps
  name: my-app-4-1-3-1--1-3
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  my_app_mapping
      host: "^my-app-stage.local(:{1}\\d+)*$"
      host_regex: true
      prefix: /
      timeout_ms: 60000
      service: https://my-app-4-1-3-1--1-3:30000
spec:
  selector:
    app: my-app
    version: 4-1-3-1--1-3
    env: stage
  type: NodePort
  ports:
  - protocol: TCP
    port: 30000
    targetPort: app-port
    nodePort: 30000
```

see https://datawire-oss.slack.com/archives/CAULN7S76/p1553262170995000 for original discussion
