### ISSUE TITLE
Helm Chart : setting tls module on helm installation breaks ambassador 

### ISSUE THREAD

**Issue by hugocarrasco** [datawire/ambassador#1374]
**Describe the bug**
After creating a certificate secret with cert-manager and trying to get https working, ambassador gets stuck with the next error:

```
[000074][warning][config]
 [bazel-out/k8-dbg/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70]
 gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected:
 Error adding/updating listener redirect_listener: cannot bind '0.0.0.0:80': Permission denied
```

**To Reproduce**
1. Create a challenge successfully with cert-manager:
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ambassador-certs
  namespace: dev
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dev.api.example.com
  dnsNames:
  - dev.api.example.com
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - dev.api.example.com
```

2. Add tls module config on "service.annotations.getambassador.io/config", by adding this after ambassador module config:
```
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: ambassador-id
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
          secret: ambassador-certs

```
3. Get error printed in infinite loop.

![image](https://user-images.githubusercontent.com/2603514/55016408-f7d12380-4fee-11e9-89c3-ca5d9d057d78.png)

![image](https://user-images.githubusercontent.com/2603514/55016436-0cadb700-4fef-11e9-9591-d75bec1c41e9.png)

**Expected behavior**

I expect ambassador to work with https.

**Versions (please complete the following information):**
 - Ambassador: 0.52.0
 - Helm Chart: 2.0.1
 - Kubernetes environment: cluster over aws
   - Version : v1.11.7

**Additional context**

If I remove the ambassador_id on the config annotation ambassador starts properly (and works with http), because it ignores the configuration of the tls module.

**Comment by richarddli** [comment]
@Flydiverny ?

**Comment by Flydiverny** [comment]
You are trying to use port 80, the helm chart is not running as root.. so it can't bind to port 80 unless you change the security context. But its better if you use another port, eg 8080.

From chart [readme](https://hub.helm.sh/charts/stable/ambassador)

> NOTE: Make sure the configured service.http.targetPort and service.https.targetPort ports match your Ambassador Module's service_port and redirect_cleartext_from configurations.

**Comment by richarddli** [comment]
@Flydiverny maybe we can bold face the non-root thing in the docs and close this issue?

**Comment by hugocarrasco** [comment]
Hi!

I'm still with issues, probably is a confusion with the configs.

1. This config can't start the ambassador redirect (probably because is the same port ?):

```
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      ambassador_id: ambassador-development
      config:
        service_port: 8080
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: ambassador-development
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8080
          secret: ambassador-certs
```
Error:
```
[2019-03-28 10:31:31.279][000071][critical][config] [source/server/listener_manager_impl.cc:836] listener 'redirect_listener' failed to listen on address '0.0.0.0:8080' on worker
```

2. This config works but results on ambassador answering http over https:
```

      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      ambassador_id: ambassador-development
      config:
        service_port: 8080
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: ambassador-development
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8443
          secret: ambassador-certs

```
Error:

```
*   Trying *.*.*.*...
* Connected to XXXXX (*.*.*.*) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.
```

**Comment by Flydiverny** [comment]
Try the other way around? ie `service_port: 8443` and `redirect_cleartext_from: 8080`. Personally don't use ambassador with tls termination so not fully sure. But in 1 you are correct that it can't be the same port, as that would (I assume) cause ambassador to try to bind twice to that port.

By default it looks like ambassador will use [service_port 80](https://github.com/datawire/ambassador/blob/0d39641c170f0d1bd342d9e2d32737074fb41e91/ambassador/ambassador/ir/irambassador.py#L70) and then when tls termination is enabled it will set its [service_port to 443](https://github.com/datawire/ambassador/blob/0d39641c170f0d1bd342d9e2d32737074fb41e91/ambassador/ambassador/ir/irambassador.py#L161).

**Comment by hugocarrasco** [comment]
Thanks! now it works.

For future use this is the setting:

```
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      ambassador_id: ambassador-development
      config:
        service_port: 8443
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: ambassador-development
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8080
          secret: ambassador-certs
```
