### ISSUE TITLE
Ambassador cannot start, forbidden. was ok try to update. now downgrade not helping

### ISSUE THREAD

**Issue by badoet** [datawire/ambassador#1383]
start ambassador , keep crashing
in log it show this:
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden: User \"system:serviceaccount:ambassador:ambassador\" cannot watch services at the cluster scope","reason":"Forbidden","details":{"kind":"services"},"code":403}\n'

was ok, i was using 0.39.0
then tried to run
kubectl apply -f https://www.getambassador.io/yaml/ambassador/ambassador-rbac.yaml
run it to a separate namespace, i put it to default at first
but then i try to put it on ambassador2 namespace because my current is running on ambassador namespace

but upgrade not working
so i just try to clean up everything
but now my existing 0.39.0 also cannot start

kubectl version --short
Client Version: v1.14.0
Server Version: v1.10.5

**Comment by badoet** [comment]
turn out the clusterrole and cluterrolebinding from the new update override my current yaml settings

firstly cluterrolebinding change the namespace to default, so yes need to download the yaml in the installation instruction and check whats inside,

secondly clusterrole, mine looks like this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
  - patch
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
```

but in the new upgrade it becomes:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - services
  - secrets
  verbs: ["get", "list", "watch"]
```

so i need to revert the clusterrole back and also fix the clusterrolebinding namespace to get it to work again

now the question would be, can i still safely upgrade to latest ambassador version if i fix the clusterrolebinding namespace to the correct namespace as my current one?

or is there something very different from my current setting that cannot get upgraded seamlessly?
