### ISSUE TITLE
Update documentation for running ambassador as non-root with HTTPS

### ISSUE THREAD

**Issue by chtison** [datawire/ambassador#1415]
**Describe the bug**

I lost a lot of my time to fix this so allow me to be short.
I need to redirect HTTP to HTTPS in the chart `stable/ambassador:2.1.0` which docker image is `quay.io/datawire/ambassador:0.53.1`.

**Solution**

```yaml
service:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        service_port: 8443
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          redirect_cleartext_from: 8080
```
