### ISSUE TITLE
External  auth-service returns HTTP/404 instead of 401

### ISSUE THREAD

**Issue by venkyvb** [datawire/ambassador#1424]
**Describe the bug**
I am trying out the auth-tutorial - https://www.getambassador.io/user-guide/auth-tutorial/. 

I have deployed the below service and I expect the auth to kick in when the user enters just the http://AMBASSADORURL (as no path-prefix is defined). 

Without Basic Auth headers and the auth-service is designed to respond to the client with an HTTP/401. 

However I am getting an HTTP/404 when I do a curl. Am I missing something here? 

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  AuthService
      name:  authentication
      auth_service: "auth-service-svc:8080"
      allowed_request_headers:
      - "x-test-auth-session"
      allowed_authorization_headers:
      - "x-test-auth-token"
  name: auth-service-svc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: auth-service
  type: ClusterIP
```

**Versions (please complete the following information):**
 - Ambassador: 0.53.1
 - Kubernetes environment: EKS
 - Version : 1.11

**Additional context**
