### ISSUE TITLE
Ambassador stops routing correctly to gRPC endpoints when using the pod loadbalancer

### ISSUE THREAD

**Issue by peturgq** [datawire/ambassador#1435]
**First some background**
I am running an NLB in AWS, I am routing HTTP/2 to Ambassador from this NLB and doing TLS termination in Ambassador, I am using google's golang gRPC client to connect to a gRPC service
mapped into ambassador.

**The bug**
As soon as I add a loadbalancer config to either Ambassador or the mapping my connections get dropped, otherwise they work fine.

**To Reproduce**
1. Have a working setup like described in background.
2. Confirm that you are able to communicate with the gRPC endpoint through ambassador.
3. Now add the loadbalancer config as detailed in [here](https://blog.getambassador.io/session-affinity-load-balancing-controls-grpc-web-and-ambassador-0-52-2b916b396d0c)
4. See communication break to the gRPC endpoint.

**Expected behavior**
I expect the loadbalancer to route requests between different ambassador pods and continue working.
**Versions (please complete the following information):**
Built on master

**Comment by Abhishek627** [comment]
I'm also facing the same issue in my setup. But my endpoint responds intermittently , otherwise it gives  "rpc error: code = Unavailable desc = all SubConns are in TransientFailure". 

I am connecting from golang gRPC client using Insecure method.

**Comment by peturgq** [comment]
Here's what a request looks like when not using load_balancer
```[2019-04-17 14:00:55.732][103][debug][router] [source/common/router/router.cc:320] [C852][S12000535122821985147] cluster 'cluster_blah_launcher_gateway' match for URL '/blah_launcher.gateway.GatewayService/PublishEvent'
[2019-04-17 14:00:55.732][103][debug][router] [source/common/router/router.cc:381] [C852][S12000535122821985147] router decoding headers:
':method', 'POST'
':scheme', 'http'
':path', '/blah_launcher.gateway.GatewayService/PublishEvent'
':authority', 'ambassador-dev.blahtech.net:443'
'content-type', 'application/grpc'
'user-agent', 'grpc-go/1.14.0'
'te', 'trailers'
'x-forwarded-for', '100.118.80.128'
'x-forwarded-proto', 'https'
'x-envoy-external-address', '100.118.80.128'
'x-request-id', 'b16e53c6-6f76-4c05-8acd-387f2953132d'
'x-envoy-expected-rq-timeout-ms', '864000'
'x-envoy-original-path', '/blah_launcher.gateway.GatewayService/PublishEvent'
```
With load_balancer
```
[2019-04-17 13:57:49.256][107][debug][router] [source/common/router/router.cc:277] [C689882][S7881278366664999827] no cluster match for URL '/blah_launcher.gateway.GatewayService/PublishEvent'
[2019-04-17 13:57:49.256][107][debug][http] [source/common/http/conn_manager_impl.cc:1278] [C689882][S7881278366664999827] encoding headers via codec (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '12'
'date', 'Wed, 17 Apr 2019 13:57:49 GMT'
'server', 'envoy'
```

**Comment by peturgq** [comment]
The cluster disappears from envoy config when applying the LB config, this is my manifest:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: elg_mapping
      grpc: true
      prefix: /blah_launcher.gateway.GatewayService/
      rewrite: /blah_launcher.gateway.GatewayService/
      service: blah-launcher-gateway
      timeout_ms: 864000
      connect_timeout_ms: 864000
      load_balancer:
        policy: round_robin
```
