### ISSUE TITLE
Unquoted wildcard in hosts causes broken mapping

### ISSUE THREAD

**Issue by Guyzeroth** [datawire/ambassador#1438]
Using ambassador 0.53.1 

Given a mapping : 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: test_mapping
      host: hello.dev.test.com
      prefix: "/"
      service: test
      rewrite: ""
      ambassador_id: ambassador-external
      tls: test_tls
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      ambassador_id: ambassador-external
      name: test_tls
      hosts:
        - *.hello.dev.test.com
      secret: hello-test-certs
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
    - name: public-http-api
      port: 80
      targetPort: 80
```

The wildcard path under hosts causes the entire mapping to disappear from ambassador
adding Quotes "" around the *.hello.dev.test.com seems to fix the issue.

It breaks very silently and there is no indication of the error.  If this isn't a bug Perhaps this needs more clearly documenting?
