### ISSUE TITLE
Header RegexMatch validation fails in 0.53.1

### ISSUE THREAD

**Issue by battlecow** [datawire/ambassador#1439]
**Describe the bug**
Using the Mapping config with regex_headers: x-forwarded-for: to whitelist public ip addresses with a rather long regex works in 0.40.2 but errors out when trying to start 0.53.1 with a validation error.

**To Reproduce**
Using the following mapping in 0.40.2 works, while the same mapping in 0.53.1 will not allow Ambassador to start.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: test_mapping
      service: test.default.svc.cluster.local:3000
      host: test.thing
      prefix: /
      regex_headers:
        x-forwarded-for: '((104)*\.(192)*\.(142)*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((104)*\.(192)*\.((?:13[6-9]|14[0-3]))*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((131)*\.(103)*\.((?:26|27))*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((131)*\.(103)*\.(26)*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((131)*\.(103)*\.(27)*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((131)*\.(103)*\.(29)*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((165)*\.(254)*\.((?:226|227))*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((165)*\.(254)*\.(226)*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((165)*\.(254)*\.(227)*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((131)*\.(103)*\.(28)*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((185)*\.(166)*\.(14[0-3])*\.((?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))*)|((34)*\.(198)*\.(32)*\.(85)*)|((34)*\.(198)*\.(178)*\.(64)*)|((34)*\.(198)*\.(203)*\.(127)*)|((34)*\.(248)*\.(49)*\.(6)*)|((34)*\.(251)*\.(193)*\.(155)*)|((34)*\.(252)*\.(100)*\.(227)*)|((35)*\.(161)*\.(3)*\.(151)*)|((35)*\.(162)*\.(23)*\.(98)*)|((35)*\.(162)*\.(54)*\.(42)*)|((52)*\.(8)*\.(84)*\.(222)*)|((52)*\.(51)*\.(80)*\.(244)*)|((52)*\.(52)*\.(234)*\.(127)*)|((54)*\.(72)*\.(233)*\.(229)*)|((54)*\.(76)*\.(3)*\.(75)*)|((18)*\.(246)*\.(31)*\.((?:12[89]|1[3-9][0-9]|2[0-4][0-9]|25[0-5]))*)|((2600):(1f14):(824):((3){1}([0-f]{1,2})([0-f]{1,1})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2401):(1d80):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2406):(da18):(809):((e){1}([0-f]{1,2})([0-f]{1,1})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2406):(da1c):(1e0):((a){1}(2){1}([0-f]{1,2})([0-f]{1,1})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2600):(1f18):(2146):((e){1}(3){1}([0-f]{1,2})([0-f]{1,1})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2600):(1f1c):(cc5):((2){1}(3){1}([0-f]{1,2})([0-f]{1,1})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2a05):(d014):(f99):((d){1}(d){1}([0-f]{1,2})([0-f]{1,1})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2a05):(d018):(34d):((5){1}(8){1}([0-f]{1,2})([0-f]{1,1})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)|((2a0a):(ea00):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4})):(([0-f]{1,4}))*)'
  name: test
  namespace: default
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP
```

**Expected behavior**
Same as 0.40.2

**Versions (please complete the following information):**
 - Ambassador: [0.40.2, 0.53.1]
 - Kubernetes environment: 1.13.3

**Additional context**
The goal of the regex is to allow whitelisting of classless ip ranges, if this were implemented as a feature it would be a non issue.
