### ISSUE TITLE
TracingService is not applied without restart

### ISSUE THREAD

**Issue by aberres** [datawire/ambassador#1477]
**Describe the bug**

When adding a TracingService to the K8S annotations it has no effect until the Ambassador pods are restarted.

**To Reproduce**
1. Setup Ambassador and a matching service without any tracing service.
2. Add an config like
```
      apiVersion: ambassador/v1
      kind: TracingService
      name: tracing
      service: zipkin.traefik:9411
      driver: zipkin
      config:
        trace_id_128bit: true
```
to the existing annotation.
3. Hit any service endpoint.

**Expected behavior**
Tracing information is immediately sent to the tracing service.

**Actual behavior**
The tracing service is only used once the pods are recreated, e.g., by deleting and recreating the deployment.

What is weird is that Envoy seems to know about the tracing service. From the logs:
```[source/common/upstream/cluster_manager_impl.cc:496] warming cluster cluster_tracing_zipkin_9411 complete```

**Versions:**
 - Ambassador: [0.60.2]
 - Kubernetes environment [Google Kubernetes Engine]
 - Version [1.12]

**Additional context**
I am using https://github.com/openzipkin/docker-zipkin-gcp as tracing service.
