### ISSUE TITLE
TLS configuration error can crash Ambassador

### ISSUE THREAD

**Issue by sai3010** [datawire/ambassador#1495]
**Describe the bug**
I have added the full chain and private key in Kube secrets as ambassador-certs. 
My service is configured as follows :

```
getambassador.io/config: |
     ---
     apiVersion: ambassador/v1
     kind:  Mapping
     name:  mapping
     grpc: True
     headers:
       lang: french
     add_request_headers:
       userid: voice
     prefix: /Listener/
     rewrite: /Listener/
     service: service:9080
     timeout_ms: 60000
     tls: ambassador-certs
     # ---
     apiVersion: ambassador/v1
     kind: Module
     name: tls
     config:
     server:
     enabled: True
     secret: ambassador-certs
     ---
```

When I restart ambassador I encounterd this issue :
`File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irresource.py", line 63, in __init__
   self.set_active(self.setup(ir, aconf))
 File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irambassador.py", line 145, in setup
   cert=legacy_ctx, termination=False, validation_ca=None)
value = cert.get(key, None)
AttributeError: 'str' object has no attribute 'get'
`

**Expected behavior**
Ambassador has to read the certificate from kube secret and serve the request

**Versions (please complete the following information):**
 - Ambassador: 0.52
 - Kubernetes environment : gcp cluster
 - Version : gcp master : 1.11.8-gke.6

**Comment by kflynn** [comment]
The first thing here is that your configuration looks incorrect. I think you want:

```
getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  mapping
      grpc: True
      headers:
        lang: french
      add_request_headers:
        userid: voice
      prefix: /Listener/
      rewrite: /Listener/
      service: service:9080
      timeout_ms: 60000
      tls: server
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          secret: ambassador-certs
```

and that may prevent the crash. But. The crash is a separate issue that shouldn't happen.
