### ISSUE TITLE
KubernetesEndpointResolver works with the name "endpoint" only

### ISSUE THREAD

**Issue by ankurpshah** [datawire/ambassador#1497]
**Describe the bug**
`KubernetesEndpointResolver` works with the name `endpoint` only. An override doesn't work.

**To Reproduce**
Following configuration doesn't work:
```
      ---
      apiVersion: ambassador/v1
      kind: KubernetesEndpointResolver
      name: my_endpoint
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      ambassador_id: ambassador-80
      config:
        service_port: 8080
        resolver: my_endpoint
```
But this works:
```
      ---
      apiVersion: ambassador/v1
      kind: KubernetesEndpointResolver
      name: endpoint
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      ambassador_id: ambassador-80
      config:
        service_port: 8080
        resolver: endpoint
```

**Expected behavior**
`KubernetesEndpointResolver` should work with name override.

**Versions (please complete the following information):**
 - Ambassador: 0.60.3
 - Kubernetes environment: AWS KOPS 
 - Version 1.14.1
