### ISSUE TITLE
Issue terminating tls on ambassador 0.53.* on GKE

### ISSUE THREAD

**Issue by boogie4eva** [datawire/ambassador#1499]
**Describe the bug**
I can't access my micro services via https despite my tls module being activated for ambassador .
My ambassador certs have been generated with ready as true and status as valid. I used http challenge . I have about 3 services that i would want ambassador to terminate tls for .
**To Reproduce**
This is my service file 
```
apiVersion: v1
kind: Service
metadata:
  name: user-services-stage
  labels:
    app: user-services-stage
spec:
  ports:
  - name: http
     port: 8080
     protocol: TCP
  selector:
    app: user-services-stage
  type: ClusterIP
```
This is my ambassador service config .
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  user-services-stage-mapping
      prefix: /v1/api/user/
      service: user-services-stage:8080
      rewrite: /v1/api/user/
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  loaderio-test-mapping
      prefix: /loaderio-f0058b1a220adac1232bcd17dfaede3e.txt
      service: user-services-stage:8080
      rewrite: /loaderio-f0058b1a220adac1232bcd17dfaede3e.txt
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  website-mapping
      prefix: /
      service: http://website-stage:8080
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
          secret: ambassador-certs

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ambassador-http
      port: 80
      targetPort: 80
    - name: ambassador-https
      port: 443
      targetPort: 443
  selector:
    service: ambassador
```
**Expected behavior**
When i test the route at /loaderio-f0058b1a220adac1232bcd17dfaede3e.txt over https i'm expecting to see the desired response . This is a simple golang service that should ordinarily print a text back . This works over plain http but does not work after i added the tls module .
I've read the ambassador docs back and forth but yet i can't get to the root of the problem . Any ideas and solutions will be appreciated .

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.53.1]
 - Kubernetes environment [e.g.Google Kubernetes Engine]
 - Version [e.g. 1.12.6]

**Additional context**
My domain is one domain but with one as x.labs.com and the other as x.x.labs.com .
