### ISSUE TITLE
Users would like simpler authentication configuration

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#152]

**Comment by kflynn** [comment]
Here's a case that Datawire just ran into:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  ambassador:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: authentication
      config:
        auth_service: "authservice"
        allowed_headers: []
spec:
    ...
```

which prompts the question, if the annotation is attached to the service to use for authentication, why do we need to specify a service in the `auth_service` attribute too? It's just duplicate info.

The simplest thing here is probably to make `auth_service` optional. If not present and we're reading an annotation, use the annotated service as the `auth_service`.

Alternately, we could have a `use_as_auth` attribute to apply to a `Mapping`, but I'm much less sure that I like that idea.
