### ISSUE TITLE
Cannot Configure CORS on Module

### ISSUE THREAD

**Issue by x-fauzan-x** [datawire/ambassador#1549]
**Describe the bug**
I configured CORS on Module with this configuration :
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      config:
        server:
          enabled: True
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        origins: "*"
        methods: POST, GET, OPTIONS
        headers: Content-Type, XXX, YYY
```

But it didn't work and got result :

> Failed to load resource: net::ERR_CONNECTION_REFUSED
> Failed to load resource: the server responded with a status of 403 (Forbidden)
> Access to XMLHttpRequest at 'https://' from origin 'https://' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

But it worked if I configured CORS on the mapping with this configuration : 
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  xxx
      prefix: xxx
      service:xxx:8080
      cors:
        origins: "*"
        methods: POST, GET, OPTIONS
        headers: 
            - Content-Type
            - XXX
            - YYY
```

**Versions (please complete the following information):**
 - Ambassador: [0.53.1]
 - Kubernetes environment [1.11.5]
