### ISSUE TITLE
crash while adding request_header in global configuration 

### ISSUE THREAD

**Issue by Abhishek627** [datawire/ambassador#1582]
**Describe the bug**
Adding `request_headers: HEADER` to ambassador  module level mapping crashes the ambassador pod. With below error : 

Traceback (most recent call last):
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py”, line 590, in run
   self.load_config_watt(rqueue, url)
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py”, line 708, in load_config_watt
   self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py”, line 722, in _load_ir
   econf = EnvoyConfig.generate(ir, “V2")
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/common.py”, line 83, in generate
   return V2Config(ir)
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2config.py”, line 54, in __init__
   V2Route.generate(self)
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2route.py”, line 188, in generate
   route = config.save_element(‘route’, irgroup, V2Route(config, irgroup))
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2route.py”, line 168, in __init__
   action = V2RateLimitAction(config, rl)
 File “/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/envoy/v2/v2ratelimitaction.py”, line 75, in __init__
   hdr_name = hdr_action[‘header’]
TypeError: string indices must be integers

**To Reproduce**
Add this to ambassador module like this [link](https://www.getambassador.io/reference/rate-limits/#request-labels)

```
config:
  default_label_domain: ambassador
  default_labels:
    ambassador:
      defaults:
      - request_headers: HEADER
```
**Expected behavior**
Request headers should have been extracted and ambassador should have correctly processed this setting.

**Versions (please complete the following information):**
 - Ambassador: 0.60.3 and 0.61.1
 - Kubernetes environment: bareMetal and aws
 - Version: v1.13.5

**Additional context**

**Comment by richarddli** [comment]
Please paste your full YAML, not a snippet.

**Comment by richarddli** [comment]
(Also the link you listed shows the annotation on a `Service`, not the Ambassador module.)

**Comment by Abhishek627** [comment]
This is my ambassador_svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        service_port: 8080
        default_label_domain: ambassador
        default_labels:
          ambassador:
            defaults:
              -  request_headers: HEADER
```

I

I was referring to special labels given on this link. Those are supported on global level. Right ?
