### ISSUE TITLE
Automatically support linkerd l5d headers

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#1594]
Currently, users integrating Ambassador with Linkerd need to manually inject the l5d header, e.g., https://linkerd.io/2/tasks/using-ingress/#ambassador.

This approach also has limitations when using custom AuthService, e.g., see #1578 and #921.

The proper solution seems to be to automatically add the `l5d-dst-override` header to all requests (when configured).

**Comment by grampelberg** [comment]
This is great! Because Linkerd uses the `Host` (or `:authority`) headers for service discovery, `l5d-dst-override` needs to be there so that Linkerd can understand where the traffic is destined. Getting the headers in automatically will be a huge benefit for Linkerd users and get rid of the possible edge cases.

**Comment by kflynn** [comment]
@grampelberg Hey, could you by any chance give Ambassador 0.73.0-rc0 a shot in a Linkerd environment? 🙂 It has some stuff for this:

- use image `quay.io/datawire/ambassador:0.73.0-rc0`
- include `add_linkerd_headers: true` in your `ambassador` `Module`
- let us know what happens! :smile:

**Comment by kflynn** [comment]
@grampelberg Awesome! great to hear that. :smile:

The way you're doing it looks good to me. You can override the `add_linkerd_headers` setting from the `ambassador` `Module` in a `Mapping`, too -- so if you only have one `Mapping` you could do this:

```yaml
---
apiVersion: ambassador/v1
kind: Mapping
name: web-ambassador-mapping
service: http://linkerd-web.linkerd.svc.cluster.local:8084
host: example.com
prefix: /
add_linkerd_headers: true
```

In general I'd expect the `ambassador` `Module` to be the more useful way to go.

I'd wait for 0.73 to actually ship before updating the docs -- it'll be soon. :smile:
