### ISSUE TITLE
SNI/TLS Termination/proxy-protocol Issue

### ISSUE THREAD

**Issue by jamessthompson** [datawire/ambassador#1606]
**Describe the bug**
When Ambassador is setting behind an tcp based ELB and is configured to handle the TLS termination turning on proxy protocol causes all pages to 404.  I can see the route defined in the admin UI and I can see the requests hit ambassador with the appropriate domain name along with the clients actual IP in the logs.  They just always 404

**To Reproduce**
1.  Start with a working configuration....

Create an ambassador instance from helm chart using this values file
```
env:
  AMBASSADOR_ID: primary

crds:
  create: true
  keep: false

autoscaling:
  enabled: true
  minReplica: 2
  maxReplica: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9102"

prometheusExporter:
  enabled: true

service:
  annotations:
    # Period on next line is intentional
    external-dns.alpha.kubernetes.io/hostname: gw-primary.sandbox.core.harrys.systems.
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      ambassador_id: primary
      config:
        use_remote_address: true
        use_proxy_proto: false
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: primary
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8080
          secret: cert-wildcard-cluster
```
Create a TLSContext 
```
kind: TLSContext
metadata:
  generation: 1
  name: jthompson-kuard-harrys-webservice
  selfLink: /apis/getambassador.io/v1/namespaces/training-jthompson/tlscontexts/jthompson-kuard-harrys-webservice
spec:
  ambassador_id: primary
  hosts:
  - kuard.sandbox.core.harrys.systems
  secret: cert-wildcard-cluster
```
Create Mapping
```
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  generation: 1
  name: jthompson-kuard-harrys-webservice
  selfLink: /apis/getambassador.io/v1/namespaces/training-jthompson/mappings/jthompson-kuard-harrys-webservice
spec:
  ambassador_id: primary
  host: kuard.sandbox.core.harrys.systems
  host_regex: false
  prefix: /
  rewrite: /
  service: jthompson-kuard-harrys-webservice.training-jthompson:8080
  shadow: false
  use_websocket: false
```

2. Validate site works via browser or curl
3. change the service to turn on proxy protocol in ELB and Ambassador via
   - Adding annotation service.beta.kubernetes.io/aws-load-balancer-proxy-protocol
   - Setting use_proxy_proto to true
```
service:
  annotations:
    # Period on next line is intentional
    external-dns.alpha.kubernetes.io/hostname: gw-primary.sandbox.core.harrys.systems.
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      ambassador_id: primary
      config:
        use_remote_address: true
        use_proxy_proto: true
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: primary
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8080
          secret: cert-wildcard-cluster
```
4. Revisit site to receive 404

**Expected behavior**
The site would not 404 with proxy-protocol active. 

**Versions (please complete the following information):**
 - Ambassador: 0.70.1
 - Kubernetes environment: AWS EKS
 - Version 1.12

**Additional context**

When proxy-protocol is active it appears that ambassador is at least getting valid requests with external IP addresses as they are showing up in the logs

```
[ambassador-primary-855f48bc9b-2g8k6 ambassador] ACCESS [2019-06-05T12:45:08.813Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "38.88.255.90" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "b368eb01-9938-4a0c-a9fd-7623a26e42f1" "kuard.sandbox.core.harrys.systems" "-"
[ambassador-primary-855f48bc9b-2g8k6 ambassador] ACCESS [2019-06-05T12:45:09.769Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "38.88.255.90" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "980fecb0-5293-4766-b048-e6c79b49cdbf" "kuard.sandbox.core.harrys.systems" "-"
[ambassador-primary-855f48bc9b-2g8k6 ambassador] ACCESS [2019-06-05T12:45:10.392Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "38.88.255.90" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" "c91a223b-5609-4a21-88ed-42ac550aae2a" "kuard.sandbox.core.harrys.systems" "-"
```

A possibly related issue was raised on slack as well...
https://datawire-oss.slack.com/archives/CAULN7S76/p1559795166112900

I'm using a wildcard cert so the cert is always the same for me.

**Notes**
In my example,  kuard.sandbox.core.harrys.systems is a CNAME aliased to the gateway's DNS record.  

I removed a loadBalancerSourceRanges setting on the service above that is present in my configuration.
