### ISSUE TITLE
Port conflict when using Module CRD and sidecar

### ISSUE THREAD

**Issue by patricksanders** [datawire/ambassador#1636]
**Describe the bug**
When running a sidecar on port 8080 and configuring Ambassador's `service_port` with the Module CRD, Envoy fails to start with the following error message:

```
[2019-06-17 20:41:59.106][193][warning][config] [bazel-out/k8-dbg/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) ambassador-listener-8080: cannot bind '0.0.0.0:8080': Address already in use
```

**To Reproduce**
1. Create a `Module` CRD with `service_port: 80`
2. Create Ambassador deployment with a sidecar running on port 8080

**Expected behavior**
Ambassador should start Envoy on port 80.

**Versions (please complete the following information):**
 - Ambassador: 0.71.0 and 0.72.0
 - Kubernetes environment: Custom EC2
 - Version: 1.10.11

**Additional context**
- This does not occur when configuring Ambassador with a Module annotation.
- This only happens on a fresh deployment. If Ambassador is initialized with an annotation then switched over to the CRD, the failure does not occur.

**Comment by kflynn** [comment]
I think we need to actually see the YAML you're using here -- this sounds kind of strange.

**Comment by patricksanders** [comment]
Sure thing! It does sound strange.

Here's the module:

```yaml
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: ambassador-patrick
spec:
  ambassador_id: patrick
  config:
    use_remote_address: false
    service_port: 80
```

And here's the corresponding annotation:

```yaml
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      ambassador_id: patrick
      kind: Module
      name: ambassador
      config:
        use_remote_address: false
        service_port: 8
```

This is a stripped down version of the deployment to show the sidecar running on port 8080:

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador-patrick
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        service: ambassador-patrick
    spec:
      serviceAccountName: ambassador
      containers:
      - name: ambassador
        image: [registry]/ambassador:0.71.0
        imagePullPolicy: Always
        env:
        - name: AMBASSADOR_ID
          value: patrick
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8877
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      - name: customauth
        image: [registry]/[externalauth_image]
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
```

If I start Ambassador with the both the annotation and the custom resource, it comes up fine. I can also delete the annotation and things stay healthy.

Are CRDs evaluated at a different time than annotations?
