### ISSUE TITLE
websocket connection doesn't work with prefix

### ISSUE THREAD

**Issue by sylhero** [datawire/ambassador#1642]
**Describe the bug**
when use websocket with prefix the connection can't establish

**To Reproduce**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-socket
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-socket
    spec:
      containers:
      - name: test-socket-container
        image: sylhero/test-socket
        env:
        - name: NODE_ENV
          value: "development"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
```
```
---
apiVersion: v1
kind: Service
metadata:
  name: test-socket
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  test_socket_mapping
      prefix: /test/
      service: test-socket
      timeout_ms: 20000
      use_websocket: true
spec:
  selector:
    app: test-socket
  ports:
  - name: first
    port: 443
    targetPort: 8000
  - name: second
    port: 80
    targetPort: 8000
```
sample client script for testing
```
const
    io = require("socket.io-client"),
    ioClient = io.connect("https://dev.test.io/test"); //http://localhost:8000

ioClient.on("seq-num", (msg) => console.info(msg));
```
everything works fine with prefix `/` but as long as you have other prefix it stops working. I used the current version of socketio from npm

error logs
```
ACCESS [2019-06-21T14:48:02.345Z] "POST /socket.io/?EIO=3&transport=polling&t=MjwWZNq&b64=1 HTTP/1.1" 405 - 3 158 3 0 "10.100.0.1" "node-XMLHttpRequest" "a2dc9059-3a52-49d3-b477-8a2fb0038cc1" "dev.io" "10.254.18.113:80"
```
traffic never routes to the pod

**Expected behavior**
A clear instruction for setting up ws with prefix or this is just a wrong example
https://www.getambassador.io/user-guide/websockets-ambassador/

**Versions (please complete the following information):**
 - Ambassador: [0.6]
 - Kubernetes environment [1.11]
