### ISSUE TITLE
Ambassador should warn about configuration that cannot be parsed

### ISSUE THREAD

**Issue by Aracki** [datawire/ambassador#1660]
I'm not sure if this is a bug or a feature request as I cannot find a reference in official documentation.

I am deploying Ambassador with Helm and I was passing: 

```
ambassadorConfig: |
  apiVersion: ambassador/v1
  kind: Module
  name: ambassador
    config:
      diagnostics:
        enabled: false
```

instead of:

```
ambassadorConfig: |
  apiVersion: ambassador/v1
  kind: Module
  name: ambassador
  config:
    diagnostics:
      enabled: false
```

...

Because of `config` block was not parsed properly, Ambassador was using default config. 

Would it be better practice not to start Ambassador process at all in cases when you actually pass the configuration but the .yaml is not parsed correctly?
