### ISSUE TITLE
Canary Deployment Not Working 

### ISSUE THREAD

**Issue by BailyTroyer** [datawire/ambassador#1707]
I am trying a simple POC with Ambassador and the two following resources have now worked: 

1. I tried following this [example](https://blog.getambassador.io/canary-deployments-a-b-testing-and-microservices-with-ambassador-f104d0458736) and the load balancer does not resolve: 

`curl: (52) Empty reply from server`

2. I also followed the documentation [here](https://www.getambassador.io/docs/dev-guide/canary-release-concepts/) and I get: 

`curl: (52) Empty reply from server`?

Here's my deployment: 

```
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ambassador
  labels:
    app: payment-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: payment-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: ambassador
  labels:
    app: payment-app
    track: stable
spec:
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
        labels:
          app: payment-app
    spec:
      containers:
      - name: payment-app
        image: ...
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-canary
  namespace: ambassador
  labels:
    app: payment-app
    track: canary
spec:
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
        labels:
          app: payment-app
    spec:
      containers:
      - name: payment-app
        image: ...
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

Here's the ambassador service:

```
apiVersion: v1
kind: Service
metadata:
 labels:
   service: ambassador
 name: ambassador
 annotations:
   getambassador.io/config: |
     ---
     apiVersion: ambassador/v1
     kind:  Mapping
     name:  payment
     prefix: /hello
     ---
     apiVersion: ambassador/v1
     kind:  Mapping
     name:  payment-canary
     prefix: /hello
     service: payment-canary:8080
     Weight: 50
spec:
 type: LoadBalancer
 ports:
 - name: ambassador
   port: 80
   targetPort: 8080
 selector:
   service: ambassador
```

Is there something that I could be missing or doing wrong?

**Comment by gbpnkans** [comment]
```
apiVersion: v1
kind: Service
metadata:
 labels:
   service: ambassador
 name: ambassador
 annotations:
   getambassador.io/config: |
     ---
     apiVersion: ambassador/v1
     kind:  Mapping
     name:  payment
     service: payment:8080
     prefix: /hello
     ---
     apiVersion: ambassador/v1
     kind:  Mapping
     name:  payment-canary
     prefix: /hello
     service: payment-canary:8080
     Weight: 50
spec:
 type: LoadBalancer
 ports:
 - name: ambassador
   port: 80
   targetPort: 8080
 selector:
   service: ambassador
```
Looks like you missed the service on the primary configuration.
