### ISSUE TITLE
Multiple rapid updates with KubernetesEndpointResolver can make Ambassador get stuck

### ISSUE THREAD

**Issue by juanjoku** [datawire/ambassador#1715]
**Describe the bug**
If Mapping objects use KubernetesEndPointResolver, then Ambassador gets an inconsistent state... and must be restarted.

**To Reproduce**

1) 
I create and register this KubernetesEndPointResolver object:

```    
apiVersion: getambassador.io/v1
kind: KubernetesEndpointResolver
metadata:
  name: myendpoint
  namespace: mynamespace
```    

2)
I create this Mapping object:

```
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name: mymapping
  namespace: mynamespace
spec:
  host: mydomain.blablebli.com
  prefix: /
  service: http://myservice.mynamespace:5000
  resolver: myendpoint
  load_balancer:
    policy: round_robin
```   

3)
I add/remove the mapping object several times:

```
#!/bin/bash
kubectl apply -f mymapping.yaml;
kubectl delete -f mymapping.yaml;
kubectl apply -f mymapping.yaml;
kubectl delete -f mymapping.yaml;
kubectl apply -f mymapping.yaml;
kubectl delete -f mymapping.yaml;
```

4)
Then, Ambassador stops working, doesn't process any new object.
**Ambassador must be restarted.**

5)
The problem also occurs when I add a short pause between add/delete operations:

```
#!/bin/bash
kubectl apply -f mymapping.yaml;
sleep 0.5;
kubectl delete -f mymapping.yaml;
sleep 0.5;
kubectl apply -f mymapping.yaml;
sleep 0.5;
kubectl delete -f mymapping.yaml;
sleep 0.5;
kubectl apply -f mymapping.yaml;
sleep 0.5;
kubectl delete -f mymapping.yaml;
```

6)
The problem DOESN'T occur when KubernetesEndPointResolver is not used.

```
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name: mymapping
  namespace: mynamespace
spec:
  host: mydomain.blablebli.com
  prefix: /
  service: http://myservice.mynamespace:5000
```
