### ISSUE TITLE
Kubernetes Endpoint Resolver Not Working

### ISSUE THREAD

**Issue by cyrus-mc** [datawire/ambassador#1755]
**Describe the bug**

I am attempting to configure resolvers as described here

https://www.getambassador.io/reference/core/resolvers/

Specifically I would like to use the Endpoints resolver such that envoy lists the POD IP instead of the service VIP.

**To Reproduce**

First I created the following:

```yaml
apiVersion: getambassador.io/v1
kind: KubernetesEndpointResolver
metadata:
  name: endpoint
```

I then created my service mapping:

```yaml
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: service_test_mapping
      service: service.test:80
      cors:
        headers: Content-Type, Authorization
        origins: '*'
      prefix: /service/
      resolver: endpoint
      rewrite: /
      timeout_ms: 10000
```

The generated envoy config for the marketmaps clusters is

```json
            {
                "connect_timeout": "3.000s",
                "dns_lookup_family": "V4_ONLY",
                "lb_policy": "ROUND_ROBIN",
                "load_assignment": {
                    "cluster_name": "cluster_service_test_80",
                    "endpoints": [
                        {
                            "lb_endpoints": [
                                {
                                    "endpoint": {
                                        "address": {
                                            "socket_address": {
                                                "address": "service.test",
                                                "port_value": 80,
                                                "protocol": "TCP"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                "name": "cluster_service_test_80",
                "type": "STRICT_DNS"
```

As you can see the endpoint is simply the MarketMaps service, meaning it still routes through K8s.

**Expected behavior**

I would expect that the endpoints listed in the envoy cluster definition list the endpoints behind the k8s service.

**Versions (please complete the following information):**
 - Ambassador: 0.74.1
 - Kubernetes environment: EKS
 - Version: 1.13
