### ISSUE TITLE
External Mapping Service

### ISSUE THREAD

**Issue by victortv7** [datawire/ambassador#1762]
This is definetely not a crucial feature. Just an idea I had. It would help if the community could expand this idea as well as providing other use cases.

**Please describe your use case / problem.**
I want to do A/B testing based on certain business rules, such as directing traffic to the new version of my service initially only for requests coming from a set of users.

**Describe the solution you'd like**
Similarly to authentication, the solution would consist of declaring an "external mapper". When a mapping condition is met, the request will be redirected to the external mapper. After treating the request, the mapper would send back to the ambassador information related to which service should be used. This information could be a new prefix(or header, host , etc.) or the external mapper could be attached to a mapping and would decide if the mapping would take place or not

Solution 1: Mapping returns a new prefix, which would be used in other mappings:

```yaml   
---
apiVersion: ambassador/v1
kind:  MappingService
name:  map_by_user_region
auth_service: "external-mapper:8080"
path_prefix: "/myservice"
---
apiVersion: ambassador/v1
kind:  Mapping
name:  old_service_mapping
prefix: /old_service/
service: "appv1:8080"
---
apiVersion: ambassador/v1
kind: Mapping
name: new_service_mapping
prefix: /new_service/
service: "appv2:8080"
```

Solution 2: The external mapper would decide if the mapping should take place in the attached mapping (returns 200 OK) or not (different than 200 OK).

```yaml
---
apiVersion: ambassador/v1
kind:  Mapping
name:  old_service_mapping
prefix: /same_prefix/
service: "appv1:8080"
---
apiVersion: ambassador/v1
kind: Mapping
name: new_service_mapping
prefix: /same_prefix/
service: "appv2:8080"
mapping_service: "external-mapper:8080"
```

You could also use weight if the external mapper returns OK in two or more mappings:

```yaml
---
apiVersion: ambassador/v1
kind:  Mapping
name:  old_service_mapping
prefix: /same_prefix/
service: "appv1:8080"
mapping_service: "external-mapper:8080"
---
apiVersion: ambassador/v1
kind: Mapping
name: new_service_mapping
prefix: /same_prefix/
service: "appv2:8080"
mapping_service: "external-mapper:8080"
weight: 10
```

**Describe alternatives you've considered**
I could just make my own business gateway that would forward the requests to the appropriate service.

P.S.: Is it possible to do a mapping based on headers sent by the external auth service? This could also be an alternative, although maybe not pretty considering microservices best practices.
