### ISSUE TITLE
sni unable to support the wildcard certificate

### ISSUE THREAD

**Issue by tttlkkkl** [datawire/ambassador#1769]
**Describe the bug**
I configure SNI according to the documentation, but it doesn't work and debug output like: 
```html
CONFIGURATION ERRORS
li.default.2: TLSContext nginx found no certificate in secret lihuaio in namespace com, ignoring...
```
my certificate is a wildcard of *.lihuaio.com ,it can working in traefik or nginx。Is ambassador not supporting wildcard certificates or am I wrong？please answer for me. thank you.

**To Reproduce**
1. helm install --name ambassador stable/ambassador
2. Issuing a wildcard certificate using Let’s Encrypt。
3. config sni like:
```yaml
kind: Service
apiVersion: v1
metadata:
  name:  li
  annotations: 
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v1
      kind: Mapping
      name: nginx_mapping
      prefix: /
      service: li:80
      host: he.lihuaio.com
      ---
      apiVersion: getambassador.io/v1
      kind: TLSContext
      name: nginx
      hosts:
      - he.lihuaio.com
      secret: lihuaio.com
spec:
  selector:
    app:  nginx-hello-word
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  80
```

**Expected behavior**
ambassador should automatically identify wildcard certificates and apply them to SNI

**Versions (please complete the following information):**
 - Ambassador: 0.75.0 
 - Kubernetes environment alibaba ACK 
 - Version 1.12.6-aliyun.1

**Additional context**
I don't think it should be a bug, but it really doesn't work
