### ISSUE TITLE
Creation of TracingService requires restart of Ambassador to take effect

### ISSUE THREAD

**Issue by ovk** [datawire/ambassador#1771]
**Describe the bug**

`TracingService` configuration is not applied until Ambassador is restarted.

**To Reproduce**

1. Deploy Ambassador with service of type NodePort.
2. Deploy Ambassador `TracingService`:

```
apiVersion: getambassador.io/v1
kind: TracingService
metadata:
  name: tracing
spec:
  service: jaeger:9411
  driver: zipkin
```

```
$ kubectl get tracingservices.getambassador.io

NAME      AGE
tracing   2m6s
```

Verify that tracing is now configured in the `/ambassador/bootstrap-ads.json` file:
```
"tracing": {
        "http": {
            "config": {
                "collector_cluster": "cluster_tracing_jaeger_9411",
                "collector_endpoint": "/api/v1/spans"
            },
            "name": "envoy.zipkin"
        }
    }
```

3. Add a Ambassador `Mapping` to a test service:

```
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: test
spec:
  prefix: /test/
  rewrite: /
  service: test:80
```
  
4. Hit Ambassador NodePort `/test/...` with traffic:

```
hey -c 5 -z 1m http://XXX.XXX.XXX.XXX:YYYY/test/some/api

...

Status code distribution:
  [200] 13690 responses
```

**No tracing information is sent from the Ambassador to Jaeger.
Watching `tcpdump` shows no packets from the Ambassador to Jaeger.**

5. Restart Ambassador pod:

```
kubectl delete pod ambassador-XXXXXXXXX-YYYY
```

Wait for the new pod to become up and running.

6. Repeat step 4

**Now (after restart) tracing information is properly delivered to Jaeger.**

**Expected behavior**

Either creating `TracingService` should take effect immediately, or the fact that Ambassador has to be restarted after changing tracing configuration needs to be documented.

**Versions:**

 - Ambassador: 0.75.0
 - Kubernetes environment: Minikube
 - Version: 1.14.6
