### ISSUE TITLE
Mapping CRD `.spec.service` field and kustomize transformers

### ISSUE THREAD

**Issue by imranismail** [datawire/ambassador#1821]
Kustomize has a feature called [transformers](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md) where it applies a series of transformations to an original set of resources. This is especially handy when a set of resources is to be deployed to different environments. This can work [with CRDs with additional config](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs/crd) that tells kustomize which fields are needed to be transformed.

However, Mapping's URL `.spec.service` field makes this impossible because Kustomize expects the reference to be equal.

## Proposal

I propose an alternative structure for defining `.spec.service` like so:

**kustomization.yaml**
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
namespace: app
configurations:
- mapping-config.yaml
resources:
- service.yaml
```

**mapping-config.yaml**
```yaml
---
nameReference:
- kind: Service
  fieldSpecs:
  - path: spec/service/name
    kind: Mapping
---
namespace:
- kind: Mapping
  path: spec/service/namespace
  create: true
```

**service.yaml**
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: http
    port: 80
  selector:
    app.kubernetes.io/name: app
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: app
spec:
  host: app.example
  prefix: /
  service:
    name: app
    scheme: http
    port: 3000
```

Running `kustomize build` for above produces the following mapping resource

```yaml
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: app-staging
  namespace: app
spec:
  host: app.example
  prefix: /
  service:
    name: app-staging
    namespace: app
    port: 3000
    scheme: http
```

## Alternative

Alternatively, we can keep the existing spec and use the `vars` transformer like so:

**kustomization.yaml**

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -staging
namespace: app
resources:
- service.yaml
configurations:
- mapping-config.yaml
vars:
- name: APP_SERVICE_NAMESPACE
  objref:
    kind: Service
    name: app
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: APP_SERVICE_NAME
  objref:
    kind: Service
    name: app
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
```

**mapping-config.yaml**

```yaml
---
varReference:
- path: spec/service
  kind: Mapping
```

**service.yaml**

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: http
    port: 80
  selector:
    app.kubernetes.io/name: app
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: app
spec:
  host: app.example
  prefix: /
  service: http://$(APP_SERVICE_NAME).$(APP_SERVICE_NAMESPACE)
```
