### ISSUE TITLE
Intermittent TLS termination errors after upgrading to Ambassador 0.78 

### ISSUE THREAD

**Issue by emilyzhang** [datawire/ambassador#1838]
**Describe the bug**
After upgrading to Ambassador v0.78 (via helm), TLS termination that previously worked 100% of the time now only works about 50% of the time.

**To Reproduce**
I upgraded from Ambassador v0.70 to v0.78 yesterday. I ran into some errors while upgrading due to CRDs (we deploy multiple ambassadors, one with an internal load balancer and one with a external load balancer) so I eventually ended up setting the following configuration for CRDs on my helm charts and applying the CRDs manually in a yaml file (copied from the Ambassador documentation):
```
# Don't delete crds when chart is deleted to prevent issues when installing new ambassadors
crds:
  create: false
  keep: true
  enabled: true
```
Besides that I haven't changed anything within my Mappings, TLSContext, or tls Module configuration. Here's an example of the configuration I'm using for a basic http-echo service: 
```
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name:  pineapple-mapping
spec:
  ambassador_id: [ambassador-public]
  prefix: /
  service: pineapple.default:5678
  host: pineapple.lob-sandbox.com
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  ambassador_id: [ambassador-public, ambassador-private]
  config:
    service_port: 8443
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: tls
  namespace: ambassador
spec:
  ambassador_id: [ambassador-public, ambassador-private]
  config:
    server:
      enabled: True
      redirect_cleartext_from: 8080
---
apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: lob-sandbox-wildcard-context
  namespace: ambassador
spec:
  ambassador_id: [ambassador-public, ambassador-private]
  hosts:
    - "*.lob-sandbox.com"
  secret: lob-sandbox-wildcard-cert
```
1. Curl "pineapple.lob-sandbox.com"
2. Half the time I get the following:
![image](https://user-images.githubusercontent.com/10638317/65164233-581aae00-d9f1-11e9-9800-992d6e4b5ecf.png)
The other half of the time I get the expected response:
![image](https://user-images.githubusercontent.com/10638317/65164160-38838580-d9f1-11e9-857d-c01427d55ac1.png)

**Expected behavior**
TLS termination always works.

**Versions (please complete the following information):**
 - Ambassador: 0.78
 - Kubernetes environment: kubedam on AWS EC2 instances
 - Version: Kubernetes v1.14

**Additional context**
Another thing that happens is that when TLS termination works, I'll often be able to get a bunch of working `curl`'s before it stops working again. I don't see anything out of the ordinary in the Ambassador pod logs or on the diagnostic dashboard, the pods seem to be running fine (and another service that uses a Mapping pod annotation instead of Mapping CRD to connect to my `ambassador-private` service is working fine 100% of the time even on Ambassador version 0.78), so I'm not sure if I have a configuration error somewhere that I missed (although `ambassador-private` and `ambassador-public` should have the same configuration except for some pod annotations). I'm mostly curious to see if anyone else has run into a similar issue.
