### ISSUE TITLE
Intermittent 503s right after upgrading Deployments

### ISSUE THREAD

**Issue by emilyzhang** [datawire/ambassador#1853]
**Describe the bug**
We're getting intermittent 503's for a couple of seconds right after a deployment has been upgraded (specifically, in the one or two seconds right after an old replica terminates), even when my pods have readinessProbes, pod disruption budgets, and RollingUpdate deployment strategies set. Even though the 503's only last a second or so, this isn't ideal because we want to have zero downtime upgrades of our deployments.

Here's a sample of the configuration we have on our services:
Ambassador-related config:
```
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name:  pineapple-mapping
spec:
  ambassador_id: [ambassador-public]
  prefix: /
  service: pineapple.default:5678
  host: pineapple.lob-sandbox.com
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  ambassador_id: [ambassador-public, ambassador-private]
  config:
    service_port: 8443
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: tls
  namespace: ambassador
spec:
  ambassador_id: [ambassador-public, ambassador-private]
  config:
    server:
      enabled: True
      redirect_cleartext_from: 8080
---
apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: lob-sandbox-wildcard-context
  namespace: ambassador
spec:
  ambassador_id: [ambassador-public, ambassador-private]
  hosts:
    - "*.lob-sandbox.com"
  secret: lob-sandbox-wildcard-cert
```
Service/Deployment config:
```
kind: Service
apiVersion: v1
metadata:
  name: pineapple
spec:
  selector:
    app: pineapple
  ports:
    # Default port for image
    - port: 5678
      targetPort: 5678
      name: default
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pineapple
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: pineapple
  template:
    metadata:
      name: pineapple
      labels:
        app: pineapple
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pineapple
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      containers:
        - name: pineapple
          image: hashicorp/http-echo
          args:
            - "-text=if you were a pineapple, you'd be a fineapple!!"
          livenessProbe:
            httpGet:
              path: /health
              port: web
              scheme: HTTP
          ports:
          - containerPort: 5678
            name: web
          readinessProbe:
            httpGet:
              path: /health
              port: web
              scheme: HTTP
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pineapple-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: pineapple
```

**To Reproduce**
1. Upgrade a deployment (my deployments have 2 replicas).
2. Ping the service continuously while the deployment is upgrading.
3. See 503's in logs and as a result of pings.

**Expected behavior**
Deployments can be upgraded without any downtime.

**Versions (please complete the following information):**
 - Ambassador: 0.78 (but this issue also occurred in 0.70 and 0.69)
 - Kubernetes environment: kubeadm on AWS EC2 instances
 - Version: Kubernetes v1.14

**Additional context**
Logs don't show anything out of the ordinary besides the occasional 503:
```
...
ACCESS [2019-09-21T00:39:31.529Z] "GET /8662 HTTP/1.1" 200 - 0 53 0 0 "192.168.3.0" "curl/7.54.0" "531316b3-f497-485c-9574-7ea67344e49b" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.530Z] "GET / HTTP/1.1" 200 - 0 53 0 0 "192.168.4.0" "Go-http-client/1.1" "7e153159-b20c-473e-91cf-06717c663ce3" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.561Z] "GET /8663 HTTP/1.1" 200 - 0 53 0 0 "192.168.3.0" "curl/7.54.0" "10229530-371e-4396-8c18-41fc6ef2f425" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.561Z] "GET / HTTP/1.1" 200 - 0 53 0 0 "192.168.4.0" "Go-http-client/1.1" "6f9e0985-bb9d-437a-9ac6-cea0efddd39c" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.596Z] "GET /8664 HTTP/1.1" 503 UC 0 95 14 - "192.168.3.0" "curl/7.54.0" "c18c8e31-3fba-4f46-a5ba-366935cda3ad" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.596Z] "GET / HTTP/1.1" 503 UC 0 95 14 - "192.168.4.0" "Go-http-client/1.1" "ab59e94d-1ca5-4a43-94e8-6e142c569866" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.639Z] "GET /8665 HTTP/1.1" 200 - 0 54 3 2 "192.168.3.0" "curl/7.54.0" "3aefa59d-807c-40fa-884c-23b1e45ba29b" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.645Z] "GET / HTTP/1.1" 200 - 0 54 0 0 "192.168.4.0" "Go-http-client/1.1" "1cb75bf1-2039-4f1f-8766-e247bbca07bb" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.674Z] "GET /8666 HTTP/1.1" 200 - 0 54 0 0 "192.168.3.0" "curl/7.54.0" "d054ed29-ace6-405b-ac07-420f8e45f3d4" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
ACCESS [2019-09-21T00:39:31.677Z] "GET / HTTP/1.1" 200 - 0 54 0 0 "192.168.4.0" "Go-http-client/1.1" "7f90de1f-2f40-459b-94dd-22f5fcdf86f7" "pineapple.lob-sandbox.com" "10.97.180.102:5678"
...
```

It's difficult to tell whether this is an issue with Ambassador (maybe routes being updated when pods are terminated?) or Envoy underneath, but I'm posting to see whether anyone else has run into a similar issue. This issue doesn't happen when the service is using an AWS ELB directly (Service type is set to LoadBalancer instead of using Ambassador for ingress).
