### ISSUE TITLE
Knative integration is broken at HEAD

### ISSUE THREAD

**Issue by mattmoor** [datawire/ambassador#1871]
**Describe the bug**
Following an adapted version of the knative + ambassador instructions to install at HEAD, I am seeing a consistent ambassador panic:
```
2019/09/30 18:13:33 kubernetes:ingresses.networking.internal.knative.dev|*|*|*: ERROR: WORKER PANICKED: ingresses.networking.internal.knative.dev is forbidden: User "system:serviceaccount:default:ambassador" cannot list resource "ingresses" in API group "networking.internal.knative.dev" at the cluster scope
```

**To Reproduce**
1. `kubectl apply -f https://storage.googleapis.com/knative-nightly/serving/latest/serving-crds.yaml`
1. `kubectl apply -f https://storage.googleapis.com/knative-nightly/serving/latest/serving-core.yaml`
1. `kubectl apply --filename https://getambassador.io/yaml/ambassador/ambassador-knative.yaml --filename https://getambassador.io/yaml/ambassador/ambassador-service.yaml`

Then create the service:
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: Go Sample v1
```

**Expected behavior**
Things work :)

**Versions (please complete the following information):**
 - Ambassador: See above (getambassador.io)
 - Kubernetes environment: GKE 1.14 cluster
