### ISSUE TITLE
KubernetesEndpointResolver falls back to service when no endpoints are ready

### ISSUE THREAD

**Issue by HoveringHalibut** [datawire/ambassador#1884]
**Describe the bug**
When using the KubernetesEndpointResolver and no endpoints are ready, Ambassador falls back to sending traffic to the service.  Requests sent to the service timeout and result in a 503 as there are no endpoints ready.
This is specifically problematic in an update scenario with 2 services with the same mapping host and path.  If the new service's pods are not yet in a ready state, the new service will receive traffic and timeout.

**To Reproduce**

1. Configure service/cluster to use Endpoint resolver
2. Deploy a service without any ready endpoints or endpoints that have a delay in becoming ready.
3. Check Ambassador configuration to see service configured for traffic instead of pod endpoints.

**Expected behavior**
No traffic should be sent to a service if no endpoints are ready.

**Versions (please complete the following information):**
 - Ambassador: 0.80
 - AKS 1.13.5

**Additional context**
This cluster is configured to use KubernetesEndpointResolver as default

```
---
apiVersion: getambassador.io/v1
kind: KubernetesEndpointResolver
metadata:
  name: endpoint
  namespace: default
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: ambassador
  namespace: default
spec:
  config:
    resolver: endpoint
    load_balancer:
      policy: round_robin
```

**Diagnostics Overview**

Configuration errors:
cluster_edm_releasetest_558fc152_2_ambassador_er_round_robin: no endpoints found, disabling cluster

Clusters:
```
{
    "connect_timeout": "3.000s",
    "dns_lookup_family": "V4_ONLY",
    "lb_policy": "ROUND_ROBIN",
    "load_assignment": {
        "cluster_name": "cluster_edm_releasetest_558fc152_2_ambassador_er_round_robin",
        "endpoints": [
            {
                "lb_endpoints": [
                    {
                        "endpoint": {
                            "address": {
                                "socket_address": {
                                    "address": "edm-releasetest-558fc152-2-ambassador",
                                    "port_value": 80,
                                    "protocol": "TCP"
                                }
                            }
                        }
                    }
                ]
            }
        ]
    },
    "name": "cluster_edm_releasetest_558fc152_2_ambassador_er_round_robin",
    "type": "STRICT_DNS"
}
```
