### ISSUE TITLE
The ExtAuthService didn't work in the K8S cluster

### ISSUE THREAD

**Issue by yxzhm** [datawire/ambassador#1887]
I try to enable the ExtAuthService in Ambassador, I find that this Ext_Auth didn't work in K8S, but it works in standalone docker container.

1. I run the Ambassador docker container in a VM and mount the auth.yaml into it. The content of auth.yaml is as following.

```
---
apiVersion: ambassador/v1
kind:  AuthService
name:  authentication
auth_service: "192.168.159.1:3000"
path_prefix: "/extauth"

allowed_authorization_headers:
- "X-Speech-VID"
```

2. After the docker container initialized, I can see the below log. It indicate that the extauth is enabled.

`ambassador_1  | 2019-10-03 09:52:47 diagd 0.60.3 [P40TAmbassadorEventWatcher] INFO: extauth: server_uri http://extauth`

3. I run the Ambassador in the K8S, and configure the same auth in annotation of Ambassador service.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: "test-auth:3000"
      path_prefix:  "/extauth"
      proto: http
      allowed_request_headers:
        - "X-Speech-VID"
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: service-ropc
      timeout_ms: 300000
      prefix: /ropc-grant/token
      rewrite: /ropc-grant/token
      service: test-ropc-adaptor:8090
      ambassador_id: ford-oem-ambass-ambassador
      weight: 100
``` 

4. In the Ambassador log, I can't find any ext_auth log content. And the ext_auth is not enabled.
When I send a request with invalid auth, I can't receive the 401 response. And the Ext Auth service didn't get any traffic from Ambassador. The log file of Ambassador pod is attached.

[Ambassador_pod.log](https://github.com/datawire/ambassador/files/3685618/Ambassador_pod.log)

**Expected behavior**
The ext_auth is enabled in K8S, just like the standalone docker container.

**Versions (please complete the following information):**
 - Ambassador: quay.io/datawire/ambassador:0.60.3
 - Kubernetes environment Bare Metal
 - Version v1.10.5
