### ISSUE TITLE
Support HTTP/2 upstream

### ISSUE THREAD

**Issue by psalaberria002** [datawire/ambassador#1936]
**Please describe your use case / problem.**
In Envoy it is possible to set `alpn_protocols: h2` for upstream services so the connections are HTTP/2. For that to work `http2_protocol_options` must be set as explained in https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#cluster .

I noticed that the grpc flag in the Mappings sets `http2_protocol_options` already, but my service is not grpc, and it seems hacky to abuse the flag for making HTTP/2 work :) See https://github.com/datawire/ambassador/blob/4b57121fdf8289f0baa71de6dc9d4d94e486b49c/python/ambassador/envoy/v2/v2cluster.py#L67-L68

**Describe the solution you'd like**
If `alpn_protocols` contains `h2`, `http2_protocol_options` should be set in the cluster config. I assume the `grpc` flag does more than just setting that field in the configs.

```
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: http2-test
spec:
  prefix: /http2-test
  service: "https://http2-test"
  tls: http2-test
  grpc: True # ??? What's the purpose of this flag? Is it only there for adding http2_protocol_options? If so, maybe that should be renamed.
---
apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: http2-test
spec:
  alpn_protocols: h2
  min_tls_version: v1.2
  secret: ambassador-dev-certs
```
