### ISSUE TITLE
Setting default timeout_ms globally

### ISSUE THREAD

**Issue by Flydiverny** [datawire/ambassador#1989]
**Please describe your use case / problem.**
Currently you can set `timeout_ms` on each _mapping_ indiviually, if this is not provided [Ambassador deafults](https://github.com/datawire/ambassador/blob/master/python/ambassador/envoy/v2/v2route.py#L136) to 3000 ms.

It would be great if you could configure this globally ie in the `ambassador` _module_. 

**Describe the solution you'd like**
Allow specifying a default timeout in the [ambassador module](https://www.getambassador.io/reference/core/ambassador/#the-ambassador-module) config 

```yaml
apiVersion: getambassador.io/v1
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    timeout_ms: 5000 # defaults to 3000 ms
```

**Describe alternatives you've considered**
Setting `timeout_ms` in every mapping and hoping no one forgets to increase it when configuring their mapping.

**Additional context**
Dug around a bit in ambassadors code, think if ambassador had a configurable default everything would be fine :smile:

for example [here](https://github.com/datawire/ambassador/blob/master/python/ambassador/envoy/v2/v2route.py#L136) it defaults to `3000` if `timeout_ms` is not set for the mapping, not sure how everything connects but would it be possible to do something like:

Before:
https://github.com/datawire/ambassador/blob/c5741177fbcd217af96154ac9c1a393826b15aea/python/ambassador/envoy/v2/v2route.py#L134-L138

After:
```py
        default_timeout_ms = config.ir.ambassador_module.get('timeout_ms', 3000)
        route = {
            'priority': group.get('priority'),
            'timeout': "%0.3fs" % (mapping.get('timeout_ms', default_timeout_ms) / 1000.0),
            'cluster': mapping.cluster.name
        }
```

([Slack discussion](https://datawire-oss.slack.com/archives/CAULN7S76/p1571937197337400))

**Comment by torian** [comment]
Faced same issue, got away with:
```
lua_scripts: |
  function envoy_on_request(request_handle)
    request_handle:headers():add("x-envoy-upstream-rq-timeout-ms", "30000")
  end
```
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-upstream-rq-timeout-ms

**Comment by Flydiverny** [comment]
Not stale

**Comment by nanugantiep** [comment]
> Faced same issue, got away with:
> 
> ```
> lua_scripts: |
>   function envoy_on_request(request_handle)
>     request_handle:headers():add("x-envoy-upstream-rq-timeout-ms", "30000")
>   end
> ```
> 
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-upstream-rq-timeout-ms

i tried this but its overriding other route mappings with more than given timeout. 
example:- 
-  `api/xyz` has mapping
```
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  emissary-timeout
spec:
  hostname: "*"
  prefix: /api/xyz/
  timeout_ms: 60000 # 1 minute timeout
```
- request_handle:headers():add("x-envoy-upstream-rq-timeout-ms", "30000")
 
 if `api/xyz` takes more than 30 sec then requests are failing, its not honoring mapping set for `api/xyz`. 
Any other way to set default timeout ?
