### ISSUE TITLE
503 NR Error When Updating Mapping

### ISSUE THREAD

**Issue by JustinPullen** [datawire/ambassador#2051]
**Describe the bug**
I receive a 503 NR error when I update a mapping.

ACCESS [2019-11-21T20:49:25.866Z] "GET /nginx/ HTTP/1.1" 503 NR 0 0 0 - "192.168.64.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" "977eb548-d706-4320
│ 81b9-af0e777cdcdc" "192.168.64.5:31471" ""

**To Reproduce**
Install minikube

>sysctl -a | grep -E --color 'machdep.cpu.features|VMX'

>brew install minikube

>minikube start --kubernetes-version v1.14.0

>kubectl cluster-info dump --namespace kube-system | grep authorization-mode

>kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml

Create ambassador-service.yaml file:
```
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 8080
  selector:
    service: ambassador
```

Run:
>kubectl apply -f ambassador-service.yaml

Create Deployment 1:
Create file deployment1.yaml with the below content
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  labels:
    deployment: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: nginx1
  template:
    metadata:
      labels:
        deployment: nginx1
    spec:
      containers:
        - name: app
          image: nginxdemos/hello
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: # make an HTTP request
              port: 80 # port to use
              path: / # endpoint to hit
              scheme: HTTP # or HTTPS
            periodSeconds: 5 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 2 # how many failures to accept before failing
            timeoutSeconds: 10 # how long to wait for a response
          livenessProbe:
            httpGet: # make an HTTP request
              port: 80 # port to use
              path: / # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 300 # how long to wait before checking
            periodSeconds: 30 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 2 # how many failures to accept before failing
            timeoutSeconds: 15 # how long to wait for a response
```

Run:
>kubectl apply -f deployment1.yaml

Create Deployment 2:
Create file deployment2.yaml with the below content
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  labels:
    deployment: nginx2
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: nginx2
  template:
    metadata:
      labels:
        deployment: nginx2
    spec:
      containers:
        - name: app
          image: nginxdemos/hello
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: # make an HTTP request
              port: 80 # port to use
              path: / # endpoint to hit
              scheme: HTTP # or HTTPS
            periodSeconds: 5 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 2 # how many failures to accept before failing
            timeoutSeconds: 10 # how long to wait for a response
          livenessProbe:
            httpGet: # make an HTTP request
              port: 80 # port to use
              path: / # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 300 # how long to wait before checking
            periodSeconds: 30 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 2 # how many failures to accept before failing
            timeoutSeconds: 15 # how long to wait for a response
```
Run:
>kubectl apply -f deployment2.yaml

Create Service 1:
Create file service1.yaml with the below content
```
---
apiVersion: v1
kind: Service
metadata:
  name: nginx1
  labels:
    deployment: nginx1
spec:
  selector:
    deployment: nginx1
  ports:
    - name: http
      port: 80
      targetPort: 80
```
Run:
>kubectl apply -f service1.yaml

Create Service 2:
Create file service2.yaml with the below content
```
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    deployment: nginx2
spec:
  selector:
    deployment: nginx2
  ports:
    - name: http
      port: 80
      targetPort: 80
```
Run:
>kubectl apply -f service2.yaml

Create Mapping 1:
Create file mapping1.yaml with the below content
```
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: nginx-ingress
  labels:
    deployment: nginx
spec:
  prefix: "/nginx/"
  rewrite: "/"
  service: nginx1
  retry_policy:
    retry_on: gateway-error
```
Run:
>kubectl apply -f mapping1.yaml

Access endpoint:

Find ambassador endpoint
>minikube service list

Hit the endpoint at http://IP:PORT/nginx/

Update the mapping
Create file mapping2.yaml with the below content
```
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: nginx-ingress
  labels:
    deployment: nginx
spec:
  prefix: "/nginx/"
  rewrite: "/"
  service: nginx2
  retry_policy:
    retry_on: gateway-error
```
Run:
>kubectl apply -f mapping2.yaml

Immediately after the update refresh the page and observe the 503s for a few seconds or up to a minute+.

**Expected behavior**
I expect the traffic to be changed immediately with no downtime.  I see a different behavior when I use the weight rules to migrate traffic using a second mapping but I am still at the mercy of some keep alive that the backend presents.  I really expect that once I update the definition to 100% of traffic to a new service it truly is 100% and does not leave some connections open or allow traffic to the old service.

**Versions (please complete the following information):**
 - Ambassador: 0.78.0, 0.84.1, 0.85.0
 - Kubernetes environment: Minikube, EKS 
 - Version 1.14

**Additional context**
I spoke with Noah Krause on slack about this.  I am seeing this in Tomcat and Nginx backends.
https://datawire-oss.slack.com/archives/CAULN7S76/p1573760024187400
