### ISSUE TITLE
Ambassador not working with zeppelin

### ISSUE THREAD

**Issue by RajeshHegde** [datawire/ambassador#2065]
**Describe the bug**
Hi,
I'm trying to proxy requests to zeppelin pods. But it is throwing 400 Bad Request from envoy.
Mapping:
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: notebook-b058d051cc1343c09f8522a2a41327e3
  namespace: default
spec:
  connect_timeout_ms: 4000
  host_rewrite: http://notebook-b058d051cc1343c09f8522a2a41327e3.default.svc.cluster.local
  idle_timeout_ms: 500000
  prefix: /notebooks/b058d051cc1343c09f8522a2a41327e3
  rewrite: /notebooks/b058d051cc1343c09f8522a2a41327e3
  service: http://notebook-b058d051cc1343c09f8522a2a41327e3.default.svc.cluster.local:50827
  timeout_ms: 4000
  use_websocket: true

I can access the zeppelin by port forwarding the service, but not from ambassador.
Zeppelin's url goes like this http://notebook-d8ed4ee76eb6457b86213e772a9c1c31.default.svc.cluster.local:50827/#/  My guess is ambassador is not passing anything after # might be the issue.
Any idea how can I resolve this?

**To Reproduce**
1. Zeppelin deployment
```
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    uuid: d8ed4ee76eb6457b86213e772a9c1c31
  name: notebook-d8ed4ee76eb6457b86213e772a9c1c31
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      uuid: d8ed4ee76eb6457b86213e772a9c1c31
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        uuid: d8ed4ee76eb6457b86213e772a9c1c31
      name: notebook-d8ed4ee76eb6457b86213e772a9c1c31
      namespace: default
    spec:
      containers:
      - env:
        - name: ZEPPELIN_SERVER_CONTEXT_PATH
          value: /notebooks/d8ed4ee76eb6457b86213e772a9c1c31
        image: apache/zeppelin:0.8.2
        imagePullPolicy: IfNotPresent
        name: notebook
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebooks/d8ed4ee76eb6457b86213e772a9c1c31/#/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

# Service
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  labels:
    uuid: d8ed4ee76eb6457b86213e772a9c1c31
  name: notebook-d8ed4ee76eb6457b86213e772a9c1c31
  namespace: default
spec:
  connect_timeout_ms: 4000
  host_rewrite: http://notebook-d8ed4ee76eb6457b86213e772a9c1c31.default.svc.cluster.local
  idle_timeout_ms: 500000
  prefix: /notebooks/d8ed4ee76eb6457b86213e772a9c1c31
  rewrite: /notebooks/d8ed4ee76eb6457b86213e772a9c1c31
  service: http://notebook-d8ed4ee76eb6457b86213e772a9c1c31.default.svc.cluster.local:57174
  timeout_ms: 4000
  use_websocket: true

```
2. Ambassador mapping
```
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  labels:
    uuid: d8ed4ee76eb6457b86213e772a9c1c31
  name: notebook-d8ed4ee76eb6457b86213e772a9c1c31
  namespace: default
spec:
  connect_timeout_ms: 4000
  host_rewrite: http://notebook-d8ed4ee76eb6457b86213e772a9c1c31.default.svc.cluster.local
  idle_timeout_ms: 500000
  prefix: /notebooks/d8ed4ee76eb6457b86213e772a9c1c31
  rewrite: /notebooks/d8ed4ee76eb6457b86213e772a9c1c31
  service: http://notebook-d8ed4ee76eb6457b86213e772a9c1c31.default.svc.cluster.local:57174
  timeout_ms: 4000
  use_websocket: true

```
3. Curl
```
curl -v --http1.1 "https://ambassador-ip/notebooks/d8ed4ee76eb6457b86213e772a9c1c31/#/"
```
```
> GET /notebooks/d8ed4ee76eb6457b86213e772a9c1c31/ HTTP/1.1
> Host: http://notebook-d8ed4ee76eb6457b86213e772a9c1c31.default.svc.cluster.local
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< content-type: text/html;charset=iso-8859-1
< content-length: 55
< server: envoy
< x-envoy-upstream-service-time: 4
< date: Wed, 27 Nov 2019 09:50:47 GMT
< Via: 1.1 google
< Alt-Svc: clear
<
* Connection #0 to host dev.ambassador.dblue.ai left intact
<h1>Bad Message 400</h1><pre>reason: Bad HostPort</pre>* Closing connection 0
```

**Versions (please complete the following information):**
 - Ambassador: 0.85.0
 - Kubernetes environment : Google Kubernetes Engine
 - Version : 1.13.11-gke.14
