### ISSUE TITLE
Downstream service unavailability when scaling down

### ISSUE THREAD

**Issue by maryoush** [datawire/ambassador#2076]
**Describe the bug**
I have an ambassador setup hosted on AWS.
We are experiencing some 5xx when pods scaled down via kubectl and reached in meantime via ambassador.

To overcome that we have applied endpoint resolver

```
 ---
      apiVersion: ambassador/v1
      kind: KubernetesEndpointResolver
      name: endpoint
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name: echo-service_mapping_root
      prefix: /echo-service/
      resolver: endpoint
      load_balancer:
        policy: round_robin
      remove_response_headers:
      - x-envoy-upstream-service-time
      - x-envoy-decorator-operation
      service: https://echo-service.orks.svc.cluster.local.:80
      tls: upstream    

``` 
which resulted in envoys cluster configuration 

```
 "lb_policy": "ROUND_ROBIN",
    "load_assignment": {
        "cluster_name": "cluster_https___echo_service_orks_svc_cl-0",
        "endpoints": [
            {
                "lb_endpoints": [
                    {
                        "endpoint": {
                            "address": {
                                "socket_address": {
                                    "address": "10.244.133.40",
                                    "port_value": 8080
                                }
                            }
                        }
                    }
                ]
            }
        ]
    },
```

But it seems to not help there.

**To Reproduce**
Add endpoint resolver https://www.getambassador.io/reference/core/resolvers/
BTW you COULD have mentioned in documentation  that w/o loadbalancer policy the end point resolver doesn't get applied  

E.g as above for echo-service.
Scale up echo-service e.g to 5 instances 
Run some load test on echo service via ambassador.
Scale down echo service back to 1 instance.

```
ACCESS [2019-12-03T10:01:46.832Z] "GET /echo-service/echo HTTP/1.1" 503 - 0 95 297 - "188.123.210.85,64.252.178.160" "curl/7.54.0" "fce6c185-5b28-4701-9ebf-52e6907b47b7" "orksbeat.api.stage.context.cloud.sap" "10.244.101.163:8080"
ACCESS [2019-12-03T10:01:47.378Z] "GET /echo-service/echo HTTP/1.1" 200 - 0 4999 2 - "188.123.210.85,64.252.178.160" "curl/7.54.0" "48f9fe97-9897-41a8-ae15-1ce65d4161cf" "orksbeat.api.stage.context.cloud.sap" "10.244.133.40:8080"
ACCESS [2019-12-03T10:01:47.633Z] "GET /echo-service/echo HTTP/1.1" 503 - 0 91 2 - "188.123.210.85,64.252.178.148" "curl/7.54.0" "23eb74df-e4d0-42eb-913e-cd9e1f173ca5" "orksbeat.api.stage.context.cloud.sap" "10.244.165.31:8080"
ACCESS [2019-12-03T10:01:47.890Z] "GET /echo-service/echo HTTP/1.1" 503 - 0 91 2 - "188.123.210.85,64.252.178.148" "curl/7.54.0" "5b789ed1-4e12-43c9-a54a-71da9d960636" "orksbeat.api.stage.context.cloud.sap" "10.244.58.145:8080"
ACCESS [2019-12-03T10:01:48.150Z] "GET /echo-service/echo HTTP/1.1" 503 - 0 91 2 - "188.123.210.85,64.252.178.75" "curl/7.54.0" "6773175c-f795-4ab1-b7a7-110608d20342" "orksbeat.api.stage.context.cloud.sap" "10.244.81.69:8080"
ACCESS [2019-12-03T10:01:48.405Z] "GET /echo-service/echo HTTP/1.1" 503 - 0 91 3 - "188.123.210.85,64.252.178.160" "curl/7.54.0" "5b24315f-954e-4c27-98fc-f0a911c6187a" "orksbeat.api.stage.context.cloud.sap" "10.244.101.163:8080"
```

**Expected behaviour**
A resource is disposed in ambassador so that no requests don't get routed to already disposed pod.  

**Versions (please complete the following information):**
 - Ambassador: Ambassador version 0.84.1
 - Kubernetes environment 
```
    nodeInfo:
      architecture: amd64
      bootID: 0cb42fab-863a-44b9-a475-59710ce13768
      containerRuntimeVersion: docker://18.6.3
      kernelVersion: 4.19.84-coreos
      kubeProxyVersion: v1.12.3
      kubeletVersion: v1.12.3
      machineID: ec2c0cb0605f0d4ffd2ea258651cf451
      operatingSystem: linux
      osImage: Container Linux by CoreOS 2247.7.0 (Rhyolite)
      systemUUID: ec2c0cb0-605f-0d4f-fd2e-a258651cf451
```

 - Kubectl 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

Regards Mariusz
