### ISSUE TITLE
Document using Consul Connect integration with Consul ACLs

### ISSUE THREAD

**Issue by HT154** [datawire/ambassador#2079]
https://www.getambassador.io/user-guide/consul-connect-ambassador/ does not include any info on how to run the Consul connector with ACLs enabled and it's not obvious what needs to be done to do so. This process should be documented on that page.

Here's how I've done it, but I'm not sure if it's the most correct approach:
```yaml
# Add to https://getambassador.io/yaml/consul/ambassador-consul-connector.yaml
        env:
        - name: CONSUL_HTTP_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: <helm release name>-consul-bootstrap-acl-token
```
It seems like there should be a better way that using the bootstrap token.
