### ISSUE TITLE
Ambassador pod crashes when not using the right ClusterRoleBinding

### ISSUE THREAD

**Issue by inercia** [datawire/ambassador#2108]
**Describe the bug**

Ambassador pod crashes when not using the right ClusterRoleBinding

**To Reproduce**

I did not specify a valid namespace in the ClusterRoleBinding for Ambassador.

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
  - kind: ServiceAccount
    name: ambassador
    # namespace: default
```

```
2019/12/12 16:14:03 kubebootstrap: adding kubernetes watch for "service" in namespace "*"
2019/12/12 16:14:03 api: snapshot server listening on: :8002
2019/12/12 16:14:03 kubebootstrap: ERROR: WORKER PANICKED: services is forbidden: User "system:serviceaccount:default:ambassador" cannot list resource "services" in API group "" at the cluster scope
goroutine 389 [running]:
runtime/debug.Stack(0xc000b23630, 0x135ae60, 0xc0000f14a0)
	runtime/debug/stack.go:24 +0x9d
github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch.func1.1.1(0xc000b23f98)
	github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:194 +0x57
panic(0x135ae60, 0xc0000f14a0)
	runtime/panic.go:679 +0x1b2
github.com/datawire/ambassador/pkg/k8s.(*Watcher).sync(0xc0007885c0, 0x0, 0x0, 0xc00004412c, 0x2, 0xc000045130, 0x8, 0xc000045138, 0x7, 0x1)
	github.com/datawire/ambassador@/pkg/k8s/watcher.go:222 +0x24c
github.com/datawire/ambassador/pkg/k8s.(*Watcher).Start(0xc0007885c0)
	github.com/datawire/ambassador@/pkg/k8s/watcher.go:205 +0x140
main.(*kubebootstrap).Work(0xc000281dc0, 0xc000739080, 0x0, 0xc000540358)
	github.com/datawire/ambassador@/cmd/watt/kubewatchman.go:165 +0x58
github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch.func1.1(0xc000b23f98, 0xc000338900, 0xc000739080)
	github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:199 +0x7a
github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch.func1(0xc000338900, 0xc000739080, 0xc000281e30)
	github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:200 +0x5f
created by github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch
	github.com/datawire/ambassador@/pkg/supervisor/supervisor.go:189 +0xb2
```

** Version **

```
commit ef8fe4a215254bb717d2c5fb7b69fc36e7fb35a0 (tag: v1.0.0-ea2, origin/master, origin/HEAD, master)
```
