### ISSUE TITLE
Unable to append cookie header

### ISSUE THREAD

**Issue by imranismail** [datawire/ambassador#2144]
**Please describe your use case / problem.**
Right now header is a dict and I can't append `set-cookie` more than once

**Describe the solution you'd like**

```yaml
add_response_headers:
- header:
    key: set-cookie
    value: name=val; Path=/
- header:
    key: set-cookie
    value: name2=val2; Path=/
  append: false
```

OR

```yaml
add_response_headers:
- set-cookie: name=val; Path=/
- set-cookie: 
    value: name2=val2; Path=/
    append: false
```
