### ISSUE TITLE
ring_hash policy doesn't seem to route requests to the same pod

### ISSUE THREAD

**Issue by archhhh** [datawire/ambassador#2165]
**Describe the bug**
Currently I am testing simple hello world gRPC app and trying to load balance requests across three instances of the app on kubernetes with ambassador. My app outputs the pod name which accepted the request and when using ring_hash load balancer policy, even though it seems most of the time the requests go to the similar pod, other times they go to other pods, which is weird, because isn't this policy supposed to route requests from the same source ip for example to the same pod?

**To Reproduce**
1. Run three pods on kubernetes
2. Deploy service for the pods
3. Try ambassador load balancing with ring_hash policy and source_ip : true

**Expected behavior**
Locally app should route to the same pod

**Versions (please complete the following information):**
 - Ambassador: 0.6
 - Kubernetes environment: minikube

app's output 
![Screen Shot 2020-01-10 at 5 55 38 PM](https://user-images.githubusercontent.com/26677794/72139587-6e021380-33d2-11ea-8bfd-0a38850435c7.png)

yaml file
![Screen Shot 2020-01-10 at 5 56 10 PM](https://user-images.githubusercontent.com/26677794/72139656-840fd400-33d2-11ea-9cde-3bd1ac41b54a.png)

**Comment by archhhh** [comment]
Using resolver properly in config file fixed the issue.

**Comment by tannaga** [comment]
@archhhh I am running into similar issue. Could you please share what did you to do the fix?
My resolver and module definition is like this

```
apiVersion: getambassador.io/v2
kind: KubernetesEndpointResolver
metadata:
  name: my-resolver1       
---
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    resolver: my-resolver1
    load_balancer:
      policy: ring_hash
      header: sessionKey
```
Thank you!
