### ISSUE TITLE
Users need the YAML input validator to catch bad labels in Mappings

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#2184]
If you put e.g. an empty string in a `labels` definition in a `Mapping`:

```
labels:
  ambassador:
  - foo:
    - bar
    - ''
```

you'll find that it turns into `{ generic_key: "" }` deep in the Envoy config, which Envoy will reject as it's not valid. Ambassador should toss out either the `label` or the whole `Mapping`.
