### ISSUE TITLE
Odd behaviour with adding response header and canary

### ISSUE THREAD

**Issue by eshepelyuk** [datawire/ambassador#2213]
**Describe the bug**
`add_response_headers` works inconsistently in canary deployment

**To Reproduce**
1. Deploy two services `eshepelyuk-fastapi` and `eshepelyuk-fastapi2`, as in example
2. Create mappings in cluster
```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eshepelyuk-fastapi-v1
  namespace: eshepelyuk-env
spec:
  prefix: /fastapi/
  service: eshepelyuk-fastapi:9090
  weight: 50
  add_response_headers:
    x-version: "v1"
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: eshepelyuk-fastapi-v2
  namespace: eshepelyuk-env
spec:
  prefix: /fastapi/
  service: eshepelyuk-fastapi2:9090
  weight: 50
  add_response_headers:
    x-version: "v2"
```
3. Hit `/fastapi` few times with curl, the same header is sent regardless of the actual mapping and service. 

**Expected behavior**
I expect header `x-version` to channge correspondingly to the declared in mapppings.

**Versions (please complete the following information):**
 - Ambassador Edge Stack 1.0.0, installed via Helm
 - Kubernetes v 1.15.6, kops cluster on EC2
