### ISSUE TITLE
Cannot create mappings with same name in different namespaces

### ISSUE THREAD

**Issue by concaf** [datawire/ambassador#2226]
**Describe the bug**
Ambassador does not allow 2 mappings with the same name with different/same config in different namespaces. An error pops up saying -
```
CONFIGURATION ERRORS
httpbin.ingress2.1: <Mapping httpbin.ingress2.1> defines Mapping httpbin, which is already defined by httpbin.ingress1.1
```

**To Reproduce**
1. Create 2 mappings with the same name (but not necessarily same config) in different namespaces. Example:

Create namespaces:

`kubectl create ns ingress1`
`kubectl create ns ingress2`
 
and then create the following mappings:

```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: httpbin
  namespace: ingress2
spec:
  host_rewrite: hb.com
  prefix: /hb2/
  service: http://hb.com
```

and 

```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: httpbin
  namespace: ingress1
spec:
  host_rewrite: httpbin.org
  prefix: /hb/
  service: http://httpbin.org                                                                                                                                                                                                                                 
```

**Expected behavior**
Both mappings should work fine

**Versions (please complete the following information):**
 - Ambassador: 1.0.0 and master and since the beginning of time??
