### ISSUE TITLE
Provide way to define multiple mappings under same domain with less overhead

### ISSUE THREAD

**Issue by brennancheung** [datawire/ambassador#2231]
**Please describe your use case / problem.**

When a particular domain has multiple services running under it, each with their own path, it is very cumbersome to create a separate object for each one.  The `host` field needs to be repeated in each object.  Also, there is the overhead of the object itself and having to repeat `apiVersion`, `kind`, etc each time.

Here is an example of mappings I had to set up to get Harbor to work:

```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: harbor-portal
  namespace: default
spec:
  host: core.harbor.mydomain.com
  prefix: /
  service: harbor-harbor-portal
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: harbor-core-api
  namespace: default
spec:
  host: core.harbor.mydomain.com
  prefix: /api
  service: harbor-harbor-core
  rewrite: /api
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: harbor-core-service
  namespace: default
spec:
  host: core.harbor.mydomain.com
  prefix: /service
  service: harbor-harbor-core
  rewrite: /service
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: harbor-v2
  namespace: default
spec:
  host: core.harbor.mydomain.com
  prefix: /v2
  service: harbor-harbor-core
  rewrite: /v2
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: harbor-chartrepo
  namespace: default
spec:
  host: core.harbor.mydomain.com
  prefix: /chartrepo
  service: harbor-harbor-core
  rewrite: /chartrepo
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: harbor-c
  namespace: default
spec:
  host: core.harbor.mydomain.com
  prefix: /c
  service: harbor-harbor-core
  rewrite: /c
```

Also note the repeated `rewrite` in each object that exist solely to prevent rewrite from happening in the first place.  It would be nice if I could just specify not rewriting the path just once.

**Describe the solution you'd like**

Allow arrays to be used for the variable parts and common fields only specified once.

A more ideal solution would be something like this:

```yaml
apiVersion: getambassador.io/v2
kind: Mappings
metadata:
  name: harbor-mappings
  namespace: default
spec:
  host: core.harbor.mydomain.com
  rewrite: ""
  mappings:
    - prefix: /
      service: harbor-harbor-portal
    - prefix: /api
      service: harbor-harbor-core
    - prefix: /service
      service: harbor-harbor-core
    - prefix: /v2
      service: harbor-harbor-core
    - prefix: /chartrepo
      service: harbor-harbor-core
    - prefix: /c
      service: harbor-harbor-core
```

**Comment by brennancheung** [comment]
Perhaps as a general pattern, underneath `spec` they can have all the normal mapping fields.  If they are defined at that level they get applied to all.  But if they are defined at a lower level they can override the global setting.

Ex:

```yaml
apiVersion: getambassador.io/v2
kind: Mappings
metadata:
  name: harbor-mappings
  namespace: default
spec:
  host: core.harbor.mydomain.com
  rewrite: ""
  paths:
    - prefix: /
      service: harbor-harbor-portal
    - prefix: /api
      service: harbor-harbor-core
      rewrite: "/somewhere-else"
    - prefix: /v2
      service: harbor-harbor-core

```
