### ISSUE TITLE
grpc hello world example does not work clean ambassador edge install on kubeadm

### ISSUE THREAD

**Issue by cogmeta** [datawire/ambassador#2252]
**Describe the bug**

We had clean install of ambassador edge on aws instance running kubeadm 1.17.0.  Then we deployed grpc hello world example but  executing greeter_client.py  result in an error. Also, grpc example pod log has some strange error

sudo docker logs 0a6f7953d987 -f
E0129 08:00:33.483639279       9 http_server_filter.cc:299]  GET request without QUERY
E0129 08:01:33.479603017       9 http_server_filter.cc:299]  GET request without QUERY
E0129 08:02:33.482634173       9 http_server_filter.cc:299]  GET request without QUERY

and running greeter_client.py with ambassador host and port  give and error:

 python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 38, in <module>
    run()
  File "greeter_client.py", line 32, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grpc/_channel.py", line 824, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grpc/_channel.py", line 726, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "unknown service edge_stack_ui/helloworld.Greeter"
        debug_error_string = "{"created":"@1580285513.750873999","description":"Error received from peer ipv4:172.31.79.169:80","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"unknown service edge_stack_ui/helloworld.Greeter","grpc_status":12}"
>

**To Reproduce**
1. Clean install ambassador edge
2. configure host and certificate
3. download and deploy grpc example hello world
4. lanch greeter_client.py with ambassador host and port 

**Expected behavior**
expected a reply 
$ python greeter_client.py
Greeter client received: Hello, you!

**Versions (please complete the following information):**
 - Ambassador Ede stack : [1.0.0]
 - Kubernetes environment: Kubeadm
 - Version [1.17.0]

**Additional context**

**Comment by cogmeta** [comment]
![image](https://user-images.githubusercontent.com/10062479/73339327-890fc700-429e-11ea-8476-7097ade5db22.png)

**Comment by cogmeta** [comment]
Acessing directly the pod ip and service cluster IP works fine

**Comment by cogmeta** [comment]
python greeter_client.py
E0129 09:44:33.734151606    3758 ssl_transport_security.cc:1246] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
Traceback (most recent call last):
  File "greeter_client.py", line 39, in <module>
    run()
  File "greeter_client.py", line 33, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grpc/_channel.py", line 824, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/grpc/_channel.py", line 726, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1580291073.734250613","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1580291073.734246938","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"
>

**Comment by buehler** [comment]
Well.. funny enough I've got the same error...

What did you do @cogmeta ?

**Comment by cogmeta** [comment]
@buehler Nothing. No response from ambassador team. It was panic few days but we managed to shift everything to web sockets.

**Comment by buehler** [comment]
Hmm.. Alright. would you mind to reopen the issue? I'm running into the same errors right now :-/

**Comment by cogmeta** [comment]
The silence from Ambassador team is mind boggling or we are doing something really stupid that they dont consider worth responding to.

**Comment by buehler** [comment]
Thanks... I'm currently investigating the issue. Maybe I'll come up with some info.

**Comment by kflynn** [comment]
Well, it definitely wasn't that we consider it not worth responding to! Mea culpa: there's been a lot going on.

Can you post the YAML you used to deploy your GRPC service?

**Comment by cogmeta** [comment]
I followed the instruction given here https://www.getambassador.io/user-guide/grpc/  step bys step and used the yaml given there.

**Comment by kflynn** [comment]
@buehler, which are you seeing?

**Comment by buehler** [comment]
Hmm well on my side, when I use ambassador to route a grpc service
```yaml
spec:
  grpc: true
  host: myhost.foobar
  prefix: /foo/bar/
  service: mysvc
  timeout_ms: 0
```

the prefix gets correctly stripped away (which is, what I thought it should do) but then the prefix `edge_stack_ui/` is added to the url. which results in incorrect urls.

So instead of `myhost.foobar/foo/bar/SERVICE/METHOD` -> `mysvc/SERVICE/METHOD`  it creates
`myhost.foobar/foo/bar/SERVICE/METHOD` -> `mysvc/edge_stack_ui/SERVICE` which is obviously not a valid grpc endpoint on the service.

That is, with the modules for grpc-web and grpc http 11 bridge active.

**Comment by chinltong** [comment]
we have the same issue that Ambassador is prepending "/edge_stack_ui" to the mapping in gRPC calls. please follow up. Thanks a million

**Comment by buehler** [comment]
What I experienced now is that those prepended urls are happening when there is no match for a mapping in ambassador. Then he tries to redirect to the UI.

When I fixed (some other) mapping, this edge-stack-ui prefix was gone and the routing was correct.

**Comment by chinltong** [comment]
> What I experienced now is that those prepended urls are happening when there is no match for a mapping in ambassador. Then he tries to redirect to the UI.
> 
> When I fixed (some other) mapping, this edge-stack-ui prefix was gone and the routing was correct.

How did you find out the mismatch?  Ambassador pod/container does not allow tcpdump.

**Comment by AndreasKlein** [comment]
Hey everyone, I just faced the exact same issue. I was able to fix it by adding `rewrite: '/'` (which should be default) to the `spec` of the mapping. After that the mapping made it into the envoy route table. 
I am able to reproduce the behavior multiple times.

**Comment by kflynn** [comment]
So looking over the docs, I'm a little curious what `Mapping`s people are using exactly?  Here's the `Mapping` from https://www.getambassador.io/user-guide/grpc/:

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: grpc-py
spec:
  grpc: True
  prefix: /helloworld.Greeter/
  rewrite: /helloworld.Greeter/
  service: grpc-example
```

where we've deliberately set the `prefix` and the `rewrite` to have the same value.

Fully realizing that what I'm about to write may be hopelessly naïve (🙂), I would kind of expect that you'd need that `rewrite` there so that your gRPC service sees the provider and the service name. What am I missing here in your actual use cases?

(My ulterior motive here is that I think that there should be a new CRD for gRPC mappings, but I want to get that right rather than just wedging something in.)

**Comment by DanielBFox** [comment]
Hello,
I'm facing exactly the same issue with the "greeter" example on a fresh install of release 1.2.
(cfr slack thread I posted the 2nd of March  https://app.slack.com/client/T0N2YK9CZ/CAULN7S76/thread/CAULN7S76-1583175338.184200)

**Comment by cchatfield** [comment]
If you are adding a host in addition to the prefix:
```
spec:
  grpc: true
  prefix: /some.service/
  rewrite: /some.service/
  host: my.server.com
```

You need to send additional metadata with the client request (golang):

```
ctx = metadata.AppendToOutgoingContext(ctx, ":authority", "my.server.com")
```

That should remove the prepended edge_stack_ui issue.

Sorta referenced here: https://www.getambassador.io/docs/latest/howtos/grpc/#grpc-headers

**Comment by cchatfield** [comment]
if you designate a host and the port is not 80, you need to define the port in the host entry

host: my.server.com:443

**Comment by jieyu** [comment]
I hit the same issue following the doc step by step.
```bash
➜  helloworld git:(master) ✗ python3 greeter_client_insecure.py 
Traceback (most recent call last):
  File "greeter_client_insecure.py", line 39, in <module>
    run()
  File "greeter_client_insecure.py", line 33, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = ""
        debug_error_string = "{"created":"@1595457044.950092000","description":"Error received from peer ipv4:54.148.164.217:80","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"","grpc_status":12}"
```

I traced the debug log
```
[2020-07-22 23:15:52.759][235][debug][http] [source/common/http/conn_manager_impl.cc:782] [C7666][S2474510021369480270] request headers complete (end_stream=false):
':scheme', 'http'
':method', 'POST'
':authority', 'a828fd023c7b24ea9bd4a1aa9378f70b-1802391861.us-west-2.elb.amazonaws.com:80'
':path', '/helloworld.Greeter/SayHello'
'te', 'trailers'
'content-type', 'application/grpc'
'user-agent', 'grpc-python/1.30.0 grpc-c/10.0.0 (osx; chttp2)'
'grpc-accept-encoding', 'identity,deflate,gzip'
'accept-encoding', 'identity,gzip'
[2020-07-22 23:15:52.759][235][debug][router] [source/common/router/router.cc:415] [C7666][S2474510021369480270] no cluster match for URL '/helloworld.Greeter/SayHello'
[2020-07-22 23:15:52.759][235][debug][http] [source/common/http/conn_manager_impl.cc:1479] [C7666][S2474510021369480270] Sending local reply with details route_not_found
[2020-07-22 23:15:52.759][235][debug][http] [source/common/http/conn_manager_impl.cc:1710] [C7666][S2474510021369480270] encoding headers via codec (end_stream=true):
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '12'
'date', 'Wed, 22 Jul 2020 23:15:52 GMT'
'server', 'envoy'
```

Notice that `no cluster match for URL '/helloworld.Greeter/SayHello'` in the debug log.

Then, I checked the generated envoy config in the pod. Turns out that the route is not added to the non-secure listener (port 80->8080), and only exists in the secure listener (port 443->8443).

After switching to use the secure port (443) with a valid certificate, it worked.

```yaml
--                                                                                                                                                                                                                                                                                                                         
apiVersion: getambassador.io/v2                                                                                                                                                                                                                                                                                             
kind: TLSContext                                                                                                                                                                                                                                                                                                            
metadata:                                                                                                                                                                                                                                                                                                                   
  name: tls                                                                                                                                                                                                                                                                                                                 
  namespace: ambassador                                                                                                                                                                                                                                                                                                     
spec:                                                                                                                                                                                                                                                                                                                       
  hosts:                                                                                                                                                                                                                                                                                                                    
  - "*"                                                                                                                                                                                                                                                                                                                     
  secret: ambassador-certs                                                                                                                                                                                                                                                                                                  
  alpn_protocols: h2
```
