### ISSUE TITLE
Make it possible to not expose the edge policy console to the internet

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#2254]
The EPC is by default always exposed to the internet of `https://{{DOMAIN}}/edge_stack/admin`.

While this does not provide a security concern since you require access to the cluster in order to `edgectl login`, it is not ideal to have this be something users can accidentally stumble upon. 

It should be possible to remove this from the routing table so  you need to `port-forward` the pod (or something similar) to access the EPC.

**Comment by minho-comcom-ai** [comment]
Try this: (only `ambassador.prod.my.domain` works)
```yaml
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  namespace: ambassador
  name: wildcard-domains
  annotations:
    getambassador.io/resource-changed: 'true'
spec:
  prefix: /
  service: istio-ingressgateway.istio-system
  precedence: 2000000
---
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  namespace: ambassador
  name: ambassador-domain
  annotations:
    getambassador.io/resource-changed: 'true'
spec:
  host: ambassador.prod.my.domain
  prefix: /edge_stack/
  rewrite: /edge_stack_ui/edge_stack/
  service: 127.0.0.1:8500
  precedence: 2000000
  timeout_ms: 60000
```
