### ISSUE TITLE
Module is not loaded when ambassador_id is set

### ISSUE THREAD

**Issue by pbabilas** [datawire/ambassador#2266]
**Describe the bug**
When I tried to start multiple ambassador with ambassador_id, module is not loaded to ambassador

**To Reproduce**
1. Apply ambassador with AMBASSADO_ID env.
2. Apply Module with ambassador_id like:

```yaml
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    server_name: test
    ambassador_id: ext

```
Tried that also:

```yaml
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  ambassador_id: ext
  config:
    server_name: test
```

Becouse documentation is not straight with that.

**Expected behavior**
When I apply module with ambassador_Id I expect to load it into correct ambassador pod.

**Versions:**
 - Ambassador: 1.1.0
 - Kubernetes self hosted 1.17.1

**Additional context**
Clear cluster configuration with ambassador.

**Comment by Fisionit** [comment]
@pbabilas - I'm having a multi ambassador setup myself and this is my Module config

```
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  ambassador_id: [ "ambassador-external", "ambassador-internal" ]
  config:
    server_name: ambassador
    diagnostics:
      enabled: true
```

I did log an issue too #2283 because I noticed that:

- The name of the module must be **ambassador** otherwise it's ignored regardless if you specify the ambassador_id
- The ambassador_id must be outside the config spec for it to work

You might want to try one of the following approaches as I noticed sometimes the syntax differs per object

```
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  ambassador_id: [ "ext" ]
  config:
    server_name: test
```
or
```
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  ambassador_id:
  - 'ext'
  config:
    server_name: test
```
