### ISSUE TITLE
/.well-known/acme-challenge not working on 1.1

### ISSUE THREAD

**Issue by pbabilas** [datawire/ambassador#2273]
**Describe the bug**
Routes on letsencrypt http01 challenge is not working on >= 1.0 ambassador.

**To Reproduce**
Easiest to reproduce is with cert-manager:
1. Install cert-manager
2. Add service and mapping to solver:

```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge
spec:
  prefix: /.well-known/acme-challenge
  host: example.com
  rewrite: ""
  service: acme-challenge-service.example

---

apiVersion: v1
kind: Service
metadata:
  name: acme-challenge-service
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
```
3. Add certificate - then pod is created
4. No route is working with example.com/.well-known/acme-challenge/token/key
Mapping is not used when using that route, but when I use example.com/.well-known/acme-challenge route it gets to pod :o

Envoy configuration has predefined:

```json
{
                                                        "match": {
                                                            "case_sensitive": true,
                                                            "prefix": "/.well-known/acme-challenge/"
                                                        },
                                                        "route": {
                                                            "cluster": "cluster_extauth_127_0_0_1_8500_ambassador",
                                                            "prefix_rewrite": "/.well-known/acme-challenge/",
                                                            "timeout": "3.000s"
                                                        }
                                                    },
```

Log shows: 
```
[ambassador-7c84bf4c47-pj9r6] ACCESS [2020-02-05T07:53:32.122Z] "GET /.well-known/acme-challenge/dRS1iK-IjW328ek4ml_OfcOMt26I4GFIOOrujKOkcKs HTTP/1.1" 404 - 0 19 1 0 "172.16.36.240" "Go-http-client/1.1" "03022f24-19f0-49e8-9473-e3e7fae7e157" "example.com" "127.0.0.1:8500"
```

example.com is ofc for previous reason ;]

**Expected behavior**
When I trigger route example.com/.well-known/acme-challenge/token/key it shoud get to solver pod by my mapping and service.

**Versions**
 - Ambassador: 1.1
 - Kubernetes v1.17.1

**Additional context**
Before version 1.0 configuration was working fine.

**Comment by pbabilas** [comment]
Ok, there is change in sources with mapping prefix. When using mapping like in doc ambassador add its own routingv2listener.py:573 - the we need to have mapping for /.well_known/acme-challenge/ instead of /.well_known/acme-challenge .
Thats all folks.

**Comment by muffinrecon** [comment]
Hi @pbabilas 

Can you paste the mapping config you used to fix this issue?

**Comment by pbabilas** [comment]
@muffinrecon below ;]

```yaml
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge
spec:
  prefix: /.well-known/acme-challenge/
  host: example.com
  rewrite: ""
  service: acme-challenge.namespace
```
Docu says that path should be `/.well-known/acme-challenge` but it is wrong.
Hope it helps.
