### ISSUE TITLE
Mappings created through annotations are not listed in Edge UI

### ISSUE THREAD

**Issue by mrtnfchs** [datawire/ambassador#2282]
Ambassador Edge Stack allows us to add mappings in two different ways, using service annotations and creating mapping resources as described in [here](https://www.getambassador.io/reference/mappings/). When creating a mapping via the mapping CRD they are listed in both the diagnostic page and Edge UI (mappings) but when they are created via service annotations they are only listed in the diagnostic page and not on the Edge UI portal

When adding a service annotation as shown below the mapping is only listed in the diagnostic page

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: grafana-mapping
      prefix: /grafana/
      service: grafana.istio-system:3000
```
 When creating the same mapping via the CRD as shown below, the mapping is shown in both the diagnostic page and Edge UI

```
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  grafana
spec:
  prefix: /grafana/
  service: grafana.istio-system:3000
```
Functionality doesn't seem to be impacted because even if these mappings are not listed in the Edge UI the routes still seem to work fine but ideally they should be shown in both places

I'm using following versions:
- Ambassador Edge Stack helm chart v6.1.1
- Ambassador Edge Stack image v1.1.0
- AWS EKS with Kubernetes v1.14.8
