### ISSUE TITLE
Unable to add Host CRD hostname with * on Ambassador Edge Stack

### ISSUE THREAD

**Issue by mrtnfchs** [datawire/ambassador#2284]
If you need to support multiple subdomains on Ambassador Edge Stack, you should be able to specify an * for the hostname as shown below.

```
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: ambassador
spec:
  hostname: '*.example.com'
  acmeProvider:
    authority: none
  ambassador_id:
  - 'ambassador-internal'
  - 'ambassador-external'
```

This works fine when ambassador is already fully started.  Ambassador will pick up the host config and applies it. However when pods are being restarted they are unable to start with the following error

`
ambassador-external-jh4v6 ambassador 2020/02/06 14:47:51 kubernetes:service\|ambassador\|*\|hostname=*.example.com: ERROR: WORKER PANICKED: unable to parse requirement: invalid label value: "*.example.com": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
`

I'm using following versions:
- Ambassador Edge Stack helm chart v6.1.1
- Ambassador Edge Stack image v1.1.0
- AWS EKS with Kubernetes v1.14.8

**Comment by ekarmazin** [comment]
Same issue here as well:

**Comment by kflynn** [comment]
I'm sorry to confirm that this is definitely a bug in Ambassador. The `Host` CRD is designed to allow for a `selector` that Ambassador can use later to find additional resources, and the default selector code is... uh... wrong. 😢 

For the moment, you can work around this by adding

```
selector:
  matchLabels:
    unusedHostname=workaround
```

to your wildcard `Host` CRD `spec` (where really the label can be anything). Sorry for the confusion!!

**Comment by Seb-SK** [comment]
Hi !

One follow-up question : Does this Host CRD hostname support wildcards with acme auth ? Here in the original question the problem was related to "authority: none" but I would like to use this with acme and let's encrypt.

But when I try to inject this host :
```
apiVersion: getambassador.com/v2
kind: Host
metadata:
  name: example-cert
  namespace: ambassador
spec:
  acmeProvider:
    authority: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com
  hostname: '*.example.com'
  selector:
    matchLabels:
      hostname: example-workaround.com
  tlsSecret:
    name: example.com
```

I get the following error 
```
Error (obtaining tlsSecret "example.com"."ambassador" (hostnames=["*.example.com"]): acme: Error -> One or more domains had a problem: [*.example.com] [*.example.com] acme: could not determine solvers )
```

**Comment by nbkrause** [comment]
@Seb-SK It does not. At the moment only the HTTP-01 challenge is supported by Ambassador which does not allow wildcards. If we implement the DNS-01 challenge in the future, we will be able to support issuing wildcard certificates via ACME

**Comment by umardx** [comment]
Thanks, @kflynn it works.

```yml
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: mydomain-com
  namespace: ambassador
spec:
  hostname: "*.mydomain.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: mydomain-com-ssl
  requestPolicy:
    insecure:
      action: Route
      additionalPort: 8080
  selector:
    matchLabels:
      unusedHostname=workaround
```
