### ISSUE TITLE
Can't connect with OAuth2 FilterPolicy on Multiple Redis Nodes Environment.

### ISSUE THREAD

**Issue by minho-comcom-ai** [datawire/ambassador#2300]
**Describe the bug**

**To Reproduce**
1. Apply below configs (`Filter`, `FiterPolicy`)
2. Connect `https://ambassador.prod/edge_stack/admin/` and Redirected to Google Login Page
3. Google Login
4. Can't Connect to `https://ambassador.prod/edge_stack/admin/`
 (Partial of Resources can't download with 303 code.)

5. Reduce Redis Node Count to 1
6. Can Connect to `https://ambassador.prod/edge_stack/admin/`

**Expected behavior**
Can Connect.

**Versions (please complete the following information):**
 - Ambassador: 1.1.0
 - Kubernetes environment GKE
 - Version 1.14.8-gke.33

**Additional context**
```yaml
kind: Filter
apiVersion: getambassador.io/v2
metadata:
  name: ambassador-google-oauth2
  namespace: ambassador
  annotations:
    getambassador.io/resource-changed: 'true'
spec:
  OAuth2:
    authorizationURL: 'https://accounts.google.com'
    grantType: AuthorizationCode
    clientURL: 'https://ambassador.prod'
    clientID: REDACTED
    secret: REDACTED
---
kind: FilterPolicy
apiVersion: getambassador.io/v2
metadata:
  name: allow-google-oauth2
  namespace: ambassador
  annotations:
    getambassador.io/resource-changed: 'true'
spec:
  rules:
    - host: ambassador.prod
      path: /edge_stack/*
      filters:
        - name: ambassador-google-oauth2
          onDeny: break
          onAllow: continue
    - host: ambassador.prod
      path: /docs/*
      filters:
        - name: ambassador-google-oauth2
          onDeny: break
          onAllow: continue
    - host: ambassador.prod
      path: /openapi/*
      filters:
        - name: ambassador-google-oauth2
          onDeny: break
          onAllow: continue
```
