### ISSUE TITLE
OOM when loading new resources

### ISSUE THREAD

**Issue by pbabilas** [datawire/ambassador#2303]
**Describe the bug**
When I load new mapping or tlscontext to my ambassador, cpu and ram usage goes to top, and mostly gets OOM at process.
![resources peak](http://q.i-systems.pl/file/4ae8033a.png)
![OOM on node](http://q.i-systems.pl/file/284c8cb6.png)

**To Reproduce**
My configuration is Ambassador API Gateway not Edge Stack
Loaded mappings: 137
Loaded tlscontext: 41
Module loaded:
```yaml
    config:
      enable_http10: true
      envoy_log_type: json
      idle_timeout_ms: 40000
      regex_max_size: 543
      retry_policy:
        num_retries: 2
        retry_on: 5xx
      server_name: cloud-dev-lb
      use_remote_address: true
      xff_num_trusted_hops: 2
```
Pod Limit:
* cpu: 2
* ram: 3gb

**Expected behavior**
Apply mappings shoould not couse ram and cpu peak and OOM.

**Versions**
 - Ambassador: 1.1
 - Kubernetes 1.15.6
