### ISSUE TITLE
Does Ambassador directly support mTLS?

### ISSUE THREAD

**Issue by nerusnayleinad** [datawire/ambassador#2307]
This is NOT a bug, but a simple question. I am not yet sure if Ambassador supports mTLS or not.

According to the documentation,

> To configure mTLS between Ambassador Edge Stack and your upstream services, you need to create a TLSContext with certificates that are signed by the Certificate Authority (CA) of your upstream service.

With this statement, it loos like it does. All I have to do is to create an Ambassador object. But then it jumps to `Istio mTLS` and `Consul mTLS`. So, it takes advantage of other technology mTLS or does it provide this feature?

If it doesn't, I find it not very practical to install Istio (which is quite resource consuming. well, not the latest versions, but still...), for this one feature when Istio itself provides most of the features Ambassador offers.

Also, it confuses me this statement:

> Istio creates and stores its TLS certificates in a form that Ambassador Edge Stack is currently unable to automatically read.

It makes me believe that Ambassador actually delegates mTLS part to Istio, and doesn't have this feature. Otherwise, why to not just create your own secret, with your own certs and mount it to Ambassador container.

**Comment by JoshDaone** [comment]
Not "directly", but you need TLSContext.

The ambassador doc is so confused and I had similar concerns. I tried to modify the manifest manually to include istio-certs in the deployment section like this (version 1.1.0):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    product: aes
  name: ambassador
  namespace: ambassador
spec:
  replicas: 1
  ...
        volumeMounts:
        - mountPath: /tmp/ambassador-pod-info
          name: ambassador-pod-info
        - mountPath: /.config/ambassador
          name: ambassador-edge-stack-secrets
          readOnly: true
        - mountPath: /etc/istiocerts/
          name: istio-certs
          readOnly: true
      restartPolicy: Always
      securityContext:
        runAsUser: 8888
      serviceAccountName: ambassador
      terminationGracePeriodSeconds: 0
      volumes:
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
        name: ambassador-pod-info
      - name: ambassador-edge-stack-secrets
        secret:
          secretName: ambassador-edge-stack
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
```

And you need to create a TLSContext in order to allow ambassador to use the secret.
```
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: istio-upstream
  namespace: ambassador
spec:
  cert_chain_file: /etc/istiocerts/cert-chain.pem
  private_key_file: /etc/istiocerts/key.pem
  cacert_chain_file: /etc/istiocerts/root-cert.pem
  redirect_cleartext_from: 8080
```

**Comment by ppeble** [comment]
Also of note: I recently had a PR land that will hopefully be released in the next version. When you mount the secrets as the docs specify then rotated certs are not picked up by ambassador, requiring a restart of the Ambassador pods. My PR changed to read directly from k8s, hopefully alleviating this: https://github.com/datawire/ambassador/pull/2277

The new format will be:

```yaml
apiVersion: ambassador/v2
kind: TLSContext
name: istio-upstream
secret: istio.ambassador
namespace: ambassador
secret_namespacing: False
```

No more mounting!

We run with strict mTLS in our cluster without issues but it does require the `TLSContext`.

I will be submitting a PR to update to the docs sometime soon once this new functionality lands.
