### ISSUE TITLE
Applying CRDs to install ambassador results in error, unable to install

### ISSUE THREAD

**Issue by jdevalk2** [datawire/ambassador#2308]
Installing ambassador into new Kubernetes cluster, there is an error

Error from server (Invalid): error when creating "https://www.getambassador.io/yaml/ambassador/ambassador-crds.yaml": Cu": must match the first version in spec.versions

How to reproduce:

kubectl apply -f https://www.getambassador.io/yaml/ambassador/ambassador-crds.yaml

It is repeated for each CRD.

In commit https://github.com/datawire/ambassador/commit/c756eabce6c783c16feb272c414fd411579c276d#diff-c853c42e9f28e289d79b11dbbf42ae73

It seems the versions have been changed from V1 to V2.

Kubernetes wants the version spec apparently to match the first defined version.

**Comment by richarddli** [comment]
Can you describe your cluster? You may be on an old version of Kubernetes.

**Comment by jdevalk2** [comment]
I have tried this on my local MiniKube 1.6.2 new VM on Hyper-V,  Kubernetes 1.17.0

Also tried it on Azure AKS that version is 1.14, same.

A couple of days ago I installed it from the CRD url and it seemed to work fine, only just now tried it again and got the version mismatch error.

**Comment by jdevalk2** [comment]
@LukeShu Just pulling in the committer of the commit that seems to have introduced the CRD creation error

**Comment by clacsinaRX-M** [comment]
I ran into this issue as well. My workaround was to install the AES CRDs with:

`kubectl apply -f https://www.getambassador.io/yaml/aes-crds.yaml`

Then added `patch`, `create`, and `delete` verbs to the `getambassador.io` apiGroup in the clusterRole:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
rules:
- apiGroups: [""]
  resources: [ "endpoints", "namespaces", "secrets", "services" ]
  verbs: ["get", "list", "watch"]
- apiGroups: [ "getambassador.io" ]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: ["get", "list", "watch"]
- apiGroups: [ "networking.internal.knative.dev" ]
  resources: [ "clusteringresses", "ingresses" ]
  verbs: ["get", "list", "watch"]
- apiGroups: [ "networking.internal.knative.dev" ]
  resources: [ "ingresses/status", "clusteringresses/status" ]
  verbs: ["update"]
- apiGroups: [ "extensions", "networking.k8s.io" ]
  resources: [ "ingresses" ]
  verbs: ["get", "list", "watch"]
- apiGroups: [ "extensions", "networking.k8s.io" ]
  resources: [ "ingresses/status" ]
  verbs: ["update"]
```
