### ISSUE TITLE
FilterPolicy resource on Google Single Sing-on don't redirect scope values to backend services

### ISSUE THREAD

**Issue by huytn1219** [datawire/ambassador#2357]
**Describe the bug**
I'm using Google as an IdP for Single Sign-On for one of my internal web applications. The application needs to retrieve the user's email from Google Oauth in order to identify the currently signed-in user on the server. 

I followed Ambassador's documentation to set up the Oauth client in Google. I also created Oauth Filter, FilterPolicy and apply scope filters on request to my application endpoint. 

I was able to authenticate my application with Google Oauth and obtained the Bearer token from Google. This token would be used to make a call to Google API to retrieve the user's information. 

When I used Bearer token and make a call to  `https://oauth2.googleapis.com/tokeninfo?access_token=<Bearer token>`, Google just returned user ID only which is a part of openid scope. No email or user profile were returned. 

I also checked Ambassador logs and noticed that Ambassador didn't use `email` scope which I added in the FilterPolicy. The only scope that Ambassador used was openid which is the default one.

```
ACCESS [2020-02-27T06:25:06.433Z] "GET /.ambassador/oauth2/redirection-endpoint?state=xxxxxxxxxxxxx:https://mydomain.com/hello&code=xxxxxxxxx&**scope=openid**&authuser=1&prompt=none HTTP/1.1" 303 UAEX 0 0 101 - "10.18.2.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36" "xxxxxxxx" "xxxxxxxxxx" "-"
```

**To Reproduce**
1. Filter's content
    ```
      apiVersion: getambassador.io/v2
      kind: Filter
      metadata:
      name: foobar
      spec:
         OAuth2:
           authorizationURL: https://accounts.google.com
           clientURL: https://example.com
           clientID: xxxxx-xxxxxxx-xxxxxx-xxxxxxx
           secret: xxxxxxxxxxxxxxx-xxxxx
     ```
2. FilterPolicy's content
    ```
     apiVersion: getambassador.io/v2
     kind: FilterPolicy
     metadata:
       name: google-policy
     spec:
        rules:
            - host: "*"
               path: /hello
               filters:
                   - name: foobar
                      arguments:
                           scope:
                           - "email"
                           - "profile"

**Expected behavior**
Use Bearer token from Google Oauth to query user' email and other scopes

**Versions (please complete the following information):**
 - Ambassador: Ambassador Edge Stack
 - Kubernetes environment [Google Kubernetes Engine]
 - Version [1.14.10-gke.17]

**Comment by huytn1219** [comment]
This issue is caused by Google changed its scopes references to full URI instead of just email and profile. 
Change `arguments.scopes` to 
```
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: oauth
spec:
  rules:
    - host: "*"
      path: /backend/debug/
      filters:
      - name: google
        arguments:
          scopes:
          - openid
          - https://www.googleapis.com/auth/userinfo.email
          - https://www.googleapis.com/auth/userinfo.profile
```

Thanks @nbkrause for supporting this issue.
