### ISSUE TITLE
Unable to remove `Server` header

### ISSUE THREAD

**Issue by riker09** [datawire/ambassador#2386]
**Describe the bug**

I cannot remove the `Server` header from the responses.

**To Reproduce**
1. Create the host, service and mapping from the getting started examples
2. Modify the `Mapping`
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: quote-backend
  namespace: volker
spec:
  remove_response_headers:
  - x-envoy-upstream-service-time
  - server
  add_response_headers:
    server: MyServerHeaderValue
  prefix: /backend/
  service: quote
```
3. curl the response with `curl -I https://your-server.org/backend/`
4. See `Server` header is still there
```
HTTP/1.1 200 OK
content-type: application/json
date: Fri, 06 Mar 2020 12:10:01 GMT
content-length: 163
server: envoy
```

**Expected behavior**
Server header value should be `MyServerHeaderValue`

**Versions (please complete the following information):**
 - Ambassador: latest
 - Kubernetes environment: bare metal
 - Version latest

**Additional context**

This is an ongoing issue: https://github.com/datawire/ambassador/issues/307#issuecomment-412501905

**Comment by riker09** [comment]
This is certainly one way to get rid of open issues. Auto-close them by a bot because they were never acknowledged.

I know this is not a super high priority issue, but total neglectance makes me wonder how serious you are about your open source engagement.

**Comment by balixiao** [comment]
@riker09  It looks like Envoy doesn't support removing `server` header from response. But you can use ambassador Module to change the `server` value.

```yaml
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  config:
    server_name: MyServerHeaderValue
```
