### ISSUE TITLE
Make manifests available in kustomize format

### ISSUE THREAD

**Issue by pratikmallya** [datawire/ambassador#2411]
**Please describe your use case / problem.**
[Kustomize](https://kustomize.io/) is a way of organizing k8s manifests in a way that allows using template free manifests. Making ambassador manifests consumable as kustomize manifests would remove duplication of manifests + make it very easy to consume upstream.

**Describe the solution you'd like**
In the k8s/ folder in this repo, have a kustomization base that I can reference in my code repo like so:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/datawire/ambassador/k8s/kustomize/bases
```

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.
