### ISSUE TITLE
unable to define mapping in namespace other than that of ambassador deployment.

### ISSUE THREAD

**Issue by kumarnishant** [datawire/ambassador#242]
I installed ambassador using ambassador-rbac.yaml. 
defined my mapping using 
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  namespace: ixi-hotel
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  hotel
      prefix: /hotels/v1/
      rewrite: /hotels/v1/
      service: hotel-service.ixi-hotel:80
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    service: ambassador
```
curl request to `hotel-service.ixi-hotel` is successful.
curl request to `ambassador.ixi-hotel`  gives Operation timed out.

inside ambassador log i find a cyclic loop in dns resolution phase. 
```
[2018-01-31 12:00:13.231][87][debug][upstream] source/common/upstream/upstream_impl.cc:631] starting async DNS resolution for hotel-service.ixi-hotel
[2018-01-31 12:00:13.232][87][debug][upstream] source/common/upstream/upstream_impl.cc:638] async DNS resolution complete for hotel-service.ixi-hotel
```
it keeps on printing above log infinitely.
if i change namespace of above yaml file to `default` which happens to be namespace of ambassador deployment, every thing works fine.

**Comment by kflynn** [comment]
Did you modify `ambassador-rbac.yaml` to put the `ambassador` deployment into the `ixi-hotel` namespace? It looks like your `ambassador` service isn't in the same namespace as the `ambassador` deployment...

(The DNS resolution messages are normal; Envoy does asynchronous DNS lookups to avoid blocking request handling while DNS completes.)

**Comment by kumarnishant** [comment]
no. i don't want to do so. 
i want to deploy ambassador in one namespace and other part of deployment in different namespace. so that i can logically partition my cluster.

**Comment by kflynn** [comment]
OK, so you need the `ambassador` service in the same namespace as the `ambassador` deployment. It's fine to have the services to which Ambassador is routing be in other namespaces, and it's fine for Ambassador to be in some namespace other than `default`. 

The simplest way forward is likely to change your YAML to deploy the `ambassador` service in `default`, and continue using the annotation there to route to a service in `ixi-hotel`:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  hotel
      prefix: /hotels/v1/
      rewrite: /hotels/v1/
      service: hotel-service.ixi-hotel:80
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    service: ambassador
```

(all I did was remove the `namespace` from that YAML, so that it deploys into `default` like our `ambassador-rbac.yaml` does.)
