### ISSUE TITLE
Swagger ui not shown with prefix, rewrite not working?

### ISSUE THREAD

**Issue by devkws** [datawire/ambassador#2468]
Fresh install of ambassador edge stack via edgectl in a private GKE cluster, with a cloud nat for internet access out.

I have a simple mapping to a service with a swagger ui.

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: users-api
spec:
  prefix: "/users-api/"
  rewrite: "/"
  service: users-api-service.apis.svc.cluster.local:5000
```

With this mapping I simply get a blank page.

With the following mapping, the swagger ui is shown correctly. 

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: users-api
spec:
  prefix: "/"
  service: users-api-service.apis.svc.cluster.local:5000
```

The issue is I need a prefix for the api as we will have multiple services.

Any thoughts?
