### ISSUE TITLE
Ambassador is not able to start if a TLSContext is using an invalid certificate.

### ISSUE THREAD

**Issue by knlambert** [datawire/ambassador#2479]
**Describe the bug**
Ambassador is not able to restart if a mapping is using an invalid certificate.

![image](https://user-images.githubusercontent.com/16439060/77387269-5a284580-6d63-11ea-9eb0-728a4f459133.png)

**To Reproduce**

1. Create a secret certificate 

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: my-certificate
data:
  tls.crt: <some crt>
  tls.key: <some key with a typo>
```

2. Create a TLSContext mapping with a service : 

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v2
      kind:  Mapping
      ambassador_id: production
      name:  my-service-mapping
      prefix: "/"
      service: my-service.default.svc.cluster.local
      host: my-service.example.com
      ---
      apiVersion: ambassador/v2
      kind: TLSContext
      ambassador_id: production
      name: my-service-tls-context
      hosts:
        - my-service.example.com
      secret: my-certificate.default

```
3. Make ambassador scale up or down, or just kill a pod.
4. It won't be able to start.

**Expected behavior**
In a shared ecosystem, ambassador should not fail to start because a user set a wrong certificate. The whole cluster is impacted.

**Versions (please complete the following information):**
 - Ambassador: 1.2.2
 - Google Kubernetes Engine
 - 1.14
