### ISSUE TITLE
Defining a Host Resource Inside the Service YAML Doesn't Use the Appropriate Certificate

### ISSUE THREAD

**Issue by jocortems** [datawire/ambassador#2501]
**Describe the bug**
When defining a `Host` resource as part of a service definition YAML as follows:

```
apiVersion: v1
kind: Service
metadata:
  name: ambassador-frontend
  namespace: conexp
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: frontend-mapping
      service: ambassador-frontend
      host: ambassador-frontend.srinipadala.xyz
      prefix: /
      add_linkerd_headers: true
      ---
      apiVersion: ambassador/v2
      kind: Host
      name: frontend-host
      hostname: ambassador-frontend.srinipadala.xyz
      acmeProvider:
        email: valid@email.com
        authority: https://acme-staging-v02.api.letsencrypt.org/directory
      tlsSecret:
        name: frontend-secret
  labels:
    app: conexp-frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: conexp-frontend
```
And browsing to the site Ambassador will use the default built in certificate. If the `Host` resource is created as a standalone resource then Ambassador will honor the certificate:

```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: ambassador-frontend
  namespace: conexp
spec:
  hostname: ambassador-frontend.srinipadala.xyz
  acmeProvider:
    email: valid@email.com
    authority: https://acme-staging-v02.api.letsencrypt.org/directory
  tlsSecret:
    name: ambassador-frontend
```
**To Reproduce**
1. Create a Service definition and under it create the corresponding `Mapping` and `Host` resources
2. Apply the YAML file
3. Browse to the URL defined in the `Mapping` resource
4. You will receive an invalid certificate warning, open the certificate, Ambassador is presenting its built in certificate

**Expected behavior**
Regardless of whether the `Host` resource is embedded in the `Service` definition manifest or as a standalone resource, it should configure ambassador with the correct certificate

**Versions (please complete the following information):**
 - Ambassador: 1.3.1
 - Kubernetes environment: Azure Kubernetes Service
 - Version: 1.14.8
