### ISSUE TITLE
Issue with setting up cleartext host

### ISSUE THREAD

**Issue by joe-zhang3** [datawire/ambassador#2629]
**Describe the bug**

Environment: SSL termination at LB, LB sends http request to Ambassador. 
Follow https://www.getambassador.io/docs/1.3/topics/running/tls/cleartext-redirection/#cleartext-routing to create a host accepts cleartext

```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: example-host
spec:
  hostname: host.example.com
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
```

But it does not work - ambassador still response me a 301 and redirect my http request to https. e.g. http://hostname/docs/ - the built in mapping. 

**Expected behavior**
Ambassador should respect the host entry and server the http request correctly.

**Versions (please complete the following information):**
- Helm Chart: 6.3.1
 - Ambassador: aes 1.4.1 [e.g. 0.32.1]
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Rancher Version 2.2.8 [e.g. 1.8.1]

**Additional context**

**Comment by joe-zhang3** [comment]
The root cause is:
I accidentally set the `env.AMBASSADOR_ID` in my script, which makes a bunch of resources are created with `ambassador_id` entry added, like below:

```yaml
{{ if and .Values.authService.create .Values.enableAES }}
---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: {{ include "ambassador.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    app.kubernetes.io/component: {{ include "ambassador.name" . }}-auth
    product: aes
spec:
  proto: grpc
  {{- if .Values.env }}
  {{- if hasKey .Values.env "AMBASSADOR_ID" }}
  ambassador_id: {{ .Values.env.AMBASSADOR_ID | quote }}
  {{- end }}
  {{- end }}
  auth_service: 127.0.0.1:8500
  {{- if .Values.authService.optional_configurations }}
  {{- toYaml .Values.authService.optional_configurations | nindent 2}}
  {{- end }}
{{ end }}
```
But it is not mentioned in the doc (https://www.getambassador.io/docs/1.3/topics/running/tls/cleartext-redirection/#cleartext-routing), I added the `ambassador_id` to the host yaml and re-apply it and the problem is gone.
