### ISSUE TITLE
Cli command to validate minor errors in Ambassador config

### ISSUE THREAD

**Issue by lavoiedn** [datawire/ambassador#272]
Trying to validate that there was no error in our Ambassador configuration for automated pipelines, we realized that there was currently no way (that I could find!) to use the ambassador cli to exit on configuration errors. `ambassador config` would log an error and ignore configurations with minor errors, such as an extra invalid property.

An example configuration that was successful with invalid annotations is this altered qotm:

```
---
apiVersion: v1
kind: Service
metadata:
  name: qotm
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  qotm_mapping
      prefix: /qotm/
      service: qotm
      invalidField: true
spec:
  type: ClusterIP
  selector:
    app: qotm
  ports:
  - port: 80
    name: http-qotm
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qotm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qotm
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:1.1
        ports:
        - name: http-api
          containerPort: 5000
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
```
