### ISSUE TITLE
Stress testing question - pretty slow comparing to stock k8s deployment/service

### ISSUE THREAD

**Issue by des-esseintes** [datawire/ambassador#2762]
Hello community!

Not a bug report actually, rather a question.

So I've made a fresh install of Ambassador in local minikube, made a test nginx deployment with static index.html and started testing it.
Maybe I'm doing something wrong, but the results are pretty weird.

Raw Deployment/Service shows the following:

```
$ hey -z 30s -c 3000 http://10.107.230.32
...
Status code distribution:
  [200] 699928 responses
```
but  with Ambassador I get the following:
```
$ hey -z 30s -c 3000 http://10.110.252.12.xip.io/backend/
...
Status code distribution:
  [200] 24385 responses
  [504] 65113 responses
```

I thought Envoy's Circuit Breaker settings were to blame and raised them slightly:
```
    circuit_breakers:
    - max_connections: 8192
      max_pending_requests: 8192
      max_requests: 8192
      priority: high
```

this did not affect the performance, sadly.

what could be the reason and what can I do to fix it? Just curious.

Thanks!
