### ISSUE TITLE
Unable to add Host CRD hostname with * on Ambassador Edge Stack

### ISSUE THREAD

**Issue by Sbou** [datawire/ambassador#2827]
Hi,

I have the same issue than this other ticket #2284. This one has been closed with a workaround but it doesn't work for me.

```
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: myhost-host
  namespace: ambassador
spec:
  hostname: "*.myhost.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-cert
  selector:
    matchLabels:
      host: myhost-host-wildcard
```

This works fine when ambassador is already fully started. Ambassador will pick up the host config and applies it. However when pods are being restarted they are unable to start with the following error

kubernetes:secret|ambassador|*|host=myhost-host-wildcard,hostname=*.myhost.com: ERROR: WORKER PANICKED: unable to parse requirement: invalid label value: "*.myhost.com": at key: "hostname": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

I'm using following versions:

Ambassador Edge Stack helm chart v6.4.4
Ambassador Edge Stack image v1.5.2
Azure AKS with Kubernetes v1.16.9
