### ISSUE TITLE
Issue matching Multiple Hosts and TLSContexts including a Wildcard

### ISSUE THREAD

**Issue by jonhoare** [datawire/ambassador#2832]
**Describe the bug**
I have a single Host, which is a Wildcard Subdomain, with a matching TLSContext to serve a Wildcard Certificate.
This setup has worked for me for a year or so.
Example:
Host: `"*.myapp.com"`
Cert: `"*.myapp.com"`

I now need to add another Host to a specific Domain (Which would also match the Wildcard Host) but I need this to apply a specific Certificate...
Example:
Host: `"client-a.myapp.com"`
Cert: `"client-a.myapp.com"`

When I configure a mapping for `client-a.myapp.com`, and attempt to hit the endpoint, Ambassador is unable to match a cluster and I am returned a 404.

**To Reproduce**
```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: myapp
spec:
  hostname: "*.myapp.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: wildcard-myapp-cert
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: myapp-context
spec:
  secret: wildcard-myapp-cert
  hosts:
    - "*.myapp.com"
  redirect_cleartext_from: 8080
  min_tls_version: v1.2
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: myapp-client-a
spec:
  hostname: client-a.myapp.com
  acmeProvider:
    authority: none
  tlsSecret:
    name: myapp-client-a-cert
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: myapp-client-a-context
spec:
  secret: myapp-client-a-cert
  hosts:
    - "client-a.myapp.com"
  redirect_cleartext_from: 8080
  min_tls_version: v1.2
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: service-1-mapping
spec:
  host: example.myapp.com # Should route using the *.myapp.com Host with the wildcard-myapp-cert TLS Certificate
  prefix: /service1
  service: https://service1
  timeout_ms: 30000
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: service-2-mapping
spec:
  host: example.myapp.com # Should route using the *.myapp.com Host with the wildcard-myapp-cert TLS Certificate
  prefix: /service2
  service: https://service2
  timeout_ms: 30000
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: service-3-mapping
spec:
  host: another-example.myapp.com # Should route using the *.myapp.com Host with the wildcard-myapp-cert TLS Certificate
  prefix: /
  service: https://service3
  timeout_ms: 30000
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: client-a-mapping
spec:
  host: client-a.myapp.com # Should route using the client-a.myapp.com Host with the myapp-client-a-cert TLS Certificate
  prefix: /
  service: https://client-a-service
  timeout_ms: 30000
```

**Expected behavior**
https://example.myapp.com/service1/ - Routes ok to https://service1 using the *.myapp.com Host applying the wildcard-myapp-cert
https://example.myapp.com/service2/ - Routes ok to https://service2 using the *.myapp.com Host applying the wildcard-myapp-cert
https://another-example.myapp.com/ - Routes ok to https://service3 using the *.myapp.com Host applying the wildcard-myapp-cert
https://client-a.myapp.com/ - Returns 404... Expected this to route to https://client-a-service using the client-a.myapp.com Host (Not the Wildcard Host) and apply the myapp-client-a-cert

**Debug Logs from Ambassador**
```
[2020-06-29 09:59:58.405][195][debug][http] [source/common/http/conn_manager_impl.cc:781] [C200698][S199400155347038866] request headers complete (end_stream=true):
':authority', 'client-a.myapp.com'
':path', '/'
':method', 'GET'
'connection', 'keep-alive'
'cache-control', 'max-age=0'
'upgrade-insecure-requests', '1'
'user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'
'accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
'sec-fetch-site', 'cross-site'
'sec-fetch-mode', 'navigate'
'sec-fetch-user', '?1'
'sec-fetch-dest', 'document'
'accept-encoding', 'gzip, deflate, br'
'accept-language', 'en-US,en;q=0.9'
[2020-06-29 09:59:58.405][195][debug][http] [source/common/http/conn_manager_impl.cc:1333] [C200698][S199400155347038866] request end stream
[2020-06-29 09:59:58.406][195][debug][router] [source/common/router/router.cc:415] [C200698][S199400155347038866] no cluster match for URL '/'
[2020-06-29 09:59:58.406][195][debug][http] [source/common/http/conn_manager_impl.cc:1475] [C200698][S199400155347038866] Sending local reply with details route_not_found
[2020-06-29 09:59:58.406][195][debug][http] [source/common/http/conn_manager_impl.cc:1706] [C200698][S199400155347038866] encoding headers via codec (end_stream=true):
':status', '404'
```

**Versions (please complete the following information):**
 - Ambassador: 1.5.3
 - Kubernetes environment: AKS 
 - Version 1.16.7

**Additional context**
```
[Envoy Routes]
{
    "match": {
        "case_sensitive": true,
        "headers": [
            {
                "exact_match": "myapp-client-a.myeapp.com",
                "name": ":authority"
            }
        ],
        "prefix": "/",
        "runtime_fraction": {
            "default_value": {
                "denominator": "HUNDRED",
                "numerator": 100
            },
            "runtime_key": "routing.traffic_shift.cluster_https___client_a_service_otls"
        }
    },
    "per_filter_config": {
        "envoy.ext_authz": {
            "disabled": true
        }
    },
    "route": {
        "cluster": "cluster_https___client_a_service_otls",
        "prefix_rewrite": "/",
        "priority": null,
        "timeout": "30.000s"
    }
}
[Envoy Clusters]
{
    "connect_timeout": "3.000s",
    "dns_lookup_family": "V4_ONLY",
    "lb_policy": "ROUND_ROBIN",
    "load_assignment": {
        "cluster_name": "cluster_https___client_a_service_otls",
        "endpoints": [
            {
                "lb_endpoints": [
                    {
                        "endpoint": {
                            "address": {
                                "socket_address": {
                                    "address": "client-a-service",
                                    "port_value": 443,
                                    "protocol": "TCP"
                                }
                            }
                        }
                    }
                ]
            }
        ]
    },
    "name": "cluster_https___client_a_service_otls",
    "transport_socket": {
        "name": "envoy.transport_sockets.tls",
        "typed_config": {
            "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext",
            "common_tls_context": {}
        }
    },
    "type": "STRICT_DNS"
}
```

If I remove the myapp-client-a Host and myapp-client-a-context TLSContext then the mapping for https://client-a.myapp.com/ works, but as it then matches the Wildcard Host, the Wildcard TLS is applied, which is not what I want in this case.

If I remove the myapp Host and myapp-client-a-cert TLSContext, then the mapping for https://client-a.myapp.com/ works as expected, but the other existing mappings which should rely on the Wildcard Host/TLS do not work.

I would have expected that I should be able to specify a Wildcard Host and TLSContext alongside a specific defined Host/TLSContext, which would be attempted to match first, falling back to the Wildcard Host if not?

I have attempted to update my mapping to use a host regex...
```
host_regex: true
host: '^client-a\\.myapp\\.com$'
```
This mapping now at least allows me to route to the correct upstream service, but I am being served the incorrect, Wildcard, certificate still.
