### ISSUE TITLE
circuit-breakers not working?

### ISSUE THREAD

**Issue by mmoghadas** [datawire/ambassador#2833]
**Describe the bug**
We're attempting to use Circut Breaker (https://www.getambassador.io/docs/latest/topics/using/circuit-breakers/) to control connections to service but seems like the setting is completely ignored. 

**To Reproduce**
1. Our configuration:
```
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: service123-backend
  namespace: service123
spec:
  prefix: /
  service: dev1-service123.service123:8070
  timeout_ms: 120000
  resolver: resolver1
  add_response_headers:
    Strict-Transport-Security: max-age=31536000;  includeSubDomains
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    X-XSS-Protection: 1; mode=block
  circuit_breakers:
  - max_connections: 1
    max_pending_requests: 1
    max_requests: 1
    priority: high
```

2. Deploy above mapping
3. Generate some traffic to service

**Expected behavior**
I would expect the connection would be limited to only 1, but doesn't' seem to be the case. 

**Versions (please complete the following information):**
 - Ambassador: 1.4.2
 - Kubernetes environment EKS
 - Version 1.5

**Additional context**
n/a
