### ISSUE TITLE
Using includeSubdomains: true in a Filter causes crash in Ambassador 1.5.4

### ISSUE THREAD

**Issue by Lemmons** [datawire/ambassador#2845]
**Describe the bug**
Using `includeSubdomains: true` in a `Filter` causes ambassador to crash at startup, or to raise an error when the `Filter` is added.

**To Reproduce**
1. Apply a `Filter` with `includeSubdomains: true` set for one of its `spec.OAuth2.protectedOrigins`
2. Check logs for error or attempt to access a site included as part of the `Filter`

**Expected behavior**
The `Filter` should not error and should properly protect subdomains as expected.

**Versions (please complete the following information):**
 - Ambassador: 1.5.4
 - Kubernetes environment: EKS
 - Version: 1.14

**Additional context**
Here is the `Filter` which causes issues:
```
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: my-test
spec:
  OAuth2:
    authorizationURL: https://cognito-idp.us-east-1.amazonaws.com/{sensitive}
    clientID: {sensitive}
    secret: {sensitive}
    protectedOrigins:
      - origin: https://my-test.{sensitive}
        includeSubdomains: true
```
Removing `includeSubdomains: true`, as shown below, allows the `Filter` to apply correctly and start working.
```
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: my-test
spec:
  OAuth2:
    authorizationURL: https://cognito-idp.us-east-1.amazonaws.com/{sensitive}
    clientID: {sensitive}
    secret: {sensitive}
    protectedOrigins:
      - origin: https://my-test.{sensitive}
```

gz#453

**Comment by nbkrause** [comment]
@Lemmons Thank you for reporting this.

This is a bug that appears to be introduced in 1.5.3 with the `internalOrigin` addition to the `protectedOrigins` field.

The workaround for it is to manually set `internalOrigin` to the `origin` configured with `includeSubdomains: true` set.

```
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: my-test
spec:
  OAuth2:
    authorizationURL: https://cognito-idp.us-east-1.amazonaws.com/{sensitive}
    clientID: {sensitive}
    secret: {sensitive}
    protectedOrigins:
      - origin: https://my-test.{sensitive}
        internalOrigin: https://my-test.{sensitive}
        includeSubdomains: true
```

We apologize for this issue and are working to resolve it. Thanks again for reporting it!
