### ISSUE TITLE
AuthService plugin is not respecting CRD updates

### ISSUE THREAD

**Issue by jcwilson** [datawire/ambassador#2862]
**Describe the bug**
With some frequency, but not 100%, I have noticed that updates to my custom `AuthService` resource are not reflected in the EPC Plugins view and the actual `AuthService` behavior is not updated either.

**To Reproduce**
Unclear, but at some point the `AuthService` plugin (or maybe Ambassador itself?) gets into a bad state. 

I started with this very basic definition (after having configured Ambassador not to create its own default AuthService and RateLimiting plugins), where `edge-jwt-validation` points to a functional internal service:
```
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: edge-jwt-validation
```

I was attempting to add CORS support to my `Ambassador` module which requires some extra headers to be passed to the `auth_service` for OPTIONS requests. I added these to the `AuthService` resource definition:
```
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: edge-jwt-validation
  allowed_request_headers:
  - "origin"
  - "access-control-request-method"
```

Here is what the EPC shows (which is as expected): 
![image](https://user-images.githubusercontent.com/629874/87278624-c9a07d00-c499-11ea-9ee8-015f590060e3.png)

However, those headers are still not being passed along to my `auth_service`.

Having encountered similar behavior before, I decided to explore a bit. I deleted the `AuthService` resource and sent a few test queries. Strangely, they were still being forwarded to my internal `edge-jwt-validation` service (and still returning 401s due to the missing headers). No requests were actually hitting the intended API service yet, as they weren't getting past the `AuthService` check. This is really bizarre since the `AuthService` no longer exists in the cluster at this point, according to `kubectl`.

I then recreated the `AuthService` with a different internal service target (`edge-echo`):
```
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: edge-echo
  allowed_request_headers:
  - "origin"
  - "access-control-request-method"
```

But then observed this in the EPC (notice the mismatched "service url:"): 
![image](https://user-images.githubusercontent.com/629874/87278935-990d1300-c49a-11ea-9666-c6df6dab4321.png)

The request behavior remained consistent with the above description. No requests are arriving at the `edge-echo` service (the intended API target and now being asked to pull double-duty as the auth service).

Finally, I deleted that `AuthService` and attempted to create a new one with the same values except for a different name. It appears to be present and correct with `kubectl` but it does not appear in the EPC. Only by deleting that resource and creating it again with the original name will it appear in EPC again.

I have no idea how to resolve this state other than reinstalling Ambassador. This is sub-optimal because doing so decommissions the existing ELB and provisions a new one, which engenders a remapping of a DNS hostname (and eventually multiple hostnames in production).

**Expected behavior**
I would expect the `AuthService` settings and behavior to reflect the latest applied configuration within a short amount of time and route requests correctly and with the expected allowed headers.

Thanks for any help or guidance in this matter.

**Versions (please complete the following information):**
 - Ambassador: 1.5.5
 - Kubernetes environment: Self-hosted in AWS, v1.15.6
