### ISSUE TITLE
Mapping with `https` scheme for service fails error check

### ISSUE THREAD

**Issue by manigandham** [datawire/ambassador#2875]
Ambassador 1.6.0 with mapping like this:

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: backoffice
spec:
  host: backoffice.example.com
  prefix: /
  timeout_ms: 600000
  service: https://backoffice:443
```

Fails with error:
```
cluster_https_default___backoffice_443_default: service https.default://backoffice:443 has unknown scheme https.default, assuming HTTP
```

This happens if there is any scheme in the address. Removing the scheme eliminates the error but defaults to HTTP.

I'm not very familiar with Python but looks like this line is the problem (running the if statement every time)? https://github.com/datawire/ambassador/blob/f4423e55ef389ba035d138ff6df5e6204c47500a/python/ambassador/ir/ircluster.py#L143
