### ISSUE TITLE
Error with Mapping using `resolver: consul` in non `AMBASSADOR_NAMESPACE` namespace

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#2881]
**Describe the bug**
A `Mapping` that sets `resolver: consul` in a namespace other than `AMBASSADOR_NAMESPACE` is rejected with error message: 

```
2020-07-23 14:32:05 diagd 1.6.0 [P60TAEW] INFO: error mapping.namespace.1 The Consul resolver does not allow dots in service names
```

It is still rendering the configuration in the snapshot correctly but Ambassador is rejecting the configuration because of the `.namespace` appending to the end of the `service` in the `Mapping`.

```
    "Consul": {
        "Endpoints": {
            "web-svc-sidecar-proxy": {
                "Id": "dc1",
                "Service": "web-svc-sidecar-proxy",
                "Endpoints": [
                    {
                        "SystemID": "consul::9bed6a5b-f33a-b432-0291-0dfe9dc57090",
                        "ID": "web-69d7545f4d-p4bnl-web-svc-sidecar-proxy",
                        "Service": "web-svc-sidecar-proxy",
                        "Address": "10.244.0.45",
                        "Port": 20000,
                        "Tags": []
                    }
                ]
            }
        }
    },
```

Moving the `Mapping` to `AMBASSADOR_NAMESPACE` stops the `.namespace` from being appended to the `service` and resolves the issue.

**To Reproduce**
1.  Deploy Ambassador 1.6 in any kubernetes cluster
 
2. Install consul

   ```
   $ helm repo add hashicorp https://helm.releases.hashicorp.com
  
   $ cat <<EOF | helm install consul hashicorp/consul -f -
   global:
     name: consul
   server:
     replicas: 1
     bootstrapExpect: 1
   connectInject:
     enabled: true
     default: true
   EOF
   ```

3. Install the quote app

   ```
   kubectl apply -f https://getambassador.io/yaml/backends/quote.yaml
   ```

   This will be automatically meshed.

4. Create the `ConsulResolver`
   
   ```
   ---
   apiVersion: getambassador.io/v2
   kind: ConsulResolver
   metadata:
     name: consul-dc1
     namespace: ambassador
   spec:
     address: consul-server.consul.svc.cluster.local:8500
     datacenter: dc1
   ```

5. Create the `Mapping` with `resolver: consul-dc1` to try and connect to the `sidecar-proxy`

   ```
   ---
   apiVersion: getambassador.io/v2
   kind: Mapping
   metadata:
     name: quote-sidecar
     namespace: default
   spec:
     prefix: /
     service: quote-sidecar-proxy
     resolver: consul-dc1
     load_balancer:
       policy: round_robin
   ```

6. Check the logs to see `quote-sidecar.default` is rejected

7. Delete that Mapping and install the following with `namespace: ambassador`

   ```
   ---
   apiVersion: getambassador.io/v2
   kind: Mapping
   metadata:
     name: quote-sidecar
     namespace: ambassador
   spec:
     prefix: /
     service: quote-sidecar-proxy
     resolver: consul-dc1
     load_balancer:
       policy: round_robin
   ```

9. See that it works
