### ISSUE TITLE
Adding CORS configuration while using EXT Auth service does not resolve CORS issue

### ISSUE THREAD

**Issue by sai3010** [datawire/ambassador#2886]
I'm running 2 Kubernetes clusters with ambassador edge stack. One cluster does not use any Auth Service so setting CORS configuration by following the instructions here: **https://www.getambassador.io/docs/latest/topics/using/cors/** resolved the CORS issue.
But in the cluster where I have external auth enabled using the same configuration does not seem to work there. My external Auth code is CORS enabled and works fine when tested separately but when the request is passed through the gateway I still get the CORS issue. I'm attaching my YAML configurations and other details below, Please suggest a way through this.
**Ambassador Edge Stzack version: 1.4.3**

**Auth service config**
```
---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: auth
spec:
  auth_service: "authentication-svc:80" # required
  proto: http      
  path_prefix: "/auth"                 # optional; default is "http"
  timeout_ms: 5000                  # optional; default is 5000
  #allow_request_body: true         # deprecated; use include_body instead
  status_on_error:                  # optional
    code: 503                         # optional; default is 403
  failure_mode_allow: false         # optional; default is false
  # the following are used only if `proto: http`; they are ignored if `proto: grpc`
  allowed_request_headers:         # optional; default is []
  - "*"
```

**Auth Mapping**

```
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  authmapping
spec:
  prefix: /auth/
  rewrite: /auth/
  service: authentication
  cors:
    origins: "*"
    methods: POST, GET , OPTIONS
    headers: "*"
    credentials: true
    exposed_headers: "*"
  timeout_ms: 30000
  idle_timeout_ms: 500000
  connect_timeout_ms: 30000
---
```
