### ISSUE TITLE
MicroCD/Projects does not work OOTB with `edgectl install`.

### ISSUE THREAD

**Issue by cakuros** [datawire/ambassador#2889]
## Background/Summary

When following the `edgectl install` process and adding `projects.yaml`, navigating to the projects tab in the EPC shows a service-accounts permissions error.  It is likely that the RBAC portions for Projects are not being correctly created during this process.

## Issue/Request

Running `kubectl apply -f https://getambassador.io/yaml/projects.yaml` should work without errors after running edgectl install.

## Replicator

A step-by-step replicator for the issue. Start with how and where to install Ambassador and end with the manifestation of the bug.

1. Kubernetes cluster info
   * 1.16
   * GKE

2. Ambassador install info
   * Ambassador version 1.6.0 via `edgectl install`.
   * Edgectl version 1.6.0

3. Ambassador configuration
   * `kubectl apply -f https://getambassador.io/yaml/projects.yaml`
   * Single AES deployment

4. Example request that shows the replication
   1. Run `edgectl install` on fresh cluster
   2. Run `kubectl apply -f https://getambassador.io/yaml/projects.yaml`
   3. Run `edgectl login -n ambassador {{AMBASSADOR_HOST}}

![Screenshot from 2020-07-22 12-28-15](https://user-images.githubusercontent.com/63562580/88557849-c14b5480-cff8-11ea-9e4d-17c685fe9bc7.png)

## Notes

Need to check and see if this can be resolved by applying the correct `ClusterRole` and `ClusterRoleBinding` to the service-account.  Will report back after checking.

gz#457

**Comment by cakuros** [comment]
Need to add rbac and restart the Ambassador pod.
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador-projects
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-6.5.1
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/managed-by: Helm
    product: aes
rules:
- apiGroups: [""]
  resources: [ "secrets", "services" ]
  verbs: [ "get", "list", "create", "patch", "delete", "watch" ]
- apiGroups: ["apps"]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "create", "patch", "delete", "watch" ]
- apiGroups: ["batch"]
  resources: [ "jobs" ]
  verbs: [ "get", "list", "create", "patch", "delete", "watch" ]
- apiGroups: [""]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [""]
  resources: [ "pods/log" ]
  verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador-projects
  namespace: ambassador
  labels:
    app.kubernetes.io/name: ambassador
    app.kubernetes.io/part-of: ambassador
    helm.sh/chart: ambassador-6.5.1
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/managed-by: Helm
    product: aes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador-projects
subjects:
  - name: ambassador
    namespace: ambassador
    kind: ServiceAccount
```
