### ISSUE TITLE
Automatic redirect from HTTP to HTTPS not working

### ISSUE THREAD

**Issue by henrikengelbrink** [datawire/ambassador#2894]
**Describe the bug**
I configured the ambassador CRD's and expected that all HTTP requests will be automatically redirected to HTTPS. HTTPS is working fine and I can see the page, but with HTTP, it is returning a 404 error (not found).

This is the config I'm currently using:

```yml
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: example-de-host
  namespace: default
spec:
  hostname: example.de
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
  acmeProvider:
    authority: 'https://acme-v02.api.letsencrypt.org/directory'
    email: dev@example.de
  tlsSecret:
    name: example-de-tls
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: example-de-host-context
spec:
  hosts:
    - example.de
  secret: example-de-tls
  min_tls_version: v1.2
  cipher_suites:
    - "[TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]"
    - "[TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256]"
    - "[TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  landing-mapping
  namespace: default
spec:
  prefix: /
  host: example.de
  service: landing-page:80
  add_response_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

**Expected behavior**
I expected that all incoming requests will be redirected to HTTPS, but instead I get an 404 (not found) on a request to HTTP.

**Versions (please complete the following information):**
 - Ambassador: 1.6.0
 - Kubernetes environment DigitalOcean Managed Kubernetes (DOKS)
 - Version 1.18.6-do.0

**Comment by henrikengelbrink** [comment]
Adding the `requestPolicy` to the `Host` CRD fixed the issue.

```yml
...
spec:
  hostname: example.de
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
...
```
