### ISSUE TITLE
TCP logging is not there on ambassador

### ISSUE THREAD

**Issue by kannanvr** [datawire/ambassador#2941]
**Describe the bug**
 When we have configured HTTP/HTTPS, we can see all the logs related to the incoming connection on ambassador pod.
But For TCP connection, we could not get the logs at all.

**To Reproduce**
   Folowing is my ambassador deployment container yaml
```
      - name: ambassador
        image: quay.io/datawire/ambassador:1.3.0
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_LOG_LEVEL
          value: trace
        - name: AES_LOG_LEVEL
          value: trace
        - name: SCOUT_DISABLE
          value: "1"
```
I have enabled AES_LOG_LEVEL and APP_LOG_LEVEL. But when i am adding the TCPMAPPING on a annotations of service , TCP connection is working fine. But We need logs to debug the connection.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TCPMapping
      name: postgres-1
      port: 5633
      service: postges-ingress.postges1:5432

```
We are expecting the TCP log when we establish the TCP connection through Ambassador

**Expected behavior**
We are expecting the TCP log when we establish the TCP connection through Ambassador

**Versions (please complete the following information):**
 - Ambassador: 1.3.0
- Kubernetes Version 1.15.3

**Comment by cakuros** [comment]
So, I tested a bit with a `TCPMapping` that looks like this:
```
---
apiVersion: getambassador.io/v2
kind: TCPMapping
metadata:
  name: default-test
spec:
  port: 2222
  service: quote:80
```

I was finding in my logs (I have set to debug) that there are entries that look like this:
```
time="2020-09-16 16:11:58" level=debug msg="[gRPC] HTTP/1.1 GET admin.REDACTED.net /backend/" func="github.com/datawire/apro/cmd/amb-sidecar/filters/handler.(*FilterMux).Filter" file="github.com/datawire/apro/cmd/amb-sidecar/filters/handler/handler.go:108" MAIN=http REQUEST_ID=15892106509584408014 SUB=http-handler
time="2020-09-16 16:11:58" level=debug msg="[gRPC] *filterapi.HTTPRequestModification : 0 headers (124.374µs)" func=github.com/datawire/apro/cmd/amb-sidecar/filters/handler.logResponse file="github.com/datawire/apro/cmd/amb-sidecar/filters/handler/handler.go:68" MAIN=http REQUEST_ID=15892106509584408014 SUB=http-handler
```
that were corresponding to the requests I was sending via `curl https://admin.REDACTED.net:2222`
