### ISSUE TITLE
The ambassador pod loses the model parameter after unexpected restart, causing grpc access failure

### ISSUE THREAD

**Issue by niaiwomattt** [datawire/ambassador#2946]
**Describe the bug**

The ambassador pod loses the model parameter after unexpected restart, causing grpc access failure

**To Reproduce**
1. kill envoy process, force ambassador to restart
2. Access to grpc web interface, error of `Http response at 400 or 500 level`, network message:`Status Code: 503 Service Unavailable`, response message:`upstream connect error or disconnect/reset before headers. reset reason: remote reset`
3. After executing `kubectl apply -f ambassador-model.yaml` again, grpc web resumes access

**Expected behavior**
After ambassador restarts, the model configuration is not lost, grpc is still available

**Versions (please complete the following information):**
 - Ambassador: 1.6.2
 - Kubernetes environment: k3s
 - Version: v1.18.8+k3s1

**Additional context**

**Comment by niaiwomattt** [comment]
k3s event message: `MountVolume.SetUp failed for volume "ambassador-token-v8wl8": secret "ambassador-token-v8wl8" not found`

Even if the pod does not restart, ambassador will lose the model configuration, which happened more than a dozen times a day

**Comment by niaiwomattt** [comment]
```yaml
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    enable_grpc_web: true
    enable_grpc_http11_bridge: false
    enable_http10: false
    diagnostics:
      enabled: true
    cors:
      origins: "*"
      methods: GET, PUT, DELETE, POST, OPTIONS
      headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
      max_age: "1728000"
      exposed_headers: custom-header-1,grpc-status,grpc-message
      credentials: true
```
This is the module configuration file
