### ISSUE TITLE
The `envoy_log_type: json` parameter doesn't work - access logs are always in text format

### ISSUE THREAD

**Issue by ovk** [datawire/ambassador#2960]
The #1666 PR added support for Envoy access logs in JSON format. However, this doesn't seem to be working: the access logs are always in text format, regardless of the `envoy_log_type` setting.

**To Reproduce**
1. Install Ambassador (in single namespace mode) and add some mapping.
2. Create Ambassador Module with the following config:

```yaml
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador-config
  namespace: example
spec:
  ambassador_id: example
  config:
    envoy_log_type: json
```

3. Restart Ambassador, to ensure it picks up config from the Module.
4. Send some HTTP requests to the mapping, notice access logs are still in text format and not JSON.

**Expected behavior**

Access logs should be in JSON format when `envoy_log_type` is set to `json`, according to [this documentation](https://www.getambassador.io/docs/latest/howtos/tracing-datadog/#2-configure-envoy-json-logging) for example.

**Additional Info**

I added some logs before this line https://github.com/datawire/ambassador/blob/master/python/ambassador/envoy/v2/v2listener.py#L731 to print the value of `self.config.ir.ambassador_module.envoy_log_type.lower()` and it is indeed always set to `text` regardless of the Module configuration.

**Versions:**
 - Ambassador: 1.7.0 OSS
 - Kubernetes environment: Minikube and bare metal
 - Version: 1.16.8

**Comment by concaf** [comment]
@ovk the `Module` needs to be named `ambassador` for configuration to take effect. Can you try that -
```yaml
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: example
spec:
  ambassador_id: example
  config:
    envoy_log_type: json
```
