### ISSUE TITLE
cors mapping doesnt work with filters

### ISSUE THREAD

**Issue by Yavin** [datawire/ambassador#2962]
**Describe the bug**
When filter is specified then CORS specified for mapping doesn't work. As I understand filters are applied before mapping, but I didn't found any method for filter/policy to pass OPTIONS request.

**To Reproduce**
I have mapping and OIDC filter specified together for a service
```
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: api-filter-policy
spec:
  rules:
    - host: api.example.com
      path: "*"
      filters:
        - name: api-filter
```
```
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: api-filter
spec:
  OAuth2:
    authorizationURL: "https://keycloak.example.com/auth/realms/api"
    grantType: "AuthorizationCode"
    protectedOrigins:
      - origin: "https://api.example.com"
        internalOrigin: "*://*"
    audience: api-client
    clientID: api-client
    secret: "secretString"
```

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: api-mapping
spec:
  host: api.example.com
  prefix: /
  service: api-service:8080
  cors:
    origins: '*'
    methods: '*'
    headers: '*'
```

**Expected behavior**
A way for CORS to work with filters

**Versions (please complete the following information):**
 - Ambassador: 1.7.0
 - Kubernetes environment bare metal
 - Version v1.18.8
