### ISSUE TITLE
Redirect Path - Ambassador Admin Portal

### ISSUE THREAD

**Issue by vikas027** [datawire/ambassador#2975]
**Describe the bug**
I am trying to redirect `http://<hostname>/` to `http://ambassador-admin.ambassador.svc.cluster.local:8877/ambassador/v0/diag/` (internal to k8s cluster)

`http://<hostname>/` does not works but `http://<hostname>/ambassador/v0/diag/` works fine

**To Reproduce**
1. Create a service like below

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-admin-ext
  namespace: ambassador
  labels:
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: ambassador-admin-ext
      host: <hostname>
      prefix: /
      service: ambassador-admin.ambassador.svc.cluster.local
      path_redirect: /ambassador/v0/diag/
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/name: ambassador
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8877
```

2. Use curl (or a browser) to check the above mapping
```bash
✦ ❯ curl https://<hostname>/ -I
HTTP/1.1 502 Bad Gateway
content-length: 0
date: Sat, 12 Sep 2020 02:32:33 GMT
x-envoy-upstream-service-time: 17
server: envoy

✦ ❯ curl https://<hostname>/ambassador/v0/diag/ -I
HTTP/1.1 200 OK
server: envoy
date: Sat, 12 Sep 2020 02:32:41 GMT
content-type: text/html; charset=utf-8
content-length: 25947
x-envoy-upstream-service-time: 19
✦ ❯
```

**Expected behavior**
I should be able to browse to `https://<hostname>/` which should automatically redirect me to `https://<hostname>/ambassador/v0/diag/` 

**Versions (please complete the following information):**
 - Ambassador: 1.7.1 (installed through helm)
 - Kubernetes environment: kubeadm (a VM on GCP)
 - Kubernetes Version: 1.18.8
