### ISSUE TITLE
timeout_ms not working

### ISSUE THREAD

**Issue by rogaha** [datawire/ambassador#2993]
**Describe the bug**
I'm trying to increase the `request timeout limit` to avoid receiving `504` when it takes more than `3000ms`. I've created the following configuration: 
```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: aegis-api
  namespace: aegis
spec:
  prefix: /
  timeout_ms: 10000
  service: aegis-api
```

It seems to be running:
```
Name:         aegis-api
Namespace:    aegis
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"getambassador.io/v2","kind":"Mapping","metadata":{"annotations":{},"name":"aegis-api","namespace":"aegis"},"spec":{"prefix"...
API Version:  getambassador.io/v2
Kind:         Mapping
Metadata:
  Creation Timestamp:  2020-09-29T18:31:04Z
  Generation:          3
  Resource Version:    5992197
  Self Link:           /apis/getambassador.io/v2/namespaces/aegis/mappings/aegis-api
  UID:                 9826e119-2e48-46a2-aa83-0e9dd34e6c91
Spec:
  Prefix:      /
  Service:     aegis-api
  timeout_ms:  0
Status:
  State:  Running
Events:   <none>
```

The requests are still returning `504` After ~3 seconds. 

**Expected behavior**
Receive `504` after 10 seconds. 

**Versions (please complete the following information):**
 - Ambassador: 1.5.5
 - Kubernetes environment: EKS 
 - Version: 1.16.13
