### ISSUE TITLE
error : not a valid Mapping: Additional properties are not allowed ('regex_rewrite' was unexpected)

### ISSUE THREAD

**Issue by Yogendra-P** [datawire/ambassador#2997]
**error : not a valid Mapping: Additional properties are not allowed ('regex_rewrite' was unexpected)**
`regex_rewrite` property  is not identified with ambassador version 1.7.2

**ambassador mapping**

        apiVersion: ambassador/v1
        kind: Mapping
        name: asterix_dictionary_mapping
        prefix_regex: true
        # prefix: "\/site\/[0-9A-Za-z_]+\/dictionary\/.*"
        prefix: "\/skipper\/site\/.*\/dictionary\/.*"
        regex_rewrite:
               pattern: '\/skipper\/(.*)'
               substitution: '/\1'
        service: localhost:8000

**ambassador image**
   Image:          quay.io/datawire/ambassador:1.7.2

**Comment by cakuros** [comment]
Hi @Yogendra-P, I've noticed you're using the `apiVersion: ambassador/v1`.  `regex_rewrite` was a feature introduced after the 1.0 release of AES, and as such doesn't exist in the `v1` api.  Changing to `v2` should fix this.

**Comment by Yogendra-P** [comment]
thanks @cakuros it worked , btw there is no information about api version here https://www.getambassador.io/docs/latest/topics/using/rewrites/#regex_rewrite

**Comment by abhishek-rio** [comment]
> Hi @Yogendra-P, I've noticed you're using the `apiVersion: ambassador/v1`. `regex_rewrite` was a feature introduced after the 1.0 release of AES, and as such doesn't exist in the `v1` api. Changing to `v2` should fix this.

@cakuros 
I am also getting the same error for below config
```
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  name: retailerapi-dev-oms-updatecart-mapping
spec:
  service: test.dev-sync:80
  host: dev1.retailio.in
  prefix_regex: true
  prefix: '/api/Retailers/([0-9]*)/Carts/([0-9]*)/updateCart'
  regex_rewrite:
    pattern: '/api/Retailers/([0-9]*)/Carts/([0-9]*)/updateCart'
    substitution: '/api/Retailers/\1/Carts/\2/updateCart'
  bypass_auth: false
  ```
  Ambassador version 1.2.2
