### ISSUE TITLE
Fast validation/reconfig generates duplicate filter chains when multiple TLSContexts with client cert auth are present

### ISSUE THREAD

**Issue by jwm** [datawire/ambassador#3006]
**Describe the bug**
We have two `TLSContext`s that require client cert auth. They're identical except for their `secret` and `hosts` (even the allowed issuers are the same):

```
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: eligibility
  namespace: ambassador
spec:
  alpn_protocols: h2,http/1.1
  ca_secret: graphql-client-certs-issuers
  cert_required: true
  hosts:
  - eligibility.staging.devoted.com
  redirect_cleartext_from: 8080
  secret: ingress-eligibility-tls
```

With fast validation/reconfig enabled, Ambassador generates an invalid Envoy configuration with duplicate filter chains.

**To Reproduce**
1. Enable fast validation and reconfig.
2. Configure two `TLSContexts` with different `hosts`.
3. See the error message in Ambassador's log output about duplicate filter chains.

**Expected behavior**

**Versions (please complete the following information):**
 - Ambassador: 1.7.3
 - Kubernetes environment: EKS
 - Version: 1.17

**Additional context**
I have the Envoy config snapshots (`snapshots/envoy.json`) in both cases (with and without fast validation/reconfig enabled).

I can upload them if they're useful, but the difference seems to be that _without_ yields a filter chain for each `TLSContext`'s hosts, but _with_ fast reconfig, there seems to be only one filter chain, where the second `TLSContext` would be alphabetically. Also, that one filter chain doesn't have any matches declared:

```
--- amb-fast-reconfig-client-cert-auth-duplicate-filter-chains  2020-10-05 19:42:44.116760256 +0000
+++ amb-fast-reconfig-client-cert-auth-duplicate-filter-chains-no-fast-reconfig 2020-10-05 19:43:27.940968867 +0000
[...unrelated diffs...]
-                        "filter_chain_match": {},
+                        "filter_chain_match": {
+                            "server_names": [
+                                "eligibility.staging.devoted.com"
+                            ],
+                            "transport_protocol": "tls"
+                        },
```
