### ISSUE TITLE
using `regex_rewrite` triggers false alarm for conflict with non-existent `rewrite` directive, gives incorrect notice in diagnostics

### ISSUE THREAD

**Issue by obataku** [datawire/ambassador#3025]
**Describe the bug**
using `regex_rewrite` in a `Mapping` definition causes Ambassador to incorrectly complain about specifying both `regex_rewrite` and `rewrite` even without a conflicting `rewrite` directive

**To reproduce**
consider a `Mapping` as follows:
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: foo
spec:
  prefix: /foo/
  regex_rewrite:
    pattern: /foo/(.*)
    substitution: /\1
  service: foo-service.default:80
```

checking the admin diagnostics page after reveals a notice like:
>`NOTICE: -global-: Cannot specify both rewrite and regex_rewrite: using regex_rewrite and ignoring rewrite`

**Expected behavior**
it should correctly recognize there is no conflicting `rewrite` and not display said warning

**Versions**
 - Ambassador version 1.7.2 confirmed (although judging by code it appears to be a problem even now)
 - GKE
