### ISSUE TITLE
Ambassador Isolated Configuration

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#308]
There needs to be a way to configure multiple Ambassadors on a single cluster independently.

Two issues here:

1. Ambassador configuration itself is cluster global, so for example, if I set `use_proxy_proto: true` on an Ambassador config then all Ambassador's pick up this change... this makes it impossible to run different configurations on the cluster such as you might want to do for testing or canary.

2. Ambassador has a cluster global understanding of mappings. 

I'm mostly concerned about (1) here. One thought I have is making Ambassador configuration happen as a filesystem file (injected likely through a configmap).

**Comment by plombardi89** [comment]
I hit the first issue working on Argonath. I need to turn proxy protocol on for the next roll out, but if I turn it on using the Ambassador config mechanism then the existing prod Ambassador will be changed as well. This will cause an outage.

**Comment by plombardi89** [comment]
We have an additional driver for this: e2e test suite parallelization

**Comment by plombardi89** [comment]
So I think the biggest concern here is we can't break existing configuration by introducing a selector mechanism.

Here's what I am thinking

- Ambassador instances are "named" are now named.
- The default name is "default"

If you want to run multiple Ambassadors the config object for Ambassador gets written like this:

```yaml
---
apiVersion: ambassador/v0
kind:  Module
name:  ambassador
config:
  name: other-ambassador
```

Then when you want a mapping to target a particular Ambassador instance:

```yaml
apiVersion: ambassador/v0
kind: Mapping
name: whatever
prefix: /whatever/
ambassador: other-ambassador
```

This would cause the mapping to only appear in the instance named `other-ambassador`
