### ISSUE TITLE
Regression: Mapping labels fail to unmarshal

### ISSUE THREAD

**Issue by psalaberria002** [datawire/ambassador#3137]
**Describe the bug**
Mapping labels fail to unmarshal, making Ambassador crash on boot.

```
time="2021-01-07 19:11:40" level=error msg="goroutine \"/watcher\" exited with error: PANIC: json: cannot unmarshal array into Go struct field MappingSpec.spec.labels of type string" func="github.com/datawire/dlib/dgroup.(*Group).goWorkerCtx.func1.1" file="github.com/datawire/dlib@v1.1.0/dgroup/group.go:374" CMD=entrypoint PID=1 THREAD=/watcher
```

**To Reproduce**
1. Add the following Mapping
```
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: a
spec:
  prefix: /api/[^/]+/projects/[^/]+/a(/.*)?
  prefix_regex: true
  rewrite: ""
  service: "https://a"
  timeout_ms: 10000
  add_response_headers:
    Strict-Transport-Security: max-age=31536000
  retry_policy:
    retry_on: gateway-error
    num_retries: 15
  labels:
    ambassador:
      - d0:
          - a
          - xratelimitid:
              header: "X-Ratelimit-Id"
              omit_if_not_present: true
```
2. Apply the mapping

**Expected behavior**
It should be able to parse it. It's a valid config.

**Versions (please complete the following information):**
 - Ambassador: 1.10 with AMBASSADOR_LEGACY_MODE=false
