### ISSUE TITLE
FilterPolicy Priority

### ISSUE THREAD

**Issue by Lemmons** [datawire/ambassador#3190]
**Please describe your use case / problem.**
When two `FilterPolicy`s are added which cover the same host and path for a given request they are applied to that request inconsistently (sometimes this inconsistency is even inconsistent between Ambassador replicas in a given deployment).  This is a use case which seems to come up fairly often in the Ambassador slack channel and is one that would simplify things greatly.

The current solution is to add multiple sections to the same `FilterPolicy` in the specific order you want them applied.  This means ordering is based on the order they are specified in the `FilterPolicy`.

Some examples: 

Here is what I'd like to work:
```
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: catch-all
  namespace: ambassador
spec:
  rules:
    - host: "*.domain.com"
      path: "*"
      filters:
        - name: default-filter
          onDeny: break
          onAllow: break
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: my-subdomain
  namespace: ambassador
spec:
  rules:
    - host: "my-subdomain.domain.com"
      path: "*"
      filters:
        - name: my-subdomain
          onDeny: break
          onAllow: break
```
instead I have to do:
```
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: catch-all
  namespace: ambassador
spec:
  rules:
    - host: "my-subdomain.domain.com"
      path: "*"
      filters:
        - name: my-subdomain
          onDeny: break
          onAllow: break
    - host: "*.domain.com"
      path: "*"
      filters:
        - name: default-filter
          onDeny: break
          onAllow: break
```
The main problem with this is that it requires modification of the `FilterPolicy` every time you want to add a new host or path. This causes a variety of issues, including breaking the ability for devs to deploy and maintain their own `FilterPolicy`s in a multi-tenant kubernetes cluster.

**Describe the solution you'd like**
There are two potential solutions to this I can see working, and even which would work together.

1. Create an explicit order in which `FilterPolicy`s that match a given host/path would be applied.  This can be simply expressed as the most specific `FilterPolicy` which matches a given request is the one used.  So in the cases above, `my-subdomain.domain.com` would be appied instead of `*.domain.com`.

2. Add a priority field to the `FilterPolicy` resource.  In this case a request which matches a set of `FilterPolicy`s will always use the higher priority `FilterPolicy`.  If the priority is the same between a set of a matched `FilterPolicy`s the ordering described in item 1 above would be applied.
