### ISSUE TITLE
gRPC routing issue with Tensorflow Serving

### ISSUE THREAD

**Issue by sreddybr3** [datawire/ambassador#325]
Hi,

I am exactly following the gRPC tutorial for /helloworld.Greeter/ for the backend using TensorFlow Serving (/tensorflow.serving.PredictionService/ as defined in  [PredictionService](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service.proto) proto). Request from client is reaching the edge proxy, but not being forwarded to the backend service.

Ambassador-rbac-prometheus.yaml contains the following images
image: quay.io/datawire/ambassador:0.29.0
image: datawire/prom-statsd-exporter:0.6.0

tfs.yaml:

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: tfs
  name: tfs
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: grpc_mapping
      grpc: true
      prefix: /tensorflow.serving.PredictionService/
      rewrite: /tensorflow.serving.PredictionService/
      service: tfs
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: tfs
    targetPort: grpc-api
  selector:
    service: tfs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: tfs
    spec:
      containers:
      - name: tfs
        image: sreddybr3/model-container-cpu-inception:1.4.3
        ports:
        - name: grpc-api
          containerPort: 9000
        env:
          - name: PORT
            value: "9000"
      restartPolicy: Always

```
