### ISSUE TITLE
Update Ambassador on GKE docs

### ISSUE THREAD

**Issue by DanTulovsky** [datawire/ambassador#3255]
Hi,

Regarding these docs: https://www.getambassador.io/docs/latest/topics/running/ambassador-with-gke/

Specifically, section (5) asks you to make manual edits to the load balancer health check.  This isn't something recommended by GKE for load balances created via Kubernetes configs.  A better way is to define a Backend config and then reference it in the ambassador Service definition.

For example:

Define backend config with a custom health check:

```
apiversion: cloud.google.com/v1
kind: backendconfig
metadata:
  name: ambassador-hc-config
  namespace: ambassador
spec:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features
  timeoutsec: 30
  connectiondraining:
    drainingtimeoutsec: 30
  customrequestheaders:
    headers:
      - "x-client-region:{client_region}"
      - "x-client-city:{client_city}"
      - "x-client-citylatlong:{client_city_lat_long}"
  logging:
    enable: true
    samplerate: 1.0
  healthcheck:
    checkintervalsec: 10
    timeoutsec: 10
    port: 8877
    type: http
    requestpath: /ambassador/v0/check_alive
```

Annotate the ambassador service with:

`cloud.google.com/backend-config: '{"default": "ambassador-hc-config"}'`

That will properly configure the health check without manual updates.

Thank you
Dan
