### ISSUE TITLE
gRPC load balancing doesn't appear to work

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#326]
From @ryanolson

@richarddli by just increasing the replicas in the example i get:
```
root@7aad1319fc7d:/devel# python greeter_client.py Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-6xdvh! Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-6xdvh! Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-6xdvh! ... root@7aad1319fc7d:/devel# python greeter_client.py Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-qzlt9! Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-qzlt9! Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-qzlt9! ... root@7aad1319fc7d:/devel# python greeter_client.py Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-6xdvh! Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-6xdvh! Greeter client received: Hello, you from host=grpc-greet-f468d5c7d-6xdvh! ...
as you can see, i get load-balancing per-invocation of a client; essentially L4 load-balancing.
```

however, i'm looking for 1 client, i.e. 1 grpc stub, to load-balance over all backend services - L7
note: i had to modify the greeter_server to output it's HOSTNAME in the response; similarly, the client makes 10 repeated calls using the same stub. (I shortened the output above).

Also reported by Jean-Christophe Baey @jcbaey_twitter

**Comment by Litee** [comment]
Sounds like https://github.com/envoyproxy/envoy/issues/2744

**Comment by plombardi89** [comment]
I'm able to reproduce this pretty consistently so now I'm digging deeper. The linked issue doesn't apply as we're not using `socket_address`.

**Comment by plombardi89** [comment]
So when I switch to a headless service in Kubernetes such as below:

```
apiVersion: v1
kind: Service
metadata:
  name: grpc-basic
  namespace: stable
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: grpc-basic-stable
      grpc: true
      prefix: /helloworld.Greeter/
      rewrite: /helloworld.Greeter/
      service: grpc-basic:50051
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: grpc-basic-stable-grpcreflect
      grpc: true
      prefix: /grpc.
      rewrite: /grpc.
      service: grpc-basic:50051
    forge.repo: git@github.com:datawire/ambassador-examples.git
    forge.descriptor: grpc-basic/service.yaml
    forge.version: d1e8a449005bc14fa572a7b54296ade0fa3fcf2d.sha
  labels: {forge.service: grpc-basic, forge.profile: stable}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  selector:
    app: grpc-basic
```

The requests are load balanced "correctly" across my three GRPC service pods:

```
plombardi@plombowski ~/w/ambassador-examples> ./grpcurl.sh -plaintext -d '{"name": "Phil"}' <REDACTED>:32212 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-68879db8d9-8pq6l)!"
}
plombardi@plombowski ~/w/ambassador-examples> ./grpcurl.sh -plaintext -d '{"name": "Phil"}' <REDACTED>:32212 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-68879db8d9-czmcg)!"
}
plombardi@plombowski ~/w/ambassador-examples> ./grpcurl.sh -plaintext -d '{"name": "Phil"}' <REDACTED>:32212 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-68879db8d9-czmcg)!"
}
plombardi@plombowski ~/w/ambassador-examples> ./grpcurl.sh -plaintext -d '{"name": "Phil"}' <REDACTED>:32212 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-68879db8d9-xktlp)!"
}
plombardi@plombowski ~/w/ambassador-examples> ./grpcurl.sh -plaintext -d '{"name": "Phil"}' <REDACTED>:32212 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-68879db8d9-8pq6l)!"
}
plombardi@plombowski ~/w/ambassador-examples> ./grpcurl.sh -plaintext -d '{"name": "Phil"}' <REDACTED>:32212 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-68879db8d9-xktlp)!"
}
```

**Comment by plombardi89** [comment]
So I have a working theory here. Envoy is opening a persistent connection to the first backend server it resolves.

I reverted from headless mode to use the following configuration:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: grpc-basic
  namespace: stable
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: grpc-basic-stable
      grpc: true
      prefix: /helloworld.Greeter/
      rewrite: /helloworld.Greeter/
      service: grpc-basic:50051
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: grpc-basic-stable-grpcreflect
      grpc: true
      prefix: /grpc.
      rewrite: /grpc.
      service: grpc-basic:50051
    forge.repo: git@github.com:datawire/ambassador-examples.git
    forge.descriptor: grpc-basic/service.yaml
    forge.version: 0b75a9d4a1e7357b71c91cd73714e46e9ef94fb8.sha
  labels: {forge.service: grpc-basic, forge.profile: stable}
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  selector:
    app: grpc-basic
```

Then I booted up another Pod on the cluster and started to hit `grpcbasic.stable:50051` with `grpcurl`. This is the **no Ambassador/Envoy** path. Because `grpcurl` is a short lived program it's going to get a new connection everytime.

```text
# ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-n6chn)!"
}
/ # ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-n6chn)!"
}
/ # ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-k9trs)!"
}
/ # ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-n6chn)!"
}
/ # ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-k9trs)!"
}
/ # ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-8z46f)!"
}
/ # ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-8z46f)!"
}
/ # ~/go/bin/grpcurl -plaintext -d '{"name": "Phil"}' grpc-basic.stable:50051 helloworld.Greeter/SayHello
{
  "message": "Hello, Phil (host: grpc-basic-799d574f58-8z46f)!"
}
```
