### ISSUE TITLE
EKS (L7) SSL Termination at ELB - Proxy Protocol and HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by vikas027** [datawire/ambassador#3274]
**Describe the bug**

I have a working Ambassador setup where I have terminated SSL on the Classic ELB (using ACM certificate). I have also enabled proxy protocol using the ELB [annotation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations/#proxy-protocol-v2) but when I enable HTTP to HTTPS redirection, it gets stuck in a https loop.

I also want to have HTTP to HTTPS redirection too along with the proxy protocol. I think I need some options set here but can't figure them out.

**To Reproduce**
Steps to reproduce the behaviour:
1. Patch the service
```yaml
---
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    use_proxy_proto: true
    use_remote_address: false
    x_forwarded_proto_redirect: true

---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: ambassador
spec:
  hostname: "*"
  selector:
    matchLabels:
      hostname: wildcard
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
      # action: Redirect # Redirection loop
```

**Expected behaviour**
I would expect Ambassador to behave normally and have the HTTP to HTTPS redirection working smoothly :)

**Versions (please complete the following information):**
 - Ambassador: v1.12.1
 - Kubernetes environment: EKS
 - Kubernetes Version: v1.19.8

**Related tickets**
- https://github.com/datawire/ambassador/issues/1571
