### ISSUE TITLE
dogstatsd metrics export not working

### ISSUE THREAD

**Issue by DanTulovsky** [datawire/ambassador#3277]
**Describe the bug**
I can't seem to get dogstatsd metrics working in ambassador edge stack.  

**To Reproduce**
I've setup:

```
  # https://docs.datadoghq.com/integrations/ambassador/
  STATSD_ENABLED: true
  DOGSTATSD: true

envRaw:
  - name: STATSD_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```

The logs on startup have:

```
time="2021-03-16T14:11:56Z" level=warning msg="statsd is not in use"
```

which looks related.  I don't see any other `statsd` related logs.

**Expected behavior**
statsd metrics show up.

**Versions (please complete the following information):**
 - Ambassador: 1.11.2
 - Kubernetes environment: GKE
 - Version: 1.19.7-gke.1500

**Additional context**

I can login to the ambassador pod and confirm:

```
bash-5.0$ env |grep STATSD
DOGSTATSD=true
STATSD_HOST=10.128.0.29
STATSD_ENABLED=true
```
I can also manually set a metric:

```
echo -n "custom10.metric.name:98|g"|nc -u -w1 $STATSD_HOST 8125
```

And this metric shows up.  But I still see no envoy metrics. Is the "statsd is not in use" message in the logs a red herring or actually indicative of a problem? On the ambassador debug page I do see: `StatsD support enabled`.

Thank you
Dan
