### ISSUE TITLE
Configuring TLS redirect has errors

### ISSUE THREAD

**Issue by kevinohara80** [datawire/ambassador#328]
Ambassador Version: **0.29.0**
Kubernetes Version: **1.9.4**

I recently updated my ambassador service to start accepting TLS connections. I wanted to set up the redirect from 80 to 443 per the [documentation][1]. I first create my tls cert resource and then added a `Module` block to the annotations of the ambassador service. When I do this, I the ambassador pods log the following error.

```
2018-03-20 11:45:53 kubewatch 0.29.0 ERROR: tls.yaml.1: <RichStatus BAD error=could 
not process Module object: tls.yaml[1] defines Module tls, which is already present
hostname=ambassador-7fd7c58489-42zs6 resolvedname=10.16.0.10 version=0.29.0>

2018-03-20 12:16:32 kubewatch 0.29.0 ERROR: ERROR ERROR ERROR Starting with 
configuration errors
```

The pods are running ok but the redirect doesn't work. Am I doing something wrong here or is there a bug?

For reference, here is my LoadBalancer service definition:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
spec:
  type: LoadBalancer
  ports:
  - name: ambassador-http
    port: 80
    targetPort: 80
  - name: ambassador-https
    port: 443
    targetPort: 443
  selector:
    service: ambassador
```

[1]: https://www.getambassador.io/user-guide/tls-termination
