### ISSUE TITLE
Can't make admin console to with non-default mappings

### ISSUE THREAD

**Issue by illinar** [datawire/ambassador#3335]
We followed the instructions described here
https://www.getambassador.io/docs/edge-stack/latest/about/faq/#how-do-i-disable-the-default-admin-mappings

We correctly see 404 now when accessing IP of the service, but admin mapping rewrite results in timeout (ERR_CONNECTION_TIMED_OUT) when trying to access "https://xyz.domain.com/edge_stack/" (the same with `edgectl login --namespace=ambassador xyz.domain.com`)

The configuration is as follows:

```
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  config:
    diagnostics:
      enabled: false
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: admin-mapping
  namespace: ambassador
spec:
  host: xyz.domain.com
  prefix: /edge_stack/
  rewrite: /edge_stack_ui/edge_stack/
  service: 127.0.0.1:8500
```

What are we missing?
