### ISSUE TITLE
Regression: Adding RateLimit to AES causes pods crash

### ISSUE THREAD

**Issue by tolik93** [datawire/ambassador#3348]
**Describe the bug**
In my case I installed ambassador via helm chart in the same namespace as my application. RateLimitService is enabled via values.yaml of the helm chart. If I add RateLimit to the namespace, the ambassador Pods crash when I open the AES Console. The behavior is same if I create RateLimit in the AES console. Adding `AMBASSADOR_SINGLE_NAMESPACE: true
` and `scope.singleNamespace: true` didn't help. Does anyone have an idea how to fix it quickly?

**To Reproduce**
1. Go to AES Console
2. Click on "Rate Limits"
3. Add sample RateLimit in the custom namespace(not "ambassador") 
4. Ambassador pods will be crash

**Expected behavior**
Creating RateLimit shouldn't cause any crashes of pods. 

**Versions (please complete the following information):**
 - Ambassador: docker.io/datawire/aes:1.12.3
 - Helm chart:   6.6.3
 - Kubernetes environment: AWS EKS
 - Version: 1.19

```yaml
apiVersion: getambassador.io/v2
kind: RateLimit
metadata:
  name: core
spec:
  domain: ambassador
  limits:
  - pattern:
    - generic_key: core
    rate: 500
    unit: minute
```
