### ISSUE TITLE
Ambassador returns 502 Bad gateway

### ISSUE THREAD

**Issue by Sbou** [datawire/ambassador#3386]
**Describe the bug**

I configured a mapping to redirect to a kubernetes service.
This service has the port 80 and a target port 8080 (container port).
If I set the Ambassador mapping without port (so with the default port 80) I receive a "Bad gateway".
If I set the mapping with the port 8080, it works.

**To Reproduce**

Kubernetes deployment
```yaml
apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: test-service
    name: test-service
    namespace: test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/instance: test
        app.kubernetes.io/name: test-service
    template:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        labels:
          app.kubernetes.io/instance: test
          app.kubernetes.io/name: test-service
      spec:
        containers:
        - env:
          - name: ASPNETCORE_URLS
            value: http://+:8080
          image: image...
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health/live
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: test-service
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
```

Kubernetes service
```yaml
apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: test-service
    name: test-service
    namespace: bootstrap
  spec:
    clusterIP: 192.168.243.147
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/instance: test
      app.kubernetes.io/name: test-service
    sessionAffinity: None
    type: ClusterIP
```
Ambassador mapping
```yaml
apiVersion: getambassador.io/v2
  kind: Mapping
  metadata:
    name: test-service
    namespace: test
  spec:
    prefix: /something/
    service: test-service.test
    timeout_ms: 30000
```

kubectl describe for this resources:

```bash
k describe service
Name:              test-service
Namespace:         test
Labels:            app.kubernetes.io/instance=test
                   app.kubernetes.io/name=test-service
Selector:          app.kubernetes.io/instance=test,app.kubernetes.io/name=test-service
Type:              ClusterIP
IP:                192.168.243.147
Port:              http  80/TCP
TargetPort:        http/TCP
Endpoints:         10.0.24.62:8080
Session Affinity:  None
```

```bash
k get endpoints
NAME                    ENDPOINTS         AGE
test-service            10.0.24.62:8080   33m
```

**Ambassador log**
```log
ACCESS [2021-05-04T08:36:13.234Z] "POST /something/.well-known/est/simpleenroll/ HTTP/1.1" 502 - 350 0 1 0 "165.225.20.81,10.0.24.66" "PostmanRuntime/7.28.0" "46009604-a689-4d76-833c-99a7f15e7524" "myserver.com" "192.168.243.147:80"
```

**Expected behavior**
Ambassador calls the Kubernetes service input and this is this service which redirect to the container endpoint.

**Versions (please complete the following information):**
 - Ambassador: CHART   ambassador-6.4.4    APP VERSION  1.5.2
 - Kubernetes environment : Azure Kubernetes Service
 - Version v1.18.10

**Additional context**
