### ISSUE TITLE
No healthy upstream when specifying external host with more than one period in the service name

### ISSUE THREAD

**Issue by rhysm** [datawire/ambassador#3433]
**Describe the bug**
Since upgrading from 1.11.2 to 1.13.4 if specifying a Mapping resource which points to an external host name with more than 1 period (e.g. https://foo.example.com) it results in a `no healthy upstream` error from Ambassador.

When specifying a service with a single period (e.g. http://httpbin.org) it works fine.

A workaround is to specify the IP address of the external host directly, but this is not ideal.

**To Reproduce**

- Create a mapping like this:

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: example
  namespace: example
spec:
  ambassador_id: ambassador-internal
  host: example-internal.example.com
  prefix: /example/
  rewrite: ""
  service: https://foo.example.com
  timeout_ms: 60000
```

- Try to access the path
- You should get a 503 response with `no healthy upstream`

**Expected behavior**
Request should be routed to the service specified in the `service` field.

**Versions (please complete the following information):**
 - Ambassador: 1.13.4
 - Kubernetes environment: bare metal
 - Version 1.16.9

**Additional context**
Access log from Ambassador when trying to access mapping:
```
ACCESS [2021-05-17T21:43:36.233Z] "GET /example/ HTTP/1.1" 503 UH 0 19 0 - "172.16.21.215" "curl/7.61.1" "aa30f90d-6e38-4142-93d5-3c491e9d6325" "example-internal.example.com" "-"
```
