### ISSUE TITLE
Creating dynamic service in mapping

### ISSUE THREAD

**Issue by DriesVanherpe-inuits** [datawire/ambassador#3438]
**Please describe your use case / problem.**
We want to use our ambassador edge stack to proxy some request to another cluster like this :

![ambassador (2)](https://user-images.githubusercontent.com/83644432/118785522-37bf8880-b891-11eb-8f63-ef3ca0fa7899.png)

We want to fall back on a mapping which dynamically alters the `host` header from `*.k8s1.company.local` to `*.k8s2.company.local`. 

Example given : `myapplication.k8s1.company.local` is sent to ambassador but no (specific) mapping can be found. The fallback mapping should send the request to `myapplication.k8s2.company.local` 

**Describe the solution you'd like**
I've found multiple rewrites like `host_regex` or `prefix_rewrite` but i'm  not sure if that's something i need in my case. I'd like to have something like this: 

```
 ---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: 404-fallback
  namespace: ambassador
spec:
  host: '(.*).k8s.mycompany.local$
  host_regex: true
  prefix: "/"
  service: $1.k8s2.mycompany.local
```
