### ISSUE TITLE
Optional error_response_overrides from the application

### ISSUE THREAD

**Issue by vikas027** [datawire/ambassador#3469]
**Environment**
- Ambassodor Edge Stack 1.13.1
- EKS v.1.20.6 (if that matters)

**Please describe your use case / problem.**
I am looking to have custom 404 errors but at the same time allow developers to have their own `404` pages as well.

I can do this as a blanket rule for everyone but then it does not differentiates a `404` coming from Ambassador or an actual `404` coming from an application

```yaml
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  config:
    error_response_overrides:
      - on_status_code: 404
        body:
          text_format: "File not found"
```

**Describe the solution you'd like**
I believe it would be smarter if the ambassador can figure out whether the `404` is coming from an application or the ambassador itself. Having this behaviour, we will only have to define overrides in the `Module` resource and keep all the `Mapping` resources lean.

**Describe alternatives you've considered**
One way is to have a blanket rule in a `Module` resource and then have `bypass_error_response_overrides: true` in every `Mapping` resource

**Additional context**
This was also discussed in a [thread](https://datawire-oss.slack.com/archives/CAULN7S76/p1621816673098700) on slack.
