### ISSUE TITLE
Use Ambassador as a dynamic gateway to Kubernetes services

### ISSUE THREAD

**Issue by jacob-hd** [datawire/ambassador#377]
I'd like to dynamically forward http requests to Ambassador to specific Kubernetes services.

For instance:
- Requests to `foo.mywebsite.com` are forwarded to service `foo`
- Requests to `bar.mywebsite.com` are forwarded to service `bar`

The configuration might look something like this:
```yaml
---
apiVersion: ambassador/v0
kind:  Mapping
name:  my_mapping
prefix: /
host: "^([^\\.]+)\\.mywebsite\\.com$"
host_regex: true
service: "$1"
```

I'm trying to convey that the capture group from the `host` regex is used in the `service` field.

This should be possible using [Envoy's Lua http filters](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter).

This is simple to do with Nginx at the edge of the cluster:
```
server {
    server_name ~^([^\.]+)\.mywebsite\.com;
    resolver kube-dns.kube-system.svc.cluster.local valid=5s;

    location / {
        proxy_pass http://$1.default.svc.cluster.local;
    }
}
```

It'd be great if Ambassador could support this. Thanks much!
