### ISSUE TITLE
When using AuthService, `req.body` in `POST` request in ExpressJs is always empty (i.e. `req.body = {}`)

### ISSUE THREAD

**Issue by seunggs** [datawire/ambassador#4131]
**Describe the bug**
When using AuthService, `req.body` in `POST` request in ExpressJs is always empty (i.e. `req.body = {}`)

**To Reproduce**
1. Deploy the AuthService based on the docs
```
...
auth_service: auth-service.auth
path_prefix: '/extauth'
include_body:
  max_bytes: 1000000
  allow_partial: true
...
```
2. Deploy an Express server as an external auth service
```
...
const authPath = '/extauth'
app.all(`${authPath}*`, authenticate, (req, res) => {
  res.send('OK (authenticated)')
})
...
```
3. Deploy an app and hit a `POST` endpoint and observe that `req.body` is always empty `{}` (I have confirmed that it works fine when I remove the AuthService)

**Expected behavior**
`req.body` should not be empty

**Versions (please complete the following information):**
 - Emissary Ingress - v2.1.2
 - Amazon EKS - v1.21
