### ISSUE TITLE
Ambassador should warn / notify if "service:" is not a DNS resolveable name (and port)

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#434]
**Describe the bug**
Someone created a mapping like this:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: hj
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  hj
      prefix: /hj/
      service: http://hipsterjesus.com/api
      host_rewrite: hipsterjesus.com
spec:
  type: ClusterIP
  ports:
    - port: 80
```

Which yields an invalid cluster in Envoy:

```json
{
    "lb_type": "round_robin",
    "name": "cluster_http___hipsterjesus_com_api",
    "type": "strict_dns",
    "urls": [
        "tcp://hipsterjesus.com/api:80"
    ]
}
```

**To Reproduce**
Deploy the mapping. Check the diagnostics UI or envoy.json

**Expected behavior**
1. Diagnostics UI at a minimum should warn the user this is wrong.
2. Prevent it from happening in the first place?

**Versions (please complete the following information):**
 - Ambassador: 0.32.2
 - Kubernetes environment: Kubernetes 1.8.5 on AWS via Kops w/ Calico CNI
 - Version 1.8.5
