### ISSUE TITLE
Ambassador container restarted frequently by Kubernetes due to timed out liveness probes

### ISSUE THREAD

**Issue by croeck** [datawire/ambassador#446]
**Describe the bug**

Ambassador pods are restarted frequently by Kubernetes due to timeouts of the liveness probe.
If I describe one of the pods, we receive this information:

```
Name:           ambassador-9b4dcdd85-4k2vk
Namespace:      api-gateway
Node:           k8s-agent-57560735-0/10.200.32.4
Start Time:     Mon, 21 May 2018 15:02:58 +0200
Labels:         app=ambassador
                pod-template-hash=560878841
                service=ambassador
                version=0.33.1
Annotations:    cni.projectcalico.org/podIP=10.200.129.224/32
                prometheus.io/port=9102
                prometheus.io/scrape=true
                sidecar.istio.io/inject=false
Status:         Running
IP:             10.200.129.224
Controlled By:  ReplicaSet/ambassador-9b4dcdd85
Containers:
  ambassador:
    Container ID:   docker://a28be07786485d5c4c9b9f8a751da43a419eba50fb4cdb1bd3c858c726673109
    Image:          quay.io/datawire/ambassador:0.33.1
    Image ID:       docker-pullable://quay.io/datawire/ambassador@sha256:f12c3f5c1093f934b2ff33e8c42a2a0d5d026c7862e2cf4e898d6270e950c8bc
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 21 May 2018 15:20:33 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Mon, 21 May 2018 15:15:45 +0200
      Finished:     Mon, 21 May 2018 15:17:50 +0200
    Ready:          True
    Restart Count:  7
    Limits:
      cpu:     1
      memory:  400Mi
    Requests:
      cpu:      200m
      memory:   100Mi
    Liveness:   http-get http://:8877/ambassador/v0/check_alive delay=30s timeout=1s period=3s #success=1 #failure=3
    Readiness:  http-get http://:8877/ambassador/v0/check_ready delay=30s timeout=5s period=3s #success=1 #failure=3
    Environment:
      AMBASSADOR_NAMESPACE:  api-gateway (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ambassador-token-vtd7b (ro)
  statsd-sink:
    Container ID:   docker://b140050f750e17199d6b66fb62988272b017e96358f4353174568d9bed0d174a
    Image:          datawire/prom-statsd-exporter:0.6.0
    Image ID:       docker-pullable://datawire/prom-statsd-exporter@sha256:761767e0d969219d71244f9bc35954a2f0c788bd311e52a06cea69fc2eacdf89
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 21 May 2018 15:03:11 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ambassador-token-vtd7b (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          True
  PodScheduled   True
Volumes:
  ambassador-token-vtd7b:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ambassador-token-vtd7b
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                From                           Message
  ----     ------                 ----               ----                           -------
  Normal   Scheduled              18m                default-scheduler              Successfully assigned ambassador-9b4dcdd85-4k2vk to k8s-agent-57560735-0
  Normal   SuccessfulMountVolume  18m                kubelet, k8s-agent-57560735-0  MountVolume.SetUp succeeded for volume "ambassador-token-vtd7b"
  Normal   Pulling                18m                kubelet, k8s-agent-57560735-0  pulling image "quay.io/datawire/ambassador:0.33.1"
  Normal   Pulled                 18m                kubelet, k8s-agent-57560735-0  Successfully pulled image "quay.io/datawire/ambassador:0.33.1"
  Normal   Created                18m                kubelet, k8s-agent-57560735-0  Created container
  Normal   Started                18m                kubelet, k8s-agent-57560735-0  Started container
  Normal   Pulling                18m                kubelet, k8s-agent-57560735-0  pulling image "datawire/prom-statsd-exporter:0.6.0"
  Normal   Pulled                 17m                kubelet, k8s-agent-57560735-0  Successfully pulled image "datawire/prom-statsd-exporter:0.6.0"
  Normal   Created                17m                kubelet, k8s-agent-57560735-0  Created container
  Normal   Started                17m                kubelet, k8s-agent-57560735-0  Started container
  Warning  Unhealthy              7m (x32 over 17m)  kubelet, k8s-agent-57560735-0  Liveness probe failed: Get http://10.200.129.224:8877/ambassador/v0/check_alive: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff                3m (x3 over 3m)    kubelet, k8s-agent-57560735-0  Back-off restarting failed container
```

**To Reproduce**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  namespace: "{{ ambassador_namespace }}"
  labels:
    app: ambassador
    service: ambassador
    version: "{{ ambassador_version }}"
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ambassador
      service: ambassador
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
      labels:
        app: ambassador
        service: ambassador
        version: "{{ ambassador_version }}"
    spec:
      serviceAccountName: ambassador
      containers:
      - name: ambassador
        image: "quay.io/datawire/ambassador:{{ ambassador_version }}"
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      - name: statsd-sink
        image: datawire/prom-statsd-exporter:0.6.0
      restartPolicy: Always
```

*If you need further yaml files (service, rbac, ...) please contact me. I assume they are not relevant here.*

**Expected behavior**

The ambassador pods and container do not get restarted if no load is applied.

**Versions (please complete the following information):**
 - Ambassador: 0.33.1
 - Kubernetes environment: Kubernetes on Azure via acs-engine (+AAD, Calico)
 - Version 1.10.1

**Additional context**

@richarddli as mentioned on gitter
