### ISSUE TITLE
statsd-sink "Name does not resolve"

### ISSUE THREAD

**Issue by kellycampbell** [datawire/ambassador#465]
**Describe the bug**
Ambassador was not responding timely to requests. 
Symptoms seem similar to #446 

ambassador was logging this msg about 200 times per second from the `statsd` container of a single pod:

```
socat[7776] E getaddrinfo("statsd-sink", "NULL", {1,0,2,17}, {}): Name does not resolve
```

This started immediately after scaling the ambassador deployment from 1 to 2 pods.

**Versions (please complete the following information):**
 - Ambassador: 0.33.1
 - Kubernetes environment: AWS using kops
 - Version: 1.7.12, kernel 4.4.111-k8s
 - Calico version: quay.io/calico/node:v2.6.2, quay.io/calico/cni:v1.11.0

**Additional Info:**

ambassador deployment config:
```
      containers:
      - name: ambassador
        image: quay.io/datawire/ambassador:0.33.1
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "true"
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMBASSADOR_RESTART_TIME
          value: "20"
        - name: AMBASSADOR_DRAIN_TIME
          value: "10"
        - name: AMBASSADOR_SHUTDOWN_TIME
          value: "15"
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
      - name: statsd
        image: quay.io/datawire/statsd:0.33.1
```
