### ISSUE TITLE
Support YAML arrays for CORS configuration

### ISSUE THREAD

**Issue by endrec** [datawire/ambassador#466]
At the moment CORS settings use comma separated lists.
It would be nice to supoort YAML arrays as it increases readability.

_Example:_
- Current format:
  ```
  cors:
    origins: http://foo.example,http://bar.example
    methods: POST, GET, OPTIONS
    headers: Content-Type,Accept,Authorization
    credentials: true
    exposed_headers: X-Custom-Header
    max_age: "86400"
  ```
- Enhanced format:
  ```
  cors:
    origins: http://foo.example,http://bar.example
    methods: 
      - POST
      - GET
      - OPTIONS
    headers: 
      - Content-Type
      - Accept
      - Authorization
    credentials: true
    exposed_headers: X-Custom-Header
    max_age: "86400"
  ```
