### ISSUE TITLE
Configure tls module in helm chart

### ISSUE THREAD

**Issue by maxfrigge** [datawire/ambassador#488]
**Please describe your use case / problem.**
I am using the helm chart and would like to configure the tls module to redirect port 80 to 443. Right now there is no way to setup annotations for the ambassador service.

**Describe the solution you'd like**
The most flexible way would probably be to add `service.annotations` to `values.yaml`. These values could then be passed to the service template. Since this is a common thing to do, it would be convinient to already have this block in `values.yaml` but in comments so it has no effect by default.

**Describe alternatives you've considered**
I have considered (not tried) using `kubectl patch` but think this should be dealt with in the chart config.

**Comment by containscafeine** [comment]
Hmm, to let users configure the TLS module via Helm, we're assuming that ambassador-certs and/or ambassador-cacert secrets have already been configured in the cluster.
So, how do we do this?
Should we also ask the users for their .pem and .crt paths, and then also deploy the secrets. And then, we can configure the TLS module YAML.
Am I getting this correct? :thinking:

**Comment by kflynn** [comment]
@maxfrigge In Ambassador 0.35.1, we added support for configuring whatever annotations you like on the `ambassador` service that Helm generates. There's an example in `helm/README.md` but here's a potential `values.yaml` snippet:

```
service:
  type: LoadBalancer
  port: 80
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name:  ambassador
      config:
        diagnostics:
          enabled: false
```

Let us know if that works for you!
