### ISSUE TITLE
apiext - failed conversion webhook for mappings related to ratelimit labels

### ISSUE THREAD

**Issue by ppeble** [datawire/ambassador#5053]
**Describe the bug**

I am running both Emissary v1.14 using `getambassador.io/v2` mappings and also have a new install using Emissary v3.6.0 in the same EKS cluster using the new v3 CRDs. This includes the `apiext` deployment and the updated CRDs with the conversion webhook. The new deployment works without issues and the old deployment works without issues, as expected. 

The problem is that I now see frequent conversion errors for the old `v2` mappings in the conversion webhook related to ratelimit labels. The error in the emissary logs are:

```
E0509 17:15:32.614232       1 reflector.go:138] pkg/kates/client.go:466: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: conversion webhook for getambassador.io/v2, Kind=Mapping failed: v2.Mapping.Spec: v2.MappingSpec.Labels: v2.MappingLabelGroupsArray: v2.MappingLabelsArray: decode slice: expect [ or n, but found {, error found in #10 byte of ...|t_label":{"host":{"h|..., bigger context ...|,"labels":{"ambassador":[{"header_request_label":{"host":{"header":":authority","omit_if_not_present|...
```

I cannot find the exact doc anymore but I know that the label format shifted with the newer CRDs. I assumed the `apiext` conversion would handle this, though. 

My new v3 mappings have the correct label format and work without issues. The problem is solely the error in the conversion webhook.

**To Reproduce**
1. Install v3.6.0 of emissary via the helm chart v8.6.0
2. Create new mapping using `v2` with the following labels:

```yaml
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: old-mapping-version
spec:
  prefix: /path/
  service: some.service

  labels:
    ambassador:
      - header_host_label:
        - host:
            header: ":authority"
            omit_if_not_present: true
      - header_host_and_path_label:
        - host:
            header: ":authority"
            omit_if_not_present: true
        - path:
            header: ":path"
            omit_if_not_present: true
```

3. Follow logs in emissary for any pod to see errors

**Expected behavior**

I expect the older mapping with labels to be converted via the CRD webhook without any issues.

**Versions (please complete the following information):**
 - Ambassador: v3.6.0
 - Kubernetes environment: AWS EKS 1.24
 - Helm chart version: v8.6.0
