### ISSUE TITLE
Socket.IO with transport polling fails

### ISSUE THREAD

**Issue by marcotrinelli** [datawire/ambassador#5161]
**Describe the bug**
I get a 504 Gateway Timeout error, followed by a 400 Bad Requests when connecting to a socket.io server with `transports: ['polling']` (Socket.IO [transports](https://socket.io/docs/v4/client-options/#transports) option). The Socket.IO handshake succeeds (meaning that I get the logs on the `connection` event in the upstream service), but the data channel is cut just afterwards. 

From the browser developer tools:

`GET https://<origin>/<path>/socket.io/?EIO=4&transport=polling&t=Ob01get&sid=We8gI0PFNPB6TZuqADQB 504 (Gateway Timeout)`

`POST https://<origin>/<path>/socket.io/?EIO=4&transport=polling&t=Ob01j91&sid=We8gI0PFNPB6TZuqADQB 400 (Bad Request)
{code: 1, message: "Session ID unknown"}
`

This issue only happens when using emissary-ingress as gateway: a local setup that does not involve emissary-ingress does not have such issue. Also,  using `transports: ['websocket']` does not produce this issue.

**To Reproduce**
Using the following configs:
- Socket.IO web client configured to use a specific `path` (`<path>/socket.io`) and `extraHeaders` (Authorization)
- A `Mapping` with the following config (`<path>` and `<origin>` are placeholders):
```
spec:
  allow_upgrade:
    - websocket
  ambassador_id:
    - id1
  bypass_auth: false
  connect_timeout_ms: 10000
  cors:
    headers:
      - Authorization
      - Content-Type
    methods:
      - 'GET, POST, PATCH, DELETE, OPTIONS'
    origins:
      - '*'
  hostname: <origin>
  prefix: /<path>/
  rewrite: /
  service: upstream-service
  timeout_ms: 10000
  ```

- Socket.IO server (`upstream-service`) with cors enabled, listening to connections towards default path `/socket.io/`

**Expected behavior**

Socket.IO connection successful (handshake and data channel) 

**Versions (please complete the following information):**
 - Ambassador: 2.2.2 (helm: emissary-ingress 7.3.2)
