### ISSUE TITLE
Random 403 UAEX errors when updating circuit breakers configuration

### ISSUE THREAD

**Issue by michelgz** [datawire/ambassador#5393]
**Describe the bug**
When updating Ambassador module **_circuit_breakers_** configuration, a subset of requests (0.1%~) fail seemingly randomly with a **_403 UAEX_** error returned by Ambassador

**To Reproduce**
1. Update any circuit_breakers configuration in your Ambassador module, e.g:
```
circuit_breakers:
      - max_connections: 1000000
        max_pending_requests: 100000000
        max_requests: 100000000
        max_retries: 100000000
        priority: default
```
2. Ambassador picks up new configuration
3. See random 403 UAEX responses, e.g:

`2023-10-26T15:53:13.056908247Z stdout F ACCESS [2023-10-26T15:53:12.893Z] "POST /example HTTP/1.1" 403 UAEX 1151 0 86 - "example" "Go-http-client/1.1" "example" "example" "-"`

</span></body></html>

**Expected behavior**
No 403 UAEX errors when updating _circuit_breakers_ configuration, (No AuthService, nor RateLimit is enabled on this cluster)

**Versions (please complete the following information):**
 - Ambassador: 3.7.2 (AES)
 - Kubernetes environment: EKS
 - Version: 1.27

**Additional context**
- Issue doesn't occur in AES version 2.3.1
- Issue occurs in cluster where no AuthService or RateLimit is enabled
- Issue doesn't occur when swapping the edge-stack image (3.7.2) for the emissary-ingress image (3.8.2)

**Additional questions**
- Is it safe to swap the edge-stack image with the emissary-ingress image?, do they have 1:1 compatibility? are there any issues that could occur when doing that?
