### ISSUE TITLE
TLS termination broken in 0.35.0

### ISSUE THREAD

**Issue by croeck** [datawire/ambassador#573]
ROOT CAUSE AND WORKAROUND from @kflynn
====================================

This is a configuration bug in 0.35.0 and earlier that will affect TLS termination using certificates in the `ambassador-certs` secret _and_ additional TLS configuration in a `tls` `Module`.

It will be fixed in 0.35.1, but as a workaround, you can explicitly set the certificate paths by including

```
    cert_chain_file: /ambassador/certs/tls.crt
    private_key_file: /ambassador/certs/tls.key
```

in the `server` block in your `tls` `Module`. (If you're doing client-cert auth, too, you'll need to set

```
    cacert_chain_file: /ambassador/cacert/tls.crt
```

in the `client` block.

A complete example:

```yaml
---
apiVersion: ambassador/v0
kind:  Module
name:  tls
config:
  server:
    enabled: True
    use_remote_address: True
    redirect_cleartext_from: 80
    cert_chain_file: /ambassador/certs/tls.crt
    private_key_file: /ambassador/certs/tls.key

  client:
    enabled: False
    cacert_chain_file: /ambassador/cacert/tls.crt
```

Original bug report from @croeck
========================

**Describe the bug**

Ambassador does not start after the upgrade to 0.35.0 and is stuck in a crash loop.
The error out of the logs is:

```
source/server/config_validation/server.cc:48] error initializing configuration '/ambassador/ambassador-config-1-envoy.json': unable to read file: /etc/certs/tls.crt
```

I upgrade from 0.34.2 where everything was working fine. There was no other change than the version number.

**To Reproduce**

Configuration:

```
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
        client:
          enabled: False
```

**Expected behavior**
Ambassador works as usual and starts with TLS termination

**Versions (please complete the following information):**
 - Ambassador: 0.35.0
 - Kubernetes environment Azure via acs-engine
 - Version 1.1.0.4

**Additional context**
- Certificates are provided by cert-manager and are available
- I saw a commit by @kflynn towards this issue. He changed the directory where certs are copied to from `/etc/certs` to `/ambassador/certs` in https://github.com/datawire/ambassador/commit/ad57626605e32c2d8756f4389db9d5d5abcf2e29

**Comment by containscafeine** [comment]
Update: I am able to reproduce this.

**Comment by containscafeine** [comment]
This only breaks when `redirect_cleartext_from` is set. The original TLS module config is being overwritten.

**Comment by kflynn** [comment]
@croeck I updated the bug description with the root cause and the workaround (so that hopefully anyone else searching for this can see it more easily). Full fix coming in 0.35.1, but there's a workaround above now -- many thanks!

**Comment by davidsmithrx** [comment]
I'm still seeing this same error in 0.35.2. Trying the workaround produces the same error but with a different cert path.

> [critical][main] source/server/config_validation/server.cc:48] error initializing configuration '/ambassador/ambassador-config-1-envoy.json': unable to read file: /etc/certs/tls.crt

Configuration:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  namespace: ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: ambassador
      config:
        service_port: 8443
        use_proxy_proto: true
        use_remote_address: true
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 8080
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: ambassador-http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    service: ambassador
```

**Versions (please complete the following information):**

Ambassador: 0.35.2
Kubernetes environment: kops created in AWS
Version 1.9.9
