### ISSUE TITLE
CORS and headers do not play nicely together

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#574]
Per @azab on Slack:

```
cors:
 origins: "*"
 headers: x-api-key
 exposed_headers: Location
headers:
 x-api-key: foobar
```

does not work, while:

```
cors:
 origins: "*"
 headers: x-api-key
 exposed_headers: Location
```

does work. In the first, the response to preflight request doesn't pass access control check: No `Acces-Control-Allow-Origin` header is present on the requested resource.

**Comment by artjomzab** [comment]
BTW, adding methods

    methods: OPTIONS, GET 

does not solve the problem. 

```
OPTIONS https://myservice.tld 404 (Not Found)

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by nadilas** [comment]
Same here

```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by nadilas** [comment]
Quick summary on why this is the case:
1. Browsers won't send custom headers in preflight requests, no matter what. This is by design; the purpose of the preflight request is to determine what information the useragent (browser) is permitted to send beyond the "simple" stuff defined in the CORS spec. Thus, for the useragent to send any non-simple data (such as your custom header) as part of the preflight request is self-defeating. (https://stackoverflow.com/a/13997235)
2. Hence the  OPTIONS being rejected because it doesn't have the custom header.
3. No routes are matched, since the `match.headers` prerequisite is missing.
4. `404` is returned in response to no routes being found. Which in turn fails the complete request.

Brainstorming:
1. Implement a per `!service!` route, where no `match.headers` is present to allow for configuring a CORSresponse for that service (Note: The limitation is that the multiple endpoints defined via the `match.headers` will have the same `CORS` response.
    
    > e.g. Environment switching?
    > ```yaml
    > getambassador.io/config: |
    >  ---
    >  apiVersion: ambassador/v1
    >  kind: Module
    >  name: ambassador
    >  config:
    >    enable_grpc_web: True
    >    service_port: 8080
    >  ---
    >  apiVersion: ambassador/v1
    >  kind:  Mapping
    >  name:  grpc_app_cors_responder_mapping
    >  prefix: /srvapp.Service/
    >  rewrite: /srvapp.Service/
    >  grpc: True
    >  service: app-staging:8000
    >  cors:
    >    origins: http://prod.subdomain.mydomain.com,http://dev.subdomain.mydomain.com,http://stg.subdomain.mydomain.com,http://localhost:8080
    >   methods: GET, POST, OPTIONS
    >   headers: Content-Type, x-grpc-web, x-app-environment
    >  ---
    >  apiVersion: ambassador/v1
    >  kind:  Mapping
    >  name:  grpc_app_staging_mapping
    >  prefix: /srvapp.Service/
    >  rewrite: /srvapp.Service/
    >  grpc: True
    >  service: app-staging:8000
    >  headers:
    >    x-app-environment: staging
    > ```
2. check other possibilites?

I can confirm that the follow works on 0.53.1:
```yaml
    ---
    apiVersion: ambassador/v1
    kind:  Mapping
      name:  grpc_app_cors_responder_mapping
      prefix: /srvapp.Service/
      rewrite: /srvapp.Service/
      grpc: True
      service: app-staging:8000
      cors:
        origins: http://prod.subdomain.mydomain.com,http://dev.subdomain.mydomain.com,http://stg.subdomain.mydomain.com,http://localhost:8080
       methods: GET, POST, OPTIONS
       headers: Content-Type, x-grpc-web, x-app-environment
```

@richarddli what do you think?
