### ISSUE TITLE
Error when accessing (RBAC) to the endpointslices resource in version v3.10.0

### ISSUE THREAD

**Issue by juanjoku** [datawire/ambassador#5844]
We have tested the new v3.10 version, installing it using the YAMLs available at https://app.getambassador.io/yaml/emissary/3.10.0/emissary-emissaryns.yaml (we have not used HELM).

There are errors in logs:

```
reflector.go:166
"Unhandled Error" 
err="pkg/kates/client.go:469: Failed to watch *unstructured.Unstructured: 
can't watch endpointslices.v1.discovery.k8s.io: forbidden" logger="UnhandledError"

```
Indeed, YAML/RBACs do not enable access to this newly incorporated resource.

It is missing, of course, something similar to this (I don't know if these verbs are sufficient):

```
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch

```

**Comment by 2hat-roberio** [comment]
I just found the same error while deploying version 3.10.0 to my testing environment. 
Does anyone know what is the impact on this error ? 
Is there a way we can workaround it ? 
Thank you.

**Comment by 2hat-roberio** [comment]
Thank you @juanjoku. I'm using helm. For this scenario the workaround was to create an extra ClusterRole with the correct label. Having this label the Emissary ClusterRole will select this permissions as well.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emissary-ingress-permission-workaround  
  labels:
    rbac.getambassador.io/role-group: emissary-ingress
rules:
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch

```
