### ISSUE TITLE
forward requests to an destination external to K8s

### ISSUE THREAD

**Issue by pourquoi42** [datawire/ambassador#585]
It is great to have ambassador as an K8s api gateway for K8s services. But in my setup, not all services are in K8s. Some of them are in a neighbouring docker swarm based landscape. It would be awkward to have 2 api-gateways, so ideally, I'd like to only maintain ambassador as an api-gateway that also can forward requests to K8s-external URLs. I couldn't find any info on whether this is possible (without introducing yet another service just for the outgoing forwarding).

**Comment by kflynn** [comment]
Ambassador can definitely route to things outside its cluster -- just make sure that the `service` element of your `Mapping` is resolvable to the right thing (or use an IP address).

We actually use this to route to `httpbin.org` in our demo config:

```yaml
---
apiVersion: ambassador/v0
kind:  Mapping
name:  httpbin_mapping
prefix: /httpbin/
service: httpbin.org:80
host_rewrite: httpbin.org
```

(The `host_rewrite` is there because `httpbin.org` uses virtual hosting based on the `Host` header, so we have to make sure it's set correctly.)
