### ISSUE TITLE
Mounting secrets to /etc/certs makes ambassador not switch to 443 automatically

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#628]
When we mount certs manually on `/etc/certs` ambassador does not turn on TLS by opening an envoy listener on 443.
When we try doing that explicitly by adding a TLS Module config like -
```yaml
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
```
it still does not work.

Which means that ambassador is not reading the TLS module config if it finds certs at `/etc/certs`.

Expected behavior:
If certs are found at `/etc/certs`, then ambassador should start a listener on 443 and configure the certs in envoy's config.

From an implementation PoV, we could lose the checks in the code that check for `/etc/certs`, instead we could unify the behavior of findings certs in the order of precedence in one function and set something like `certs_found = True` and use that to make decisions throughout the code.

**Comment by containscafeine** [comment]
Update:
Actually setting -
```
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
```
worked out fine.
This is a documentation thing which has been fixed by ea89e7edda1d9ff6d275c2be7c34a201df96533d
