### ISSUE TITLE
Auth and WebSockets don't work well together

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#670]
One user reports on Slack -

Hi I am getting into a strange issue using a backend service with external auth. I configure all the services as per the docs. My backend service is configured at prefix /asr and my auth service is configured at prefix /extauth now when i call my service with ws://ip:port/asr it does not go to auth service but i am able to call my service fine which seems wrong but if i change the request to ws://ip:port/xyz the request is sent to auth service just fine . I am confused why this is happening

Service:
```yaml
getambassador.io/config: |
     ---
     apiVersion: ambassador/v0
     kind:  Mapping
     name:  mmasr_mapping
     prefix: /asr
     rewrite: /
     service: mmasr:10000
     use_websocket: true
     host_rewrite: mmasr
```

Auth:
```yaml
getambassador.io/config: |
     ---
     apiVersion: ambassador/v0
     kind:  AuthService
     name:  authentication
     auth_service: "mmasrauth:6000"
     path_prefix: "/extauth"
     allowed_headers:
     - "x-asr-session"
```

Another user -
Is there any trick for getting websockets working with an auth service running in the cluster? I've got a ton of services and everything is working perfectly with my auth service. But any websocket requests are always returned with a 400 (Bad Request). As far as I can tell, the request never hits my auth service.
I can even verify this by adding/removing the upgrade header and hitting the same URL with cURL. (edited)
I am running 0.34.1 (before the websocket regression).
