### ISSUE TITLE
External Authentication supports Json Web Tokens (JWT)

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#68]
Ambassador needs to support Json Web Token ("JWT") an an authentication mechanism.

Information we need to collect:
- Which algorithms?
- Does it need to handle authorization as well as authentication (e.g. checking that the requested resource can be accessed with the claims attached to the JWT)

Outputs:
- There is an External Authentication Service implementation with JWT
- There is documentation for installing and configuring the JWT External Authentication Service.

**Comment by ethanrubio** [comment]
My company is evaluating service meshes and currently uses JWTs with NGNIX to listen on every request to update and validate JWTs. Would this mean that ambassador would be able to do something similar to NGINX's Authentication Based on Subrequest?

**Comment by richarddli** [comment]
We just released Ambassador 0.9.0 today, which supports an external authentication service (see http://www.getambassador.io/user-guide/mappings.html#external-authentication) for details. Ambassador does *not* currently natively support JWT (that's what this issue is about).

Given the support for an external authentication service, does that meet your needs? If not, specifics about what additional support you would need would be great!

**Comment by ethanrubio** [comment]
Ambassador sends a POST request to the External Auth, but my use case sends a GET request to my external auth. Would this be possible to configure?

**Comment by kflynn** [comment]
The external auth service gets enough information to do this kind of check, yes. As Richard notes, knowing more about the specifics of how you use JWT (which signing method, etc) would be interesting too!

**Comment by richarddli** [comment]
> Ambassador sends a POST request to the External Auth, but my use case sends a GET request to my external auth. Would this be possible to configure?

@ethanrubio for some reason, GitHub lost your comment (I got it in email). This isn't supported today, but we could easily add it. I've opened https://github.com/datawire/ambassador/issues/73 to track this issue.

**Comment by kminehart** [comment]
Check out one I just made.

https://github.com/kminehart/abassador-auth-jwt

**Comment by kflynn** [comment]
Whoa! That's great, @kminehart -- we'll check it out! :)

**Comment by kminehart** [comment]
It's not perfect, I just made it yesterday/today. Any feedback would be appreciated.

Thanks! :)

**Comment by kflynn** [comment]
@kminehart It might be worth including a sample Ambassador `auth.yaml` in your README -- is this what you use?

```yaml
---
apiVersion: ambassador/v0
kind:  Module
name:  authentication
config:
  auth_service: {whatever you need}
  allowed_headers:
  - "x-jwt-payload"
```

?

**Comment by kminehart** [comment]
```
---
apiVersion: ambassador/v0
kind:  Module
name:  authentication
config:
  auth_service: {whatever you need}
  allowed_headers:
  - "Authorization"
```

To my understanding, JWTs are by convention provided as `Authorization: Bearer xxxxxxxxxx`, so that's the only thing I left unconfigurable.
