### ISSUE TITLE
gRPC with TLS is not working for me

### ISSUE THREAD

**Issue by maximematheron** [datawire/ambassador#690]
Hello everybody,

I followed the tutorial for TLS termination. 
It is perfectly working for non-gRPC deployments. 

The issue is when i try to use TLS with gRPC. The gRPC server is started with some credentials 

```
tlsCreds, err := credentials.NewServerTLSFromFile("certs/fullchain.pem", "certs/privkey.pem")
```

I deploy this just like it is said in the documentation:

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: helloworld-tls
  name: helloworld-tls
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: grpc_mapping_helloworld_tls
      grpc: true
      prefix: /helloworld.Greeter/
      rewrite: /helloworld.Greeter/
      service: helloworld-tls.ms-dev
      ambassador_id: ambassador-tls
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: helloworld-tls
    targetPort: grpc-api
  selector:
    service: helloworld-tls
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-tls
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: helloworld-tls
    spec:
      containers:
      - name: helloworld-tls
        image: [MY_IMAGE]
        ports:
        - name: grpc-api
          containerPort: 50151
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
      restartPolicy: Always
```

When i try to ping Ambassador with a client using TLS and the same certs (used for my domain name on top of the external IP of the ambassador svc), i got the given issue:

```
upstream connect error or disconnect/reset before headers
```

I can read the logs of Ambassador's pods, and I can see that the ambassador is routing to the right service, but the server seems to be closing the communication:

<img width="1378" alt="capture d ecran 2018-08-02 a 19 34 46" src="https://user-images.githubusercontent.com/22519198/43600884-21e9c360-968c-11e8-9842-62176359fe51.png">

The TLS communication is fine in my computer, even when I forward the port of the pods of the deploy on my machine. 

Do you have an idea?

Thanks,
Maxime
