### ISSUE TITLE
Ambassador Diag Crashed

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#700]
**Describe the bug**
Applying routing rules caused Ambassador to crash. 

**To Reproduce**

YAML:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kubernaut-ambassador-stub
  namespace: kubernaut
  annotations:
    getambassador.io/config: |
      #
      # HOST ROUTES: The most common access method
      #

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-http-hostroute
      host: ^next\.kubernaut\.io(:443)?$
      host_regex: true
      service: kubernaut-public

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-ws-hostroute
      prefix: /ws
      rewrite: /ws
      host: ^next\.kubernaut\.io(:443)?$
      host_regex: true
      use_websocket: true
      service: kubernaut-public

      #
      # PATH ROUTES: "Current" (a.k.a "public") version entrypoints
      #

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-http-pathroute
      prefix: /current/
      rewrite: /
      service: kubernaut-public

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-http-pathroute-notrailingslash
      prefix: /current
      rewrite: /
      service: kubernaut-public

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-ws-pathroute
      prefix: /current/ws/
      rewrite: /ws
      use_websocket: true
      service: kubernaut-public

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-ws-pathroute-notrailingslash
      prefix: /current/ws
      rewrite: /ws
      use_websocket: true
      service: kubernaut-public

      #
      # PATH ROUTES: "Beta" (a.k.a "private") version entrypoints
      #

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-http-pathroute
      prefix: /beta/
      rewrite: /
      service: kubernaut-private

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-http-pathroute-notrailingslash
      prefix: /beta
      rewrite: /
      service: kubernaut-private

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-ws-pathroute
      prefix: /beta/ws/
      rewrite: /ws
      use_websocket: true
      service: kubernaut-private

      ---
      apiVersion: ambassador/v0
      kind: Mapping
      ambassador_id: kubernaut
      name: kubernaut-public-ws-pathroute-notrailingslash
      prefix: /beta/ws
      rewrite: /ws
      use_websocket: true
      service: kubernaut-private
    forge.repo: git@github.com:datawire/kubernaut-backend.git
    forge.descriptor: service.yaml
    forge.version: 019fda54050467256489d32b1db41b2fd56a4a78.sha
  labels: {forge.service: kubernaut-controller, forge.profile: beta}
spec:
  type: ClusterIP
  clusterIP: None

```

**Expected behavior**
Refresh diag service and see changes.

**What happened?**

Diag UI just shows `server error`

**Logs**

```text
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:41 kubewatch 0.37.0 INFO: generating config with gencount 4 (1 change)
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:41 kubewatch 0.37.0 ERROR: could not restart Envoy
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/ambassador/kubewatch.py", line 124, in run
ambassador-6d846d5f7c-txhz6 ambassador     self.restart()
ambassador-6d846d5f7c-txhz6 ambassador   File "/ambassador/kubewatch.py", line 133, in restart
ambassador-6d846d5f7c-txhz6 ambassador     config = self.generate_config(output)
ambassador-6d846d5f7c-txhz6 ambassador   File "/ambassador/kubewatch.py", line 166, in generate_config
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(output)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:44 diagd 0.37.0 [P62TThreadPoolExecutor-0_4] ERROR: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 95, in wrapper
ambassador-6d846d5f7c-txhz6 ambassador     result = f(*args, reqid=reqid, **kwds)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 450, in show_intermediate
ambassador-6d846d5f7c-txhz6 ambassador     result = aconf(app).get_intermediate_for(source)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 146, in aconf
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(latest)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:44 diagd 0.37.0 [P62TThreadPoolExecutor-0_4] ERROR: DFCB5685-36BE-4FFD-9470-43C78418EC99: 127.0.0.1 "GET /ambassador/v0/diag/grp-50aa4d6cbec9d52c9ecc1e0fcb4dfb56b7ca65f7" 34ms 500 server error
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:45 diagd 0.37.0 [P62TThreadPoolExecutor-0_5] ERROR: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 95, in wrapper
ambassador-6d846d5f7c-txhz6 ambassador     result = f(*args, reqid=reqid, **kwds)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 450, in show_intermediate
ambassador-6d846d5f7c-txhz6 ambassador     result = aconf(app).get_intermediate_for(source)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 146, in aconf
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(latest)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:45 diagd 0.37.0 [P62TThreadPoolExecutor-0_5] ERROR: AFB853B5-E2CD-4AA8-8199-580626E5BFAF: 127.0.0.1 "GET /ambassador/v0/diag/grp-50aa4d6cbec9d52c9ecc1e0fcb4dfb56b7ca65f7" 95ms 500 server error
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:46 diagd 0.37.0 [P62TThreadPoolExecutor-0_6] ERROR: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 95, in wrapper
ambassador-6d846d5f7c-txhz6 ambassador     result = f(*args, reqid=reqid, **kwds)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 450, in show_intermediate
ambassador-6d846d5f7c-txhz6 ambassador     result = aconf(app).get_intermediate_for(source)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 146, in aconf
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(latest)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:46 diagd 0.37.0 [P62TThreadPoolExecutor-0_6] ERROR: F02CF9D2-97E1-41A3-A866-C94BD5AFE899: 127.0.0.1 "GET /ambassador/v0/diag/grp-50aa4d6cbec9d52c9ecc1e0fcb4dfb56b7ca65f7" 61ms 500 server error
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:47 diagd 0.37.0 [P62TThreadPoolExecutor-0_0] ERROR: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 95, in wrapper
ambassador-6d846d5f7c-txhz6 ambassador     result = f(*args, reqid=reqid, **kwds)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 450, in show_intermediate
ambassador-6d846d5f7c-txhz6 ambassador     result = aconf(app).get_intermediate_for(source)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 146, in aconf
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(latest)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:47 diagd 0.37.0 [P62TThreadPoolExecutor-0_0] ERROR: C9B4AAE8-301A-4173-853A-64BFCDF44B8A: 127.0.0.1 "GET /ambassador/v0/diag/grp-50aa4d6cbec9d52c9ecc1e0fcb4dfb56b7ca65f7" 32ms 500 server error
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:48 diagd 0.37.0 [P62TThreadPoolExecutor-0_7] ERROR: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 95, in wrapper
ambassador-6d846d5f7c-txhz6 ambassador     result = f(*args, reqid=reqid, **kwds)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 450, in show_intermediate
ambassador-6d846d5f7c-txhz6 ambassador     result = aconf(app).get_intermediate_for(source)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 146, in aconf
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(latest)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:48 diagd 0.37.0 [P62TThreadPoolExecutor-0_7] ERROR: 244895C6-8BA8-4BEF-96C9-2C6E59C3D8A2: 127.0.0.1 "GET /ambassador/v0/diag/grp-50aa4d6cbec9d52c9ecc1e0fcb4dfb56b7ca65f7" 33ms 500 server error
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:57 diagd 0.37.0 [P62TThreadPoolExecutor-0_5] ERROR: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 95, in wrapper
ambassador-6d846d5f7c-txhz6 ambassador     result = f(*args, reqid=reqid, **kwds)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 409, in show_overview
ambassador-6d846d5f7c-txhz6 ambassador     ov = aconf(app).diagnostic_overview()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 146, in aconf
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(latest)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:57 diagd 0.37.0 [P62TThreadPoolExecutor-0_5] ERROR: 24573921-9BEC-43AB-A048-7A6400315523: 127.0.0.1 "GET /ambassador/v0/diag/" 33ms 500 server error
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:59 diagd 0.37.0 [P62TThreadPoolExecutor-0_3] ERROR: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador Traceback (most recent call last):
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 95, in wrapper
ambassador-6d846d5f7c-txhz6 ambassador     result = f(*args, reqid=reqid, **kwds)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 409, in show_overview
ambassador-6d846d5f7c-txhz6 ambassador     ov = aconf(app).diagnostic_overview()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador_diag/diagd.py", line 146, in aconf
ambassador-6d846d5f7c-txhz6 ambassador     aconf = Config(latest)
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 352, in __init__
ambassador-6d846d5f7c-txhz6 ambassador     self.process_all_objects()
ambassador-6d846d5f7c-txhz6 ambassador   File "/usr/lib/python3.6/site-packages/ambassador-0.37.0-py3.6.egg/ambassador/config.py", line 450, in process_all_objects
ambassador-6d846d5f7c-txhz6 ambassador     allowed_ids = obj.get('ambassador_id', 'default')
ambassador-6d846d5f7c-txhz6 ambassador AttributeError: 'NoneType' object has no attribute 'get'
ambassador-6d846d5f7c-txhz6 ambassador 2018-08-05 01:52:59 diagd 0.37.0 [P62TThreadPoolExecutor-0_3] ERROR: 4BD38566-2440-4BFD-91C2-EF53E4C9BE89: 127.0.0.1 "GET /ambassador/v0/diag/" 96ms 500 server error
```

**Versions (please complete the following information):**
 - Ambassador: 0.37.0
 - Kubernetes environment: GKE
 - Version 1.10.x

**Additional context**
