### ISSUE TITLE
Canary relaeases invalid traffic distribution

### ISSUE THREAD

**Issue by exu** [datawire/ambassador#719]
When setting canary release I've getting invalid (looks randomly) requests distribution during tests. 

I've configured two services (simple go based binaries which responds with plaintext) with weights set up in annotations on service definition in YAML. 

Ambassador admin panel show that it's ok: 
![ambassador admin panel](https://image.ibb.co/nR4RgU/20180809_1216x300_rect.jpg)

v1 service YAML
```
# Source: example-go-service/templates/service.yml
apiVersion: v1
kind: Service
metadata:
  name: go-v1-example-go-service
  labels:
    example: go-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  go-v1-example-go-service
      prefix: /go/
      service: go-v1-example-go-service
      

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8801
  selector:
    example: go-service
  type: LoadBalancer
```

v2 service YAML: 
```
# Source: example-go-service/templates/service.yml
apiVersion: v1
kind: Service
metadata:
  name: go-v2-example-go-service
  labels:
    example: go-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  go-v2-example-go-service
      prefix: /go/
      service: go-v2-example-go-service
      weight: 5

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8801
  selector:
    example: go-service
  type: LoadBalancer

```

Both services have 2 replicas

I've put some traffic to ambassador (several tests) each 10000 requests with 100 concurrent traffic. 

Percentage distribution of pods
```
TEST1
Total: 10000
Hell(o) World from go-v1-example-go-service-5484575d7b-t9gg2: 34.88%
Hell(o) World from go-v2-example-go-service-9756f4cdc-kdv6n: 35.90%
Hell(o) World from go-v2-example-go-service-9756f4cdc-j822s: 19.77%
Hell(o) World from go-v1-example-go-service-5484575d7b-7znjw: 9.45%

TEST2
Hell(o) World from go-v1-example-go-service-5484575d7b-7znjw: 4.10%
Hell(o) World from go-v2-example-go-service-9756f4cdc-kdv6n: 45.36%
Hell(o) World from go-v2-example-go-service-9756f4cdc-j822s: 20.10%
Hell(o) World from go-v1-example-go-service-5484575d7b-t9gg2: 30.44%


TEST3
Total: 10000
Hell(o) World from go-v1-example-go-service-5484575d7b-t9gg2: 36.93%
Hell(o) World from go-v1-example-go-service-5484575d7b-7znjw: 10.25%
Hell(o) World from go-v2-example-go-service-9756f4cdc-j822s: 20.12%
Hell(o) World from go-v2-example-go-service-9756f4cdc-kdv6n: 32.70%

TEST4 
Total: 10000
Hell(o) World from go-v1-example-go-service-5484575d7b-7znjw: 13.11%
Hell(o) World from go-v2-example-go-service-9756f4cdc-j822s: 13.64%
Hell(o) World from go-v1-example-go-service-5484575d7b-t9gg2: 34.11%
Hell(o) World from go-v2-example-go-service-9756f4cdc-kdv6n: 39.14%

TEST5
Hell(o) World from go-v1-example-go-service-5484575d7b-t9gg2: 35.57%
Hell(o) World from go-v2-example-go-service-9756f4cdc-j822s: 8.15%
Hell(o) World from go-v1-example-go-service-5484575d7b-7znjw: 11.84%
Hell(o) World from go-v2-example-go-service-9756f4cdc-kdv6n: 44.44%


                       
```

**To Reproduce**
- setup two services in ambassador
- set annotations for each service (95/5 percentage distribution) 
- make some traffic to ambassadors service endpoint

**Expected behavior**
Traffic distribution among services should be `95%` to `5%`

**Versions (please complete the following information):**
 - Ambassador: 0.38
 - Kubernetes environment: Google Kubernetes Engine
 ```
Google Cloud SDK 207.0.0
app-engine-go 
app-engine-python 1.9.71
beta 2018.06.22
bq 2.0.34
core 2018.06.22
gsutil 4.32
```

**Additional context**
services generated with use of helm
