### ISSUE TITLE
increasing replicas from 1 to 2 or more causes ambassador to crash restart loop

### ISSUE THREAD

**Issue by zencircle** [datawire/ambassador#743]
**Describe the bug**
When increasing replica set from 1 to 2 or more causes replicas to crash
RBAC enabled

**To Reproduce**
kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml

**Expected behavior**
All 3 pods that are part of replica set should be running

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.38]
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
DCOS/Mesos Kubernetes Framework 
 - Version [e.g. 1.10.6]

**Additional context**
```
I have tried remove the statsd, liveness and readness probes and that does not solve the problem
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-admin
  name: ambassador-admin
spec:
  type: NodePort
  ports:
  - name: ambassador-admin
    port: 8877
    targetPort: 8877
  selector:
    service: ambassador
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
rules:
- apiGroups: [""]
  resources:
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["create", "update", "patch", "get", "list", "watch"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
- kind: ServiceAccount
  name: ambassador
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        service: ambassador
    spec:
      serviceAccountName: ambassador
      containers:
      - name: ambassador
#        image: quay.io/datawire/ambassador:0.39.0-rc0
        image: quay.io/datawire/ambassador:0.38.0
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace          
#        livenessProbe:
#          httpGet:
#            path: /ambassador/v0/check_alive
#            port: 8877
#          initialDelaySeconds: 30
#          periodSeconds: 3
#        readinessProbe:
#          httpGet:
#            path: /ambassador/v0/check_ready
#            port: 8877
#          initialDelaySeconds: 30
#          periodSeconds: 3
#      - name: statsd
#        image: quay.io/datawire/statsd:0.38.0
      restartPolicy: Always

kubectl get pod
NAME                          READY     STATUS             RESTARTS   AGE
ambassador-7fd4cdb8b5-fv6k6   0/1       CrashLoopBackOff   7          16m
ambassador-7fd4cdb8b5-t68rx   0/1       CrashLoopBackOff   6          11m
```

If replicaset=1 ambassador deploys successfully
```
kubectl delete -f amb/ambassador-rbac.yaml 
service "ambassador-admin" deleted
clusterrole.rbac.authorization.k8s.io "ambassador" deleted
serviceaccount "ambassador" deleted
clusterrolebinding.rbac.authorization.k8s.io "ambassador" deleted
deployment.extensions "ambassador" deleted

 kubectl apply -f amb/ambassador-rbac.yaml 
service "ambassador-admin" created
clusterrole.rbac.authorization.k8s.io "ambassador" created
serviceaccount "ambassador" created
clusterrolebinding.rbac.authorization.k8s.io "ambassador" created
deployment.extensions "ambassador" created

 kubectl get pod --watch
NAME                          READY     STATUS    RESTARTS   AGE
ambassador-7fd4cdb8b5-cg86d   1/1       Running   0          18s
```
Crash logs
```
[2018-08-24 17:15:43 +0000] [19] [INFO] Listening at: http://0.0.0.0:8877 (19)
[2018-08-24 17:15:43 +0000] [19] [INFO] Using worker: threads
[2018-08-24 17:15:43 +0000] [47] [INFO] Booting worker with pid: 47
2018-08-24 17:15:43 diagd 0.38.0 [P47TMainThread] INFO: Starting periodic updates
2018-08-24 17:15:58 kubewatch 0.38.0 INFO: generating config with gencount 2 (1 change)
/usr/lib/python3.6/site-packages/pkg_resources/__init__.py:1298: UserWarning: /ambassador is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
2018-08-24 17:16:03 kubewatch 0.38.0 WARNING: Scout: could not post report: HTTPSConnectionPool(host='kubernaut.io', port=443): Max retries exceeded with url: /scout (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d94e2d2b0>: Failed to establish a new connection: [Errno -3] Try again',))
2018-08-24 17:16:03 kubewatch 0.38.0 INFO: Scout reports {"latest_version": "0.38.0", "exception": "could not post report: HTTPSConnectionPool(host='kubernaut.io', port=443): Max retries exceeded with url: /scout (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d94e2d2b0>: Failed to establish a new connection: [Errno -3] Try again',))", "cached": false, "timestamp": 1535130958.199165}
[2018-08-24 17:16:03.269][50][info][config] source/server/configuration_impl.cc:50] loading 0 static secret(s)
[2018-08-24 17:16:03.271][50][info][upstream] source/common/upstream/cluster_manager_impl.cc:132] cm init: all clusters initialized
[2018-08-24 17:16:03.271][50][info][config] source/server/configuration_impl.cc:60] loading 1 listener(s)
[2018-08-24 17:16:03.281][50][info][config] source/server/configuration_impl.cc:94] loading tracing configuration
[2018-08-24 17:16:03.281][50][info][config] source/server/configuration_impl.cc:116] loading stats sink configuration
got SIGHUP
forking and execing new child process at epoch 1
forked new child process with PID=54
got SIGCHLD
PID=54 exited with code=1
Due to abnormal exit, force killing all child processes and exiting
force killing PID=22
exiting due to lack of child processes
AMBASSADOR: envoy exited with status 1
Here's the envoy.json we were trying to run with:
{
  "listeners": [
    
    {
      "address": "tcp://0.0.0.0:80",
      
      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {"codec_type": "auto",
            "stat_prefix": "ingress_http",
            "access_log": [
              {
                "format": "ACCESS [%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n",
                "path": "/dev/fd/1"
              }
            ],
            
            "route_config": {
              "virtual_hosts": [
                {
                  "name": "backend",
                  "domains": ["*"],"routes": [
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_ready","prefix_rewrite": "/ambassador/v0/check_ready","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_alive","prefix_rewrite": "/ambassador/v0/check_alive","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/","prefix_rewrite": "/ambassador/v0/","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    ,
                    
                    {
                      "timeout_ms": 3000,"prefix": "/httpbin/","prefix_rewrite": "/","host_rewrite": "httpbin.org","weighted_clusters": {
                              "clusters": [
                                  
                                    { "name": "cluster_httpbin_org_80", "weight": 100.0 }
                                  
                              ]
                          }

                      
                    }
                    
                    
                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "cors",
                "config": {}
              },{"type": "decoder",
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    }
  ],
  "admin": {
    "address": "tcp://127.0.0.1:8001",
    "access_log_path": "/tmp/admin_access_log"
  },
  
  "cluster_manager": {
    "clusters": [
      {
        "name": "cluster_127_0_0_1_8877",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",        
        "hosts": [
          {
            "url": "tcp://127.0.0.1:8877"
          }
          
        ]},
      {
        "name": "cluster_httpbin_org_80",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",        
        "hosts": [
          {
            "url": "tcp://httpbin.org:80"
          }
          
        ]}
      
    ]
  },
  
  "statsd_udp_ip_address": "127.0.0.1:8125",
  "stats_flush_interval_ms": 1000
}AMBASSADOR: shutting down (1)
```
