### ISSUE TITLE
Using cert-manager acme http01 validation with Ambassador

### ISSUE THREAD

**Issue by mprigge** [datawire/ambassador#780]
I am new to Ambassador, so please bear with my ignorance here. 

I am attempting to determine how to get ambassador to work with cert-manager using http01 validation. Any documented reference I see to cert-manager and Ambassador together seem to use the dns01 validation mechanism. Is it possible to use the http mechanism also? 

If so, generally how is this accomplished? It's easy enough to manually create a service with an ambassador mapping annotation which routes the `/.well-known/acme-challenge/` prefix, but I'm not certain what is supposed to actually respond to this. 

Edited to add:

I've seen a few examples of how to get cert-manager working with istio ingress that seem to suggest that you'd create an Ingress/Service pair with a service selector based on the `certmanager.k8s.io/domain` label. That approach seems like it'd work with Ambassador, also (except with a Service mapping annotation instead of an Ingress). However, that label does not appear on the `cm-acme-http-solver` pods created by cert-manager to validate the http01 requests.  So, I'm not sure if that label is used by cert-manager anymore.

**Comment by mprigge** [comment]
Okay - I think I sorted out what's happening here. For anyone else who happens across this, the reason the `certmanager.k8s.io/domain` label isn't present is because it was replaced by a hashed domain name to support domains longer than the limits of a label. More info [here](https://github.com/jetstack/cert-manager/blob/4b576a2f3e3c0c48f505188083b0dbfdc839bc08/pkg/issuer/acme/http/pod.go#L38-L41).

As far as the service, I had to actually look at the [source](https://github.com/jetstack/cert-manager/blob/master/pkg/issuer/acme/http/solver/solver.go) of the cm-acme-http-solver container to see what its problem was. The ambassador map for the service had to retain the hostname and not rewrite the prefix.  

So, something like this:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chartname.secretName" . }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ template "chartname.secretName" . }}
      prefix: /.well-known/acme-challenge/
      rewrite: ""
      host: {{ template "chartname.hostname" . }}
      host_rewrite: {{ template "chartname.hostname" . }}
      service: {{ template "chartname.secretName" . }}
spec:
  ports:
  - port: 80
    targetPort: 8089
  selector:
    certmanager.k8s.io/acme-http-domain: <adler32 hash of chartname.hostname>
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "chartname.secretName" . }}
spec:
  secretName: {{ template "chartname.secretName" . }}
  issuerRef:
    name: {{ .Values.tls.issuer }}
    kind: ClusterIssuer
  commonName: {{ template "chartname.hostname" . }}
  dnsNames:
  - {{ template "chartname.hostname" . }}
  acme:
    config:
    - http01:
        ingressClass: not-there
      domains:
      - {{ template "ichartname.hostname" . }}
```
