### ISSUE TITLE
Additive rewrites with regex prefixes

### ISSUE THREAD

**Issue by amargherio** [datawire/ambassador#805]
## Use case/problem
When setting a prefix regex for a service with a single endpoint, such as an orders service, I want to be able to rewrite the path by prepending to the specified prefix. A suitable use case might be running multiple versions of a service, where request without a version are rewritten to point to the latest production version of a service. 

i.e. 
```yaml
apiVersion: ambassador/v0
kind: Mapping
method: GET
name: service_latest_rewrite
prefix: /orders/
rewrite:  /latest/
service: orders
---
apiVersion: ambassador/v0
kind: Mapping
method: GET
name: service_v1_rewrite
prefix: /v1/
rewrite: ""
service: orders
```

## Proposed solution
When the above YAML is passed into Ambassador, I'd like to see the rewrite appended to the prefix, so the matching path of `/orders/19/status/` would turn into `/latest/orders/19/status/`. This could potentially be enabled using a `rewrite_prepend: true` attribute in the Mapping object to make it clear that prepending to the matching prefix value is enabled.

## Alternatives considered
I've considered trying to implement this logic into the Nginx ingress controller sitting in front of Ambassador.

## Additional Context
Currently, this functionality isn't supported by Envoy, but there's an open PR for implementing it https://github.com/envoyproxy/envoy/pull/4403
