### ISSUE TITLE
Use relative URLs in Diagnostics UI

### ISSUE THREAD

**Issue by xadhatter** [datawire/ambassador#812]
**Please describe your use case / problem.**
I would like to expose the Diagnostics UI under a URL of my choice, however, because absolute URLs for the hyperlinks within the page are used this is difficult.

**Describe the solution you'd like**
I would like to expose the Diagnostics UI using a mapping such as:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador-diag
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ambassador-diag_mapping
      prefix: /admin/gateway/
      rewrite: /ambassador/v0/diag/
      service: ambassador-diag
spec:
  ports:
   - port: 80
     targetPort: 8877
...
```
When a link on the Diagnostics UI is clicked it should use the existing URL prefix which will then be rewritten by the Mapping.
