### ISSUE TITLE
Write-up how to configure the Lyft RLS with Ambassador.

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#863]
Possible config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: ambassador
data:
  config-messaging.yaml: |
    domain: ambassador # domain must be ambassador
    descriptors:
      - key: instance_id
        rate_limit:
          unit: day
          requests_per_unit: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit-svc
  namespace: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: RateLimitService
      name: ratelimit
      service: "ratelimit-svc:8081"
spec:
  type: ClusterIP
  ports:
  - port: 8081
    name: grpc
    protocol: TCP
  - port: 8080
    name: http
    protocol: TCP
  selector:
    service: ambassador-ratelimit
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratelimit
  namespace: ambassador
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: ambassador-ratelimit
    spec:
      volumes:
      - name: config
        configMap:
          name: ratelimit-config
          items:
          - key: config-messaging.yaml
            path: stuff/ratelimit/config/config.yaml
      containers:
      - name: lyft-ratelimit
        image: lyft-ratelimit-container
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: grpc
            containerPort: 8081
            protocol: TCP
          - name: debug
            containerPort: 6070
            protocol: TCP 
        #command: ["nc"]
        #args: ["-lk", "-n", "-p8081"]
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: REDIS_SOCKET_TYPE
          value: "tcp"
        - name: REDIS_URL
          value: "redis-ratelimit-svc:6379"
        - name: RUNTIME_ROOT
          value: "/data/stuff"
        - name: RUNTIME_SUBDIRECTORY
          value: "ratelimit"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: GRPC_PORT
          value: "8081"
        - name: DEBUG_PORT
          value: "6070"
        - name: USE_STATSD
          value: "false"
        volumeMounts:
        - name: config
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit-diag
  namespace: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  ratelimit_diag
      prefix: /rate/diag/
      service: ratelimit-diag
spec:
  selector:
    service: ambassador-ratelimit
  ports:
  - port: 80
    name: debug
    targetPort: 6070
```
