### ISSUE TITLE
EA doesn't seem to like `alpn_protocols: h2`.

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#881]
**Describe the bug**
EA doesn't seem to like `alpn_protocols: h2`. Connections timeout when `alpn_protocols: h2` is present in the TLS module. Ambassador does not crash and does not log any error or requests. 
cURL error:
```bash
curl -v https://<ambassador-ex-ip>/httpbin/
*   Trying 35.227.87.184...
* TCP_NODELAY set
* Connected to nkrause-ambassador.k736.net (35.227.87.184) port 443 (#0)
* Operation timed out after 300244 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 300244 milliseconds with 0 out of 0 bytes received
```

**To Reproduce**
Configure tls with `alpn_protocols: h2`
```yaml
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  tls
      ambassador_id: ambassador-tls
      config:
        server:
          enabled: true
          secret: user-secret
          redirect_cleartext_from: 80
          alpn_protocols: h2
```

**Expected behavior**
Support for `alpn_protocols: h2`. 

**Versions (please complete the following information):**
 - Ambassador: 0.50.0-ea1
 - Kubernetes environment GKE
 - Version 1.9.7
