### ISSUE TITLE
StatsD exporter listens on port 9125 while Ambassador targets 8125

### ISSUE THREAD

**Issue by Xerodesign** [datawire/ambassador#914]
**Describe the bug**
The Ambassador documentation gives an overview of how to setup an independent StatsD exporter service in the "StatsD as an Independent Deployment" section of the statistics documentation (https://www.getambassador.io/reference/statistics). The documentation points the reader to an example yaml file, https://github.com/datawire/ambassador/blob/master/statsd-sink/prometheus/prom-statsd-sink.yaml, that creates a `statsd-sink` service using the `prom/statsd-exporter:v0.6.0` image and listening on ports `8125` (UDP) and `9102` (TCP).

Unfortunately the default `prom/statsd-exporter:v0.6.0` image listens on port `9125`, so the port definition of `8125` doesn't work as intended.

**To Reproduce**
1. Deploy the `statsd-sink` service from `https://github.com/datawire/ambassador/blob/master/statsd-sink/prometheus/prom-statsd-sink.yaml`
2. Configure the Ambassador deployment to have the `STATSD_ENABLED` environment variable set to "true"
3. Deploy Ambassador
4. See no stats are being received by `statsd-sink` from Ambassador

**Expected behavior**
`statsd-sink` should receive stats from Ambassador.

**Versions (please complete the following information):**
 - Ambassador: 0.40.0
 - Kubernetes environment: kops/AWS
 - Kubernets Version 1.9.6
 - Prometheus StatsD Exporter: 0.6.0

**Additional context**
We were able to work around the problem by adding a target port of `9125` to the `prom-statsd-sink.yaml` example. Similar to:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statsd-sink
[snip]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: statsd-sink
  name: statsd-sink
spec:
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 9125
    name: statsd-metrics
  - protocol: TCP
    port: 9102
    name: prometheus-metrics
  selector:
    service: statsd-sink
```

Another solution may be to allow the user to specify the StatsD port to target within the Ambassador config, something analogous to `STATSD_HOST`.
