### ISSUE TITLE
Ambassador crashes when using add_request_headers with DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT

### ISSUE THREAD

**Issue by caiobegotti** [datawire/ambassador#948]
Ok, this might get confusing because the debugging session took two whole days with @nbkrause:

Apparently both Ambassador 0.38.0 and 0.40.0 have an odd behavior when using add_request_headers and "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%" (I need this to be passed on my backends to do some geo-IP processing).

I was using 0.38.0 successfully with this header just fine, for weeks. Then for a random reason I had to delete the Ambassador pod and waited it to be recreated (I have a single replica). From then on I started getting the behavior of this bug. I tried to upgrade to 0.40.0 to no avail. It does not matter if it's using RBAC or not (apparently), or via Helm chart or not, nor if it's in the default or an alternative namespace.

If I use an annotation like below, Ambassador crashes EVERY TIME that I `curl` the host specified below:

```
kind: Service
apiVersion: v1
metadata:
  name: playground
  labels:
    name: playground
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: playground
      prefix: /
      host: playground.api.dev.internal.nymos.io
      add_request_headers:
        x-forwarded-for: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
      service: playground.dev
spec:
  selector:
    name: playground
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
```

Empty server reply with `curl`:

```
$ curl playground.api.dev.internal.nymos.io/v1/playground/ping -i -k -v
*   Trying 35.234.140.148...
* TCP_NODELAY set
* Connected to playground.api.dev.internal.nymos.io (35.234.140.148) port 80 (#0)
> GET /v1/playground/ping HTTP/1.1
> Host: playground.api.dev.internal.nymos.io
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host playground.api.dev.internal.nymos.io left intact
curl: (52) Empty reply from server
```

See the null pointer backtrace here (it is a big long to paste on Github), as I got it from the single Ambassador pod: https://pastebin.com/iw6vw1ZH

If I change the add_request_headers annotation to whatever else, apparently it does not crash Ambassador:

```
      add_request_headers:
        x-test: "test"
```

Before that previous pod deletion, even with 0.38.0, that additional header DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT worked ok, but now it makes Envoy to take Ambassador down with it. I cannot make any sense out of this 😢

 - Ambassador: 0.38.0 and 0.40.0
 - Kubernetes environment: GKE
 - Version: v1.10.6-gke.6

For more info and debugging steps search for DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT in the #ambassador channel of Datawire's Slack, as I talked to @nbkrause over there.
