### ISSUE TITLE
0.50.0-EA4: envoy_override is not applied

### ISSUE THREAD

**Issue by adaniline** [datawire/ambassador#951]
**Describe the bug**
envoy_override does not add hash_policy to a route config
In my service mapping:
```
        apiVersion: ambassador/v0
        kind:  Mapping
        name:  myapp-socketio
        prefix: /myapp/socket.io
        rewrite: /socket.io
        service: myapp
        use_websocket: true
        envoy_override:
          hash_policy:
            cookie:
              name: "NODE_ID"
              ttl: 
                seconds: 3600
              path: "/myapp/socket.io"
```
Here is envoy route config shown in the admin diagnostics:
```
{
    "match": {
        "case_sensitive": true,
        "headers": null,
        "prefix": "/myapp/socket.io"
    },
    "route": {
        "prefix_rewrite": "/socket.io",
        "priority": null,
        "weighted_clusters": {
            "clusters": [
                {
                    "name": "cluster_my_app",
                    "request_headers_to_add": null,
                    "weight": 100.0
                }
            ]
        }
    }
}
```
**Expected behavior**
hash_policy should be appended to Envoy route

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.50.0-ea4]
 - IBM Container Service
 - Version 1.10.8
