### ISSUE TITLE
AWS Load Balancer creates port 80 and 443 both with protocol SSL

### ISSUE THREAD

**Issue by krish512** [datawire/ambassador#977]
**Need to create AWS load balancer with SSL(443) and TCP(80) but creates SSL(443) and SSL(80)**

**YAML file used to reproduce**
```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-southeast-1:123123123:certificate/443abcde-cfgh-klmn-6789-b9876ab01c67"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "*"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  frontend-web_mapping
      prefix: /
      service: frontend-web:3000
spec:
  type: LoadBalancer
  ports:
  - name: ambassador-http
    port: 80
    targetPort: 80
  - name: ambassador-https
    port: 443
    targetPort: 443
  selector:
    service: ambassador
```

**Expected behavior**
Need to either have a way to specify protocols for AWS Load Balancer listeners protocols or should specify protocols correctly

How do I make sure that the global redirection works from 80 to 443 and also listeners are created on load balancers with correct protocols and ports?
