### ISSUE TITLE
TLS failure: `routines:CONNECT_CR_SRVR_HELLO:wrong version number`

### ISSUE THREAD

**Issue by samuela** [datawire/ambassador#995]
**Describe the bug**
For the life of me, I'm unable to get Ambassador to play nicely with SSL certs provided by cert-manager. Here's the story so far:

1. Running ambassador 0.40.1 in a namespace called "ambassador". 
<details><summary>YAML config</summary>

```yaml
# The namespace for all Ambassador related objects.
apiVersion: v1
kind: Namespace
metadata:
  name: ambassador
  labels:
    app: ambassador-proxy
---
# The admin service.
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-admin
  name: ambassador-admin
  namespace: ambassador
spec:
  type: NodePort
  ports:
    - name: ambassador-admin
      port: 8877
      targetPort: 8877
  selector:
    service: ambassador
---
# The ClusterRole that specifies behaviors that the Ambassador Pods require.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador
  namespace: ambassador
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["create", "update", "patch", "get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["get", "list", "watch"]
---
# ServiceAccount that is mounted on each of the Ambassador Pods.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
  namespace: ambassador
---
# Binding between the ClusterRole and ServiceAccout.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador
  namespace: ambassador
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador
subjects:
  - kind: ServiceAccount
    name: ambassador
    namespace: ambassador
---
# Deployment for the actual Ambassador Service.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
  namespace: ambassador
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        service: ambassador
    spec:
      # This is where that ServiceAccount is declared for the Pods.
      serviceAccountName: ambassador
      containers:
        - name: ambassador
          image: quay.io/datawire/ambassador:0.40.1
          resources:
            limits:
              cpu: 1
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 100Mi
          env:
            - name: AMBASSADOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: admin
              containerPort: 8877
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: 8877
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: 8877
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
---
# Finally, the Ambassador Service.
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  annotations:
    getambassador.io/config: |
      # From https://www.getambassador.io/user-guide/tls-termination/.
      apiVersion: ambassador/v0
      kind: Module
      name: tls
      config:
        # The 'server' block configures TLS termination. 'enabled' is the only
        # required element.
        server:
          # If 'enabled' is not True, TLS termination will not happen.
          enabled: True
          # If you set 'redirect_cleartext_from' to a port number, HTTP traffic
          # to that port will be redirected to HTTPS traffic. Typically you would
          # use port 80, of course.
          # redirect_cleartext_from: 80

          # These are optional. They should not be present unless you are using
          # a custom Docker build to install certificates onto the container
          # filesystem, in which case YOU WILL STILL NEED TO SET enabled: True
          # above.
          #
          # cert_chain_file: /etc/certs/tls.crt   # remember to set enabled!
          # private_key_file: /etc/certs/tls.key  # remember to set enabled!
          # Enable TLS ALPN protocol, typically HTTP2 to negotiate it with
          # HTTP2 clients over TLS.
          # This must be set to be able to use grpc over TLS.
          # alpn_protocols: h2
        # The 'client' block configures TLS client-certificate authentication.
        # 'enabled' is the only required element.
        client:
          # If 'enabled' is not True, TLS client-certificate authentication will
          # not happen.
          enabled: False

          # If 'cert_required' is True, TLS client certificates will be required
          # for every connection.
          # cert_required: False
          # This is optional. It should not be present unless you are using
          # a custom Docker build to install certificates onto the container
          # filesystem, in which case YOU WILL STILL NEED TO SET enabled: True
          # above.
          #
          # cacert_chain_file: /etc/cacert/tls.crt  # remember to set enabled!
spec:
  type: LoadBalancer
  # This must be a static IP in the same GCP region as the cluster.
  loadBalancerIP: <redacted>
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  selector:
    service: ambassador
```
</details>

2. cert-manager is running in its own namespace, "cert-manager":
<details>
 <summary>YAML config</summary>

```yaml
# Source: cert-manager/templates/00-namespace.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: "cert-manager"
  labels:
    name: "cert-manager"
    certmanager.k8s.io/disable-validation: "true"

---
# Source: cert-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: "cert-manager"
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
---
# Source: cert-manager/templates/certificate-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.certmanager.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Certificate
    plural: certificates
    shortNames:
      - cert
      - certs

---
# Source: cert-manager/templates/challenge-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: challenges.certmanager.k8s.io
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: Challenge
    plural: challenges
  scope: Namespaced
---
# Source: cert-manager/templates/clusterissuer-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.certmanager.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: ClusterIssuer
    plural: clusterissuers
  scope: Cluster
---
# Source: cert-manager/templates/issuer-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issuers.certmanager.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: Issuer
    plural: issuers
  scope: Namespaced
---
# Source: cert-manager/templates/order-crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: orders.certmanager.k8s.io
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: Order
    plural: orders
  scope: Namespaced
---
# Source: cert-manager/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
rules:
  - apiGroups: ["certmanager.k8s.io"]
    resources:
      ["certificates", "issuers", "clusterissuers", "orders", "challenges"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "events", "services", "pods"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager
subjects:
  - name: cert-manager
    namespace: "cert-manager"
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-view
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "issuers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-edit
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["certmanager.k8s.io"]
    resources: ["certificates", "issuers"]
    verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
# Source: cert-manager/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager
  namespace: "cert-manager"
  labels:
    app: cert-manager
    chart: cert-manager-v0.6.0-dev.6
    release: cert-manager
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
      release: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
        release: cert-manager
      annotations:
    spec:
      serviceAccountName: cert-manager
      containers:
        - name: cert-manager
          image: "quay.io/jetstack/cert-manager-controller:canary"
          imagePullPolicy: Always
          args:
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --leader-election-namespace=$(POD_NAMESPACE)
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
```
</details>

3. A ClusterIssuer is created, answering DNS challenges:
<details>
 <summary>YAML config</summary>

```yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <my email>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: prod-clouddns
          clouddns:
            project: <redacted>
            serviceAccountSecretRef:
              name: prod-clouddns-svc-acct-secret
              key: cert-manager-svc-acct.json
```
</details>

4. A Certificate for cert-manager to establish:
<details>
 <summary>YAML config</summary>

```yaml
# See https://www.getambassador.io/user-guide/tls-termination/.
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: foo-cert
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: foo.kumo.run
  dnsNames:
    - foo.kumo.run
  acme:
    config:
      - dns01:
          provider: prod-clouddns
        domains:
          - foo.kumo.run
```
</details>

I can see from the cert-manager logs that the actual SSL certificate is acquired successfully and a Secret named `ambassador-certs` is created with the appropriate contents. However, when I try to execute an https query against Ambassador it's not happy:

```
~ $ curl https://foo.kumo.run -v
* Rebuilt URL to: https://foo.kumo.run/
*   Trying 35.236.77.11...
* TCP_NODELAY set
* Connected to foo.kumo.run (35.236.77.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

And yet nothing shows up in the Ambassador logs. I've tried restarting the Ambassador service in order to encourage it to pick up on the new certificate, but no matter what I try I keep getting the same exact error. It doesn't matter if it's a certificate from the staging Let's Encrypt server or from prod.

It may also be worth noting that http requests to port 443 still work:
```
~ -> curl http://foo.kumo.run:443
Hello, world!
Version: 1.0.0
Hostname: foo-deployment-667cf67d6-92wnv
```

**To Reproduce**
Steps to reproduce the behavior: everything explained above.

**Expected behavior**
Ambassador to pick up on the cert in `ambassador-certs` as specified and respond correctly to https queries.

**Versions (please complete the following information):**
 - Ambassador: 0.40.1
 - Kubernetes environment: GKE

**Additional context**
Documentation around TLS termination leaves a bit to be desired. For example, section 4 here (https://www.getambassador.io/user-guide/tls-termination/) indicates that "sometimes" you'll need this extra config in order to make things work. Well why sometimes? What are those times? In what situations should that be necessary or unnecessary?

**Comment by samuela** [comment]
Just tried 0.40.2 and the same thing happens.

**Comment by samuela** [comment]
0.50.0-ea6 gives me the following error on Ambassador startup:
```
2018-11-27 08:55:46 kubewatch 0.50.0 INFO: generating config with gencount 1 (14 changes)
/usr/lib/python3.6/site-packages/pkg_resources/__init__.py:1235: UserWarning: /ambassador is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 448, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 427, in main
    sync(restarter)
  File "/ambassador/kubewatch.py", line 361, in sync
    restarter.restart()
  File "/ambassador/kubewatch.py", line 188, in restart
    bootstrap_config, ads_config = self.generate_config(output)
  File "/ambassador/kubewatch.py", line 243, in generate_config
    aconf.load_all(resources)
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/config.py", line 174, in load_all
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/config.py", line 241, in process
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/config.py", line 419, in handle_mapping
  File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/config/config.py", line 315, in safe_store
Exception: <Mapping service default-drshrey-kumo-service, namespace drshrey-kumo-451d4f8e-e954-4f5a-b0d6-4ca97927a401.1> defines Mapping default-drshrey-kumo-mapping, which is already present
AMBASSADOR: kubewatch sync exited with status 1
AMBASSADOR: shutting down (1)
```

**Comment by samuela** [comment]
Other interesting aspect/issue: the service should be accessible over http on port 80 but it's not. I can only get to it on port 443:
```
$ curl http://foo.kumo.run -v 
* Rebuilt URL to: http://foo.kumo.run/
*   Trying 35.236.77.11...
* TCP_NODELAY set
* Connection failed
* connect to 35.236.77.11 port 80 failed: Connection refused
* Failed to connect to foo.kumo.run port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to foo.kumo.run port 80: Connection refused
```
Again, this isn't showing up anywhere in the Ambassador logs.

Here's the foo service FWIW:
<details>
 <summary>YAML config</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    kumo-customer-deploy-id: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  namespace: foo
spec:
  # For some reason the Deployment doesn't know which Pods it owns without
  # specifying labels manually.
  selector:
    matchLabels:
      app: label.app.foo
  template:
    metadata:
      labels:
        app: label.app.foo
    spec:
      containers:
        - name: foo-container
          image: gcr.io/google-samples/hello-app:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: foo-service
  namespace: foo
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: foo-mapping
      prefix: /
      host: foo\..*
      host_regex: true
      service: foo-service.foo
spec:
  type: ClusterIP
  # Tells the Service which Pods it should be caring about.
  selector:
    app: label.app.foo
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
---
# Only applies to pods in the foo Namespace.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: foo
spec:
  # Match all pods in this Namespace.
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Allow ingress traffic from the Ambassador proxy for external traffic.
        - namespaceSelector:
            matchLabels:
              app: ambassador-proxy
        # Allow traffic within this namespace.
        - namespaceSelector:
            matchLabels:
              kumo-customer-deploy-id: foo
```
</details>

**Comment by idealhack** [comment]
+1 on 0.40.0

**Comment by nbkrause** [comment]
Could you try identifying the certificate in the TLS `Module`? You will also need to set `redirect_cleartext_from: 80` in the TLS `Module`.

```
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Module
      name: TLS
      config:
        server:
          enabled: true
          secret: ambassador-certs
          redirect_cleartext_from: 80
```

**Comment by idealhack** [comment]
I think I didn’t write `secret: ambassador-certs` in the annotation because I didn’t see it in the documentation. Will try it tomorrow.

**Comment by samuela** [comment]
I also didn't write `secret: ambassador-certs` since it wasn't mentioned in the docs.

Also is there a material difference between `name: TLS` and `name: tls`. The docs (https://www.getambassador.io/user-guide/tls-termination/) use lowercase. Which one is correct?

@nbkrause I tried updating my service as follows:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  annotations:
    getambassador.io/config: |
      # From https://www.getambassador.io/user-guide/tls-termination/.
      apiVersion: ambassador/v0
      kind: Module
      name: TLS
      config:
        # The 'server' block configures TLS termination. 'enabled' is the only
        # required element.
        server:
          # If 'enabled' is not True, TLS termination will not happen.
          enabled: True
          # If you set 'redirect_cleartext_from' to a port number, HTTP traffic
          # to that port will be redirected to HTTPS traffic. Typically you would
          # use port 80, of course.
          redirect_cleartext_from: 80
          secret: ambassador-certs

          # These are optional. They should not be present unless you are using
          # a custom Docker build to install certificates onto the container
          # filesystem, in which case YOU WILL STILL NEED TO SET enabled: True
          # above.
          #
          # cert_chain_file: /etc/certs/tls.crt   # remember to set enabled!
          # private_key_file: /etc/certs/tls.key  # remember to set enabled!
          # Enable TLS ALPN protocol, typically HTTP2 to negotiate it with
          # HTTP2 clients over TLS.
          # This must be set to be able to use grpc over TLS.
          # alpn_protocols: h2
        # The 'client' block configures TLS client-certificate authentication.
        # 'enabled' is the only required element.
        client:
          # If 'enabled' is not True, TLS client-certificate authentication will
          # not happen.
          enabled: False

          # If 'cert_required' is True, TLS client certificates will be required
          # for every connection.
          # cert_required: False
          # This is optional. It should not be present unless you are using
          # a custom Docker build to install certificates onto the container
          # filesystem, in which case YOU WILL STILL NEED TO SET enabled: True
          # above.
          #
          # cacert_chain_file: /etc/cacert/tls.crt  # remember to set enabled!
spec:
  type: LoadBalancer
  # This must be a static IP in the same GCP region as the cluster.
  loadBalancerIP: <redacted>
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  selector:
    service: ambassador
```
Now I get the following behavior:
```
$$$ curl http://foo.kumo.run -v
* Rebuilt URL to: http://foo.kumo.run/
*   Trying 35.236.77.11...
* TCP_NODELAY set
* Connected to foo.kumo.run (35.236.77.11) port 80 (#0)
> GET / HTTP/1.1
> Host: foo.kumo.run
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Thu, 29 Nov 2018 09:23:20 GMT
< content-length: 70
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 0
< server: envoy
< 
Hello, world!
Version: 1.0.0
Hostname: foo-deployment-667cf67d6-2hjl2
* Connection #0 to host foo.kumo.run left intact
$$$ curl https://foo.kumo.run -v
* Rebuilt URL to: https://foo.kumo.run/
*   Trying 35.236.77.11...
* TCP_NODELAY set
* Connection failed
* connect to 35.236.77.11 port 443 failed: Connection refused
* Failed to connect to foo.kumo.run port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to foo.kumo.run port 443: Connection refused
```
So now HTTP has been magically fixed, and HTTPS is still not working but with a different error...

**Comment by samuela** [comment]
Does it matter that the ambassador Service and the `ambassador-certs` Secret are in different kubernetes namespaces?

**Comment by idealhack** [comment]
I saw the same thing as @samuela. I was about to ask the secrets in different namespaces question.

**Comment by idealhack** [comment]
I copied the secret to the namespace of Ambassador, and it works... So I wonder what's the best practices here, Should we make every certificate of cert-manager in the namespace of Ambassador?

**Comment by nbkrause** [comment]
@samuela @idealhack That would be your issue. 

According to the kubernetes documentation https://kubernetes.io/docs/concepts/configuration/secret/#details
> Secret API objects reside in a namespace. They can only be referenced by pods in that same namespace.

So the only approach is to have every secret Ambassador will need in the same namespace as Ambassador. 

As far as identifying the secret name in the tls module, you should not need to do that in and pre-`0.50.0` version of Ambassador if your secret is named `ambassador-certs`. Ambassador will automatically check for a secret with that name and use it for TLS termination if it exists. I made that suggestion just for troubleshooting purposes.

**Comment by idealhack** [comment]
@nbkrause Thanks for your help!

Another question, Ambassador document suggest adding the annotation on the `ambassador` service, but what about we have multiple certificates? I guess the annotations should be added to the services which need TLS?

**Comment by samuela** [comment]
Multiple certificates is also a huge issue for me! Also is it possible to serve https over arbitrary ports? Like map an entire range of ports to be on https?

Is there any way to point Ambassador to ambassador-certs in a different namespace? I ask because I'm not sure that cert-manager can be configured to dump ambassador-certs in a namespace other than "default".

**Comment by nbkrause** [comment]
@samuela No that's a limitation of Kubernetes. You can specify the namespace cert-manager creates the secret in the `Certificate` definition yaml. 

```
kind: Certificate
metadata:
  name: domain3
  namespace: default     # Change to namespace you want secret created
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: example.com
  dnsNames:
  - example.com
  acme:
    config:
    - dns01:
        provider: <DNS Provider>
      domains:
      - example.com
```
@idealhack @samuela Once TLS termination is enabled in ambassador, it requires all requests be routed over HTTPS so putting the tls `Module` in the Ambassador service definition seems to make sense since it is a global config. Now if you are looking for multiple services to use authenticate with different certificates (SNI), you will need to use a `TLSContext` resource which is only available in `0.50.0-ea6` currently. https://www.getambassador.io/user-guide/sni

It is possible to serve https over any port. You need to configure your service to listen on any port and target the traffic to 443. i.e 

```
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  ports:
   - name: port1
      port: 8000
      targetPort: 443
   - name: port1
      port: 8001
      targetPort: 443
   - name: port1
      port: 8002
      targetPort: 443
  selector:
    service: ambassador
```
As you can see, doing a range would be ugly since you will need to manually add another port definition (again a Kubernetes limitation)
